# Generated by Django 5.1.6 on 2025-03-14 03:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DR', '草稿'), ('PB', '已发布'), ('AR', '已归档')], default='DR', max_length=2, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('slug', models.SlugField(blank=True, max_length=250, unique_for_date='publish_date', verbose_name='URL别名')),
                ('content', models.TextField(verbose_name='内容')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='发布时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='浏览数')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name': '文章管理',
                'verbose_name_plural': '文章管理',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=250)),
                ('articles', models.ManyToManyField(related_name='categories', to='articles.article', verbose_name='文章列表')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='标签名称')),
                ('articles', models.ManyToManyField(related_name='tags', to='articles.article', verbose_name='文章列表')),
            ],
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['publish_date'], name='articles_publish_date_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status'], name='articles_status_idx'),
        ),
    ]
