---
# 定义用户账户应用的菜单项
menu_slug: "accounts"
items:
  - name: 用户管理
    icon: icon-[tabler--user-circle]
    is_group_header: true
    children:
        - name: 用户中心
          named_url: accounts:home
          icon: icon-[tabler--user]
          is_visible: true
          login_required: true

        - name: 个人资料
          named_url: accounts:profile
          icon: icon-[tabler--id]
          is_visible: true
          login_required: true

        - name: 邀请注册
          named_url: accounts:generate_invitation
          icon: icon-[tabler--user-plus]
          is_visible: true
          login_required: true
          required_perms: accounts.add_ivitationcode
