---
# 定义Samba应用的菜单项

menu_slug: "samba"
items:
  - name: "开通Samba账户"
    icon: icon-[tabler--user-circle]
    is_group_header: true
    children:
        - name: SMB账户
          named_url: samba:accounts
          icon: icon-[tabler--users-plus]
          is_visible: true
          login_required: true



  
