# Generated by Django 6.0.6 on 2026-06-17 10:52

import archives.models
import core.uploads
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='绑定对象 ID')),
                ('asset_type', models.CharField(choices=[('test_project', '试题'), ('marking_scheme', '评分表'), ('marking_standard', '评分标准'), ('scoring_script', '评分脚本'), ('result_package', '结果包'), ('score_sheet', '成绩表'), ('training_log', '训练日志'), ('meeting_record', '会议记录'), ('learning_resource', '学习资料'), ('attachment', '附件'), ('other', '其他')], default='other', max_length=40, verbose_name='资料类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('file', models.FileField(help_text='上传资料文件，支持 pdf, doc, docx, xls, xlsx, ppt, pptx, zip, gz, bz2, rar, 7z, json, txt, csv, png, jpg, jpeg，大小不超过 100MB', storage=core.uploads.PrivateMediaStorage('archives'), upload_to=archives.models.archive_asset_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'zip', 'gz', 'bz2', 'rar', '7z', 'json', 'txt', 'csv', 'png', 'jpg', 'jpeg'), message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, ppt, pptx, zip, gz, bz2, rar, 7z, json, txt, csv, png, jpg, jpeg'), core.uploads.UploadSizeValidator(100)], verbose_name='文件')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('file_sha256', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='文件 SHA256')),
                ('business_date', models.DateField(db_index=True, default=django.utils.timezone.localdate, verbose_name='业务日期')),
                ('source_system', models.CharField(blank=True, max_length=100, verbose_name='来源系统')),
                ('source_external_id', models.CharField(blank=True, max_length=150, verbose_name='外部 ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('is_locked', models.BooleanField(default=False, verbose_name='已锁定')),
                ('skill_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archive_assets', to='standards.skillproject', verbose_name='技能项目')),
                ('target_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_assets', to='contenttypes.contenttype', verbose_name='绑定对象类型')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_assets', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '资料资产',
                'verbose_name_plural': '资料资产',
                'ordering': ['-business_date', '-uploaded_at', '-pk'],
            },
        ),
    ]
