# Generated by Django 6.0.6 on 2026-06-17 10:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standards', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='赛事级别代码')),
                ('name', models.CharField(max_length=120, verbose_name='赛事级别名称')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='统计权重')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '赛事级别',
                'verbose_name_plural': '赛事级别',
                'ordering': ['order', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='赛事系列代码')),
                ('name', models.CharField(max_length=120, verbose_name='赛事系列名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '赛事系列',
                'verbose_name_plural': '赛事系列',
                'ordering': ['order', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('competition', '正式竞赛'), ('assessment', '训练考核'), ('mock_exam', '模拟赛'), ('training_test', '训练测试'), ('other', '其他事件')], max_length=30, verbose_name='事件类型')),
                ('name', models.CharField(max_length=150, verbose_name='事件名称')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='事件代码')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('location', models.CharField(blank=True, max_length=150, verbose_name='地点')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('active', '进行中'), ('completed', '已完成'), ('archived', '已归档'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.competitionlevel', verbose_name='赛事级别')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.competitionseries', verbose_name='赛事系列')),
                ('skill_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='standards.skillproject', verbose_name='技能项目')),
                ('training_cycle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='training.trainingcycle', verbose_name='训练周期')),
            ],
            options={
                'verbose_name': '事件',
                'verbose_name_plural': '事件',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EventModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='模块代码')),
                ('name', models.CharField(max_length=150, verbose_name='模块名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('total_mark', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='总分')),
                ('duration_minutes', models.PositiveIntegerField(default=0, verbose_name='时长（分钟）')),
                ('counts_towards_ranking', models.BooleanField(default=True, verbose_name='计入排名分')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='events.event', verbose_name='事件')),
            ],
            options={
                'verbose_name': '事件模块',
                'verbose_name_plural': '事件模块',
                'ordering': ['event', 'order', 'code', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EventModuleCapabilityDomainMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主领域')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='权重')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('capability_domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_module_mappings', to='standards.capabilitydomain', verbose_name='能力领域')),
                ('event_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domain_mappings', to='events.eventmodule', verbose_name='事件模块')),
            ],
            options={
                'verbose_name': '事件模块能力领域映射',
                'verbose_name_plural': '事件模块能力领域映射',
                'ordering': ['event_module', '-is_primary', 'capability_domain__order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(blank=True, max_length=100, verbose_name='外部编号')),
                ('display_name', models.CharField(max_length=150, verbose_name='显示名称')),
                ('role', models.CharField(choices=[('competitor', '选手'), ('expert', '专家'), ('coach', '教练'), ('staff', '工作人员'), ('observer', '观察员'), ('other', '其他')], default='competitor', max_length=30, verbose_name='角色')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='所属单位')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='events.event', verbose_name='事件')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_participations', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '事件参与人员',
                'verbose_name_plural': '事件参与人员',
                'ordering': ['event', 'role', 'display_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EventResultSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='总分')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='排名')),
                ('award', models.CharField(blank=True, max_length=100, verbose_name='奖项')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_summaries', to='events.event', verbose_name='事件')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result_summary', to='events.eventparticipant', verbose_name='参与人员')),
            ],
            options={
                'verbose_name': '事件结果汇总',
                'verbose_name_plural': '事件结果汇总',
                'ordering': ['event', 'rank', '-total_score', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='eventmodule',
            constraint=models.UniqueConstraint(fields=('event', 'code'), name='uniq_eventmodule_event_code'),
        ),
        migrations.AddConstraint(
            model_name='eventmodulecapabilitydomainmap',
            constraint=models.UniqueConstraint(fields=('event_module', 'capability_domain'), name='uniq_eventmodule_domain'),
        ),
        migrations.AddConstraint(
            model_name='eventmodulecapabilitydomainmap',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('event_module',), name='uniq_primary_domain_per_eventmodule'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('event', 'user'), name='uniq_eventparticipant_event_user'),
        ),
        migrations.AddConstraint(
            model_name='eventparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('external_code', ''), _negated=True), fields=('event', 'external_code'), name='uniq_eventparticipant_event_external_code'),
        ),
    ]
