# Generated by Django 6.0.6 on 2026-06-17 10:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('events', '0001_initial'),
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('exam_requirement', '试题要求'), ('scoring_aspect', '评分点'), ('marking_standard', '评分标准条目'), ('script_check', '评分脚本检查项'), ('cmp_result_item', 'CMP 回传评分项'), ('manual', '教练手工补充考点'), ('other', '其他')], max_length=40, verbose_name='来源类型')),
                ('source_object_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='来源对象 ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('original_text', models.TextField(blank=True, verbose_name='原始文本')),
                ('normalized_text', models.TextField(blank=True, verbose_name='规范化文本')),
                ('estimated_mark', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='分值估计')),
                ('estimated_difficulty', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='难度估计')),
                ('evidence_level', models.CharField(blank=True, max_length=50, verbose_name='证据等级')),
                ('extraction_source', models.CharField(choices=[('manual', '人工'), ('parser', '解析器'), ('ai', 'AI'), ('cmp', 'CMP'), ('imported', '导入')], default='manual', max_length=20, verbose_name='提取来源')),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='置信度')),
                ('review_status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='draft', max_length=20, verbose_name='审核状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_note', models.TextField(blank=True, verbose_name='审核备注')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('capability_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_evidences', to='standards.capabilitydomain', verbose_name='能力领域')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_knowledge_evidences', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('event_module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_evidences', to='events.eventmodule', verbose_name='事件模块')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_knowledge_evidences', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('skill_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_evidences', to='standards.skillproject', verbose_name='技能项目')),
                ('source_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_evidences', to='contenttypes.contenttype', verbose_name='来源对象类型')),
            ],
            options={
                'verbose_name': '考点证据',
                'verbose_name_plural': '考点证据',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeEvidenceSkillMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主技能点')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='权重')),
                ('mapping_source', models.CharField(choices=[('manual', '人工'), ('ai', 'AI'), ('imported', '导入'), ('parser', '解析器')], default='manual', max_length=20, verbose_name='映射来源')),
                ('confidence', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='置信度')),
                ('reason', models.TextField(blank=True, verbose_name='理由')),
                ('review_status', models.CharField(choices=[('draft', '草稿'), ('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='draft', max_length=20, verbose_name='审核状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_mappings', to='knowledge.knowledgeevidence', verbose_name='考点证据')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_knowledge_skill_mappings', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('skill_node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_evidence_mappings', to='standards.skillnode', verbose_name='技能点')),
            ],
            options={
                'verbose_name': '考点技能映射',
                'verbose_name_plural': '考点技能映射',
                'ordering': ['evidence', '-is_primary', 'skill_node__order', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('evidence', 'skill_node'), name='uniq_knowledge_evidence_skill_node'), models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('evidence',), name='uniq_knowledge_primary_skill_per_evidence')],
            },
        ),
    ]
