# Generated by Django 6.0.6 on 2026-06-15 14:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition_standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='技能树名称')),
                ('version', models.CharField(default='v1', max_length=50, verbose_name='版本')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skill_trees', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_trees', to='competition_standards.standardmodule', verbose_name='标准模块')),
            ],
            options={
                'verbose_name': '技能树',
                'verbose_name_plural': '技能树',
                'ordering': ['module__project__name', 'module__code', '-is_current', 'version', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='节点代码')),
                ('name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('node_type', models.CharField(choices=[('category', '分类'), ('topic', '专题'), ('skill', '技能点'), ('task', '训练任务')], default='skill', max_length=20, verbose_name='节点类型')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, help_text='1 最简单，5 最难。', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='默认难度')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='skilltrees.skillnode', verbose_name='父节点')),
                ('tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='skilltrees.skilltree', verbose_name='技能树')),
            ],
            options={
                'verbose_name': '技能树节点',
                'verbose_name_plural': '技能树节点',
                'ordering': ['tree', 'parent_id', 'sort_order', 'code', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='skilltree',
            constraint=models.UniqueConstraint(fields=('module', 'version'), name='uniq_skilltree_module_version'),
        ),
        migrations.AddConstraint(
            model_name='skilltree',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('module',), name='uniq_current_skilltree_per_module'),
        ),
        migrations.AddConstraint(
            model_name='skillnode',
            constraint=models.UniqueConstraint(fields=('tree', 'code'), name='uniq_skillnode_tree_code'),
        ),
    ]
