# Generated by Django 6.0.1 on 2026-02-05 04:58

import behaviors.models
import core.utils.validators
import django.core.validators
import functools
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductrecord',
            name='attachment',
            field=models.FileField(blank=True, help_text='支持PDF、图片等格式，文件大小不超过 50MB', null=True, upload_to=behaviors.models.conduct_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png'], message='仅支持以下文件格式: pdf, jpg, jpeg, png'), functools.partial(core.utils.validators.validate_file_size, max_size_mb=50)], verbose_name='附件'),
        ),
        migrations.AlterField(
            model_name='conductrecord',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='默认使用选中类型的分值，可微调', max_digits=6, null=True, verbose_name='实际得分'),
        ),
    ]
