# Generated by Django 6.0.4 on 2026-05-20 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviors', '0011_alter_conductrecord_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='conductcategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='conductitem',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='conductseverityrule',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='conductcategory',
            constraint=models.UniqueConstraint(fields=('nature', 'name'), name='uniq_conduct_category_nature_name'),
        ),
        migrations.AddConstraint(
            model_name='conductitem',
            constraint=models.UniqueConstraint(fields=('category', 'name'), name='uniq_conduct_item_category_name'),
        ),
        migrations.AddConstraint(
            model_name='conductseverityrule',
            constraint=models.UniqueConstraint(fields=('nature', 'severity'), name='uniq_conduct_severity_rule_nature_severity'),
        ),
    ]
