# Generated by Django 6.0.6 on 2026-08-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behaviors', '0012_alter_conductcategory_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductrecord',
            options={'ordering': ['-occurred_date', '-recorded_at'], 'permissions': [('be_conduct_subject', '可作为奖惩对象'), ('add_conduct_record', '录入奖惩记录'), ('review_conduct_record', '审核奖惩记录'), ('view_all_conduct_records', '查看所有奖惩记录')], 'verbose_name': '奖惩记录', 'verbose_name_plural': '奖惩记录'},
        ),
    ]
