# Generated by Django 6.0.6 on 2026-08-13 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviors', '0012_alter_conductcategory_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductrecord',
            name='student',
            field=models.ForeignKey(limit_choices_to={'groups__profile__codename': 'competitor'}, on_delete=django.db.models.deletion.CASCADE, related_name='conduct_records', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
        migrations.AlterField(
            model_name='conductsummary',
            name='student',
            field=models.OneToOneField(limit_choices_to={'groups__profile__codename': 'competitor'}, on_delete=django.db.models.deletion.CASCADE, related_name='conduct_summary', to=settings.AUTH_USER_MODEL, verbose_name='学生'),
        ),
    ]
