# Generated by Django 6.0.6 on 2026-08-14 05:48

import behaviors.models
import core.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behaviors', '0014_alter_conductrecord_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductrecord',
            name='attachment',
            field=models.FileField(blank=True, help_text='上传奖惩附件，支持 pdf, jpg, jpeg, png，大小不超过 50MB', null=True, storage=core.uploads.PrivateMediaStorage('behaviors'), upload_to=behaviors.models.conduct_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'jpg', 'jpeg', 'png'), message='仅支持以下格式的文件：pdf, jpg, jpeg, png'), core.uploads.UploadSizeValidator(50)], verbose_name='附件'),
        ),
    ]
