# Generated by Django 6.0 on 2026-01-06 00:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='考核名称')),
                ('date', models.DateField(help_text='考核进行的日期', verbose_name='考核日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('participants', models.ManyToManyField(blank=True, help_text='参加本次考核的人员', related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='参考人员')),
            ],
            options={
                'verbose_name': '考核',
                'verbose_name_plural': '考核',
                'ordering': ['-date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('25.00'))], verbose_name='得分')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessment.assessment', verbose_name='所属考核')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_scores', to='competitions.module', verbose_name='考核模块')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to=settings.AUTH_USER_MODEL, verbose_name='选手')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'ordering': ['assessment', 'user', 'module'],
                'unique_together': {('assessment', 'user', 'module')},
            },
        ),
    ]
