# Generated by Django 6.0 on 2026-01-06 01:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-start_date', 'name'], 'verbose_name': '考核', 'verbose_name_plural': '考核'},
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='date',
        ),
        migrations.AddField(
            model_name='assessment',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='考核结束的日期', verbose_name='结束日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessment',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='本次考核包含的模块', related_name='assessments', to='competitions.module', verbose_name='考核模块'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='考核开始的日期', verbose_name='开始日期'),
            preserve_default=False,
        ),
    ]
