# Generated by Django 6.0 on 2026-01-06 02:20

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_assessment_options_remove_assessment_date_and_more'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='modules',
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='得分'),
        ),
        migrations.CreateModel(
            name='AssessmentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='该模块在本次考核中的满分值', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='模块总分')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment', verbose_name='考核')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.module', verbose_name='模块')),
            ],
            options={
                'verbose_name': '考核模块配置',
                'verbose_name_plural': '考核模块配置',
                'unique_together': {('assessment', 'module')},
            },
        ),
    ]
