# Generated by Django 6.0 on 2026-01-06 02:45

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_assessment_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmodule',
            name='max_score',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='该模块在本次考核中的满分值', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='模块总分'),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
