# Generated by Django 6.0 on 2026-01-19 08:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_remove_assessment_paper_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmodule',
            name='duration',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='该模块的考核时长，单位为小时', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='考核时长(小时)'),
        ),
    ]
