# Generated by Django 6.0 on 2026-01-20 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_alter_assessment_modules_and_more'),
        ('competitions', '0008_alter_competitionmodule_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='本次考核包含的模块', related_name='assessments', through='assessment.AssessmentModule', to='competitions.module', verbose_name='考核模块'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competitions.module', verbose_name='模块'),
        ),
    ]
