# Generated by Django 6.0.1 on 2026-01-29 05:41

import assessment.models
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_alter_assessment_modules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmodule',
            name='paper_file',
            field=models.FileField(blank=True, help_text='请上传文件，支持 xls, xlsx, csv, pdf, doc, docx, jpg, jpeg, png, zip, 7z, gz, bz2, rar，大小不超过 100MB', storage=django.core.files.storage.FileSystemStorage(location='E:\\01-04-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessment'), upload_to=assessment.models.assessment_paper_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar']), assessment.models.validate_file_size], verbose_name='试卷及评分文件'),
        ),
    ]
