# Generated by Django 6.0.1 on 2026-02-04 06:32

import assessment.models
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_alter_assessmentmodule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentattachment',
            name='file',
            field=models.FileField(help_text='上传附件文件，支持 pdf, doc, docx, xls, xlsx, csv, txt, jpg, jpeg, png, gif, zip, 7z, gz, bz2, rar，大小不超过 100MB', storage=django.core.files.storage.FileSystemStorage(location='D:\\04-01-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessment'), upload_to=assessment.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'txt', 'jpg', 'jpeg', 'png', 'gif', 'zip', '7z', 'gz', 'bz2', 'rar']), assessment.models.validate_assessment_attachment_file_size], verbose_name='附件文件'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='question_file',
            field=models.FileField(blank=True, help_text='上传试题文件，支持 pdf, doc, docx，大小不超过 50MB', storage=django.core.files.storage.FileSystemStorage(location='D:\\04-01-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessment'), upload_to=assessment.models.question_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx']), assessment.models.validate_assessment_tp_file_size], verbose_name='试题文件'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='scoring_script_file',
            field=models.FileField(blank=True, help_text='上传评分脚本文件（非必须），支持 py, sh, bat, exe, ps1, yml, yaml，大小不超过 50MB', storage=django.core.files.storage.FileSystemStorage(location='D:\\04-01-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessment'), upload_to=assessment.models.scoring_script_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['py', 'sh', 'bat', 'exe', 'ps1', 'yml', 'yaml']), assessment.models.validate_assessment_ms_file_size], verbose_name='评分脚本文件'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='scoring_sheet_file',
            field=models.FileField(blank=True, help_text='上传评分表文件（非必须），支持 pdf, doc, docx, xls, xlsx, csv，大小不超过 50MB', storage=django.core.files.storage.FileSystemStorage(location='D:\\04-01-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessment'), upload_to=assessment.models.scoring_sheet_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv']), assessment.models.validate_assessment_mt_file_size], verbose_name='评分表文件'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='scoring_standard_file',
            field=models.FileField(blank=True, help_text='上传评分标准文件，支持 pdf, doc, docx, xls, xlsx, csv，大小不超过 50MB', storage=django.core.files.storage.FileSystemStorage(location='D:\\04-01-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessment'), upload_to=assessment.models.scoring_standard_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv']), assessment.models.validate_assessment_mc_file_size], verbose_name='评分标准文件'),
        ),
    ]
