# Generated by Django 6.0.3 on 2026-04-09 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0019_alter_assessmentattachment_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentmodule',
            options={'ordering': ['assessment', 'sort_order', 'module__code', 'pk'], 'verbose_name': '考核模块', 'verbose_name_plural': '考核模块'},
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, help_text='数值越小越靠前显示', verbose_name='显示顺序'),
        ),
    ]
