# Generated by Django 6.0.3 on 2026-04-10 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0021_assessmentmodule_responsible_coach'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmodule',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='锁定后成绩不可修改', verbose_name='已锁定'),
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='锁定时间'),
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_assessment_modules', to=settings.AUTH_USER_MODEL, verbose_name='锁定人'),
        ),
    ]
