# Generated by Django 6.0.4 on 2026-05-18 08:12

import assessments.models
import core.uploads
import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='上传附件文件，支持 pdf, doc, docx, xls, xlsx, csv, txt, md, jpg, jpeg, png, gif, zip, 7z, gz, bz2, rar, tar，大小不超过 100MB', storage=core.uploads.PrivateMediaStorage('assessments'), upload_to=assessments.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'txt', 'md', 'jpg', 'jpeg', 'png', 'gif', 'zip', '7z', 'gz', 'bz2', 'rar', 'tar'), message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, csv, txt, md, jpg, jpeg, png, gif, zip, 7z, gz, bz2, rar, tar'), core.uploads.UploadSizeValidator(100)], verbose_name='附件文件')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='文件说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '考核附件',
                'verbose_name_plural': '考核附件',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='数值越小越靠前显示', verbose_name='显示顺序')),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('25.00'), help_text='该模块在本次考核中的满分值', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='模块总分')),
                ('duration', models.DecimalField(decimal_places=1, default=Decimal('0.0'), help_text='该模块的考核时长，单位为小时', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.0'))], verbose_name='考核时长(小时)')),
                ('is_locked', models.BooleanField(default=False, help_text='锁定后成绩不可修改', verbose_name='已锁定')),
                ('locked_at', models.DateTimeField(blank=True, null=True, verbose_name='锁定时间')),
                ('is_material_locked', models.BooleanField(default=False, help_text='锁定后资料不可修改', verbose_name='资料已锁定')),
                ('material_locked_at', models.DateTimeField(blank=True, null=True, verbose_name='资料锁定时间')),
                ('question_file', models.FileField(blank=True, help_text='上传试题文件，支持 pdf, doc, docx，大小不超过 50MB', storage=core.uploads.PrivateMediaStorage('assessments'), upload_to=assessments.models.question_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx'), message='仅支持以下格式的文件：pdf, doc, docx'), core.uploads.UploadSizeValidator(50)], verbose_name='试题文件')),
                ('scoring_standard_file', models.FileField(blank=True, help_text='上传评分标准文件，支持 pdf, doc, docx, xls, xlsx, csv，大小不超过 50MB', storage=core.uploads.PrivateMediaStorage('assessments'), upload_to=assessments.models.scoring_standard_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv'), message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, csv'), core.uploads.UploadSizeValidator(50)], verbose_name='评分标准文件')),
                ('scoring_sheet_file', models.FileField(blank=True, help_text='上传评分表文件，支持 pdf, doc, docx, xls, xlsx, csv，大小不超过 50MB', storage=core.uploads.PrivateMediaStorage('assessments'), upload_to=assessments.models.scoring_sheet_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv'), message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, csv'), core.uploads.UploadSizeValidator(50)], verbose_name='评分表文件')),
                ('scoring_script_file', models.FileField(blank=True, help_text='上传评分脚本文件，支持 py, sh, bat, exe, ps1, yml, yaml，大小不超过 50MB', storage=core.uploads.PrivateMediaStorage('assessments'), upload_to=assessments.models.scoring_script_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('py', 'sh', 'bat', 'exe', 'ps1', 'yml', 'yaml'), message='仅支持以下格式的文件：py, sh, bat, exe, ps1, yml, yaml'), core.uploads.UploadSizeValidator(50)], verbose_name='评分脚本文件')),
            ],
            options={
                'verbose_name': '考核模块',
                'verbose_name_plural': '考核模块',
                'ordering': ['assessment', 'sort_order', 'module__code', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='得分')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'ordering': ['assessment_module', 'user'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='考核名称')),
                ('start_date', models.DateField(help_text='考核开始的日期', verbose_name='开始日期')),
                ('end_date', models.DateField(help_text='考核结束的日期', verbose_name='结束日期')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('participants', models.ManyToManyField(blank=True, help_text='参加本次考核的人员', related_name='assessments', to=settings.AUTH_USER_MODEL, verbose_name='参考人员')),
            ],
            options={
                'verbose_name': '考核',
                'verbose_name_plural': '考核',
                'ordering': ['-start_date', 'name'],
                'permissions': [('view_all_scores', '可以查看所有人的考核成绩')],
            },
        ),
    ]
