# Generated by Django 6.0.6 on 2026-08-18 02:49

import assessments.models
import core.uploads
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('standards', '0001_initial'),
        ('training', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='级别代码')),
                ('name', models.CharField(max_length=120, verbose_name='级别名称')),
                (
                    'weight',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('1.00'),
                        max_digits=6,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='历史统计权重',
                    ),
                ),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '竞赛与考核级别',
                'verbose_name_plural': '竞赛与考核级别',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='系列代码')),
                ('name', models.CharField(max_length=120, verbose_name='系列名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '竞赛与考核系列',
                'verbose_name_plural': '竞赛与考核系列',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'assessment_type',
                    models.CharField(
                        choices=[
                            ('competition', '正式竞赛'),
                            ('selection', '选拔赛'),
                            ('exchange', '交流赛'),
                            ('mock', '模拟赛'),
                            ('training_assessment', '训练考核'),
                            ('training_test', '训练测试'),
                            ('other', '其他'),
                        ],
                        max_length=30,
                        verbose_name='类型',
                    ),
                ),
                ('name', models.CharField(max_length=180, verbose_name='名称')),
                ('code', models.CharField(max_length=80, unique=True, verbose_name='代码')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='地点')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', '草稿'),
                            ('published', '已发布'),
                            ('active', '进行中'),
                            ('completed', '已完成'),
                            ('archived', '已归档'),
                            ('cancelled', '已取消'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='状态',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'created_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_assessments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='创建人',
                    ),
                ),
                (
                    'skill_project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='assessments',
                        to='standards.skillproject',
                        verbose_name='技能项目',
                    ),
                ),
                (
                    'training_cycle',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='assessments',
                        to='training.trainingcycle',
                        verbose_name='训练周期',
                    ),
                ),
                (
                    'level',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='assessments',
                        to='assessments.assessmentlevel',
                        verbose_name='级别',
                    ),
                ),
                (
                    'series',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='assessments',
                        to='assessments.assessmentseries',
                        verbose_name='系列',
                    ),
                ),
            ],
            options={
                'verbose_name': '竞赛与考核',
                'verbose_name_plural': '竞赛与考核',
                'ordering': ['-start_date', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='模块代码')),
                ('name', models.CharField(max_length=150, verbose_name='模块名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                (
                    'total_mark',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='总分',
                    ),
                ),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='时长（分钟）')),
                ('counts_towards_ranking', models.BooleanField(default=True, verbose_name='计入排名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'assessment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='modules',
                        to='assessments.assessment',
                        verbose_name='竞赛与考核',
                    ),
                ),
            ],
            options={
                'verbose_name': '评测模块',
                'verbose_name_plural': '评测模块',
                'ordering': ['assessment', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'document_type',
                    models.CharField(
                        choices=[
                            ('test_project', '试题'),
                            ('marking_scheme', '评分表'),
                            ('marking_standard', '评分标准'),
                            ('scoring_script', '评分脚本'),
                            ('result_file', '成绩或结果文件'),
                            ('attachment', '其他附件'),
                        ],
                        max_length=30,
                        verbose_name='资料类型',
                    ),
                ),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                (
                    'file',
                    models.FileField(
                        help_text='上传文件，支持 pdf, doc, docx, xls, xlsx, ppt, pptx, zip, gz, bz2, rar, 7z, json, txt, csv, png, jpg, jpeg，大小不超过 100MB',
                        storage=core.uploads.PrivateMediaStorage('assessments'),
                        upload_to=assessments.models.assessment_document_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=(
                                    'pdf',
                                    'doc',
                                    'docx',
                                    'xls',
                                    'xlsx',
                                    'ppt',
                                    'pptx',
                                    'zip',
                                    'gz',
                                    'bz2',
                                    'rar',
                                    '7z',
                                    'json',
                                    'txt',
                                    'csv',
                                    'png',
                                    'jpg',
                                    'jpeg',
                                ),
                                message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, ppt, pptx, zip, gz, bz2, rar, 7z, json, txt, csv, png, jpg, jpeg',
                            ),
                            core.uploads.UploadSizeValidator(100),
                            core.uploads.UploadSignatureValidator(),
                        ],
                        verbose_name='文件',
                    ),
                ),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_sha256', models.CharField(editable=False, max_length=64, verbose_name='SHA256')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版本')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'assessment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='documents',
                        to='assessments.assessment',
                        verbose_name='竞赛与考核',
                    ),
                ),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='uploaded_assessment_documents',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='上传者',
                    ),
                ),
                (
                    'module',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='documents',
                        to='assessments.assessmentmodule',
                        verbose_name='评测模块',
                    ),
                ),
            ],
            options={
                'verbose_name': '评测资料',
                'verbose_name_plural': '评测资料',
                'ordering': ['assessment', 'module_id', 'document_type', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentModuleCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'role',
                    models.CharField(
                        choices=[('primary', '主教练'), ('collaborator', '协作教练')],
                        default='collaborator',
                        max_length=20,
                        verbose_name='角色',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                (
                    'assessment_module',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='coach_assignments',
                        to='assessments.assessmentmodule',
                        verbose_name='评测模块',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='assessment_module_assignments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='教练',
                    ),
                ),
            ],
            options={
                'verbose_name': '评测模块教练',
                'verbose_name_plural': '评测模块教练',
            },
        ),
        migrations.CreateModel(
            name='AssessmentModuleDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'role',
                    models.CharField(
                        choices=[('primary', '主要领域'), ('related', '关联领域')],
                        default='related',
                        max_length=20,
                        verbose_name='角色',
                    ),
                ),
                ('note', models.TextField(blank=True, verbose_name='说明')),
                (
                    'assessment_module',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='domain_mappings',
                        to='assessments.assessmentmodule',
                        verbose_name='评测模块',
                    ),
                ),
                (
                    'technical_domain',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='assessment_module_mappings',
                        to='standards.technicaldomain',
                        verbose_name='技术领域',
                    ),
                ),
            ],
            options={
                'verbose_name': '评测模块技术领域',
                'verbose_name_plural': '评测模块技术领域',
            },
        ),
        migrations.CreateModel(
            name='AssessmentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(blank=True, max_length=100, verbose_name='外部代码')),
                ('display_name', models.CharField(max_length=150, verbose_name='显示名称')),
                (
                    'role',
                    models.CharField(
                        choices=[
                            ('competitor', '选手'),
                            ('expert', '专家'),
                            ('coach', '教练'),
                            ('staff', '工作人员'),
                            ('observer', '观察员'),
                            ('other', '其他'),
                        ],
                        default='competitor',
                        max_length=20,
                        verbose_name='角色',
                    ),
                ),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='单位')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'assessment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='participants',
                        to='assessments.assessment',
                        verbose_name='竞赛与考核',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='assessment_participations',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='关联用户',
                    ),
                ),
            ],
            options={
                'verbose_name': '评测参与人员',
                'verbose_name_plural': '评测参与人员',
                'ordering': ['assessment', 'role', 'display_name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResultSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'total_score',
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='总分'),
                ),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='名次')),
                ('award', models.CharField(blank=True, max_length=100, verbose_name='奖项')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'assessment',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='result_summaries',
                        to='assessments.assessment',
                        verbose_name='竞赛与考核',
                    ),
                ),
                (
                    'participant',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='result_summary',
                        to='assessments.assessmentparticipant',
                        verbose_name='参与人员',
                    ),
                ),
            ],
            options={
                'verbose_name': '评测结果摘要',
                'verbose_name_plural': '评测结果摘要',
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentmodule',
            constraint=models.UniqueConstraint(
                fields=('assessment', 'code'), name='uniq_assessmentmodule_assessment_code'
            ),
        ),
        migrations.AddConstraint(
            model_name='assessmentdocument',
            constraint=models.UniqueConstraint(
                condition=models.Q(('module__isnull', False)),
                fields=('assessment', 'module', 'document_type', 'file_sha256'),
                name='uniq_assessment_document_module_hash',
            ),
        ),
        migrations.AddConstraint(
            model_name='assessmentdocument',
            constraint=models.UniqueConstraint(
                condition=models.Q(('module__isnull', True)),
                fields=('assessment', 'document_type', 'file_sha256'),
                name='uniq_assessment_document_general_hash',
            ),
        ),
        migrations.AddConstraint(
            model_name='assessmentmodulecoach',
            constraint=models.UniqueConstraint(
                fields=('assessment_module', 'user'), name='uniq_assessmentmodule_coach'
            ),
        ),
        migrations.AddConstraint(
            model_name='assessmentmodulecoach',
            constraint=models.UniqueConstraint(
                condition=models.Q(('role', 'primary')),
                fields=('assessment_module',),
                name='uniq_primary_coach_per_assessmentmodule',
            ),
        ),
        migrations.AddConstraint(
            model_name='assessmentmoduledomain',
            constraint=models.UniqueConstraint(
                fields=('assessment_module', 'technical_domain'), name='uniq_assessmentmodule_domain'
            ),
        ),
        migrations.AddConstraint(
            model_name='assessmentmoduledomain',
            constraint=models.UniqueConstraint(
                condition=models.Q(('role', 'primary')),
                fields=('assessment_module',),
                name='uniq_primary_domain_per_assessmentmodule',
            ),
        ),
        migrations.AddConstraint(
            model_name='assessmentparticipant',
            constraint=models.UniqueConstraint(
                condition=models.Q(('user__isnull', False)),
                fields=('assessment', 'user'),
                name='uniq_assessmentparticipant_user',
            ),
        ),
        migrations.AddConstraint(
            model_name='assessmentparticipant',
            constraint=models.UniqueConstraint(
                condition=models.Q(('external_code', ''), _negated=True),
                fields=('assessment', 'external_code'),
                name='uniq_assessmentparticipant_external',
            ),
        ),
    ]
