# Generated by Django 6.0.4 on 2026-05-18 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('curriculum', '0001_initial'),
        ('trainingcycles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='training_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='trainingcycles.trainingcycle', verbose_name='备赛周期'),
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.assessment', verbose_name='考核'),
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_assessment_modules', to=settings.AUTH_USER_MODEL, verbose_name='锁定人'),
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='material_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_locked_assessment_modules', to=settings.AUTH_USER_MODEL, verbose_name='资料锁定人'),
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='curriculum.standardmodule', verbose_name='模块'),
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='responsible_coach',
            field=models.ForeignKey(blank=True, help_text='只有该教练可以上传资料和录入成绩', limit_choices_to={'groups__name': '教练'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_assessment_modules', to=settings.AUTH_USER_MODEL, verbose_name='负责教练'),
        ),
        migrations.AddField(
            model_name='assessmentattachment',
            name='assessment_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assessments.assessmentmodule', verbose_name='考核模块'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='本次考核包含的模块', related_name='assessments', through='assessments.AssessmentModule', to='curriculum.standardmodule', verbose_name='考核模块'),
        ),
        migrations.AddField(
            model_name='score',
            name='assessment_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='assessments.assessmentmodule', verbose_name='考核模块'),
        ),
        migrations.AddField(
            model_name='score',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_scores', to=settings.AUTH_USER_MODEL, verbose_name='选手'),
        ),
        migrations.AlterUniqueTogether(
            name='assessmentmodule',
            unique_together={('assessment', 'module')},
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together={('assessment_module', 'user')},
        ),
    ]
