# Generated by Django 6.0.4 on 2026-05-20 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_assessmentmodule_counts_towards_ranking'),
        ('competition_standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assessmentmodule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='score',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='assessmentmodule',
            constraint=models.UniqueConstraint(fields=('assessment', 'module'), name='uniq_assessmentmodule_assessment_module'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('assessment_module', 'user'), name='uniq_score_assessmentmodule_user'),
        ),
    ]
