# Generated by Django 6.0 on 2026-01-06 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_remove_assessment_modules_alter_score_score_and_more'),
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='modules',
            field=models.ManyToManyField(blank=True, help_text='本次考核包含的模块', related_name='assessments', through='assessments.AssessmentModule', to='competitions.module', verbose_name='考核模块'),
        ),
    ]
