# Generated by Django 6.0.5 on 2026-05-22 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_alter_assessmentmodule_unique_together_and_more'),
        ('competition_standards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='competition_standards.standardmodule', verbose_name='标准模块'),
        ),
    ]
