# Generated by Django 6.0.6 on 2026-06-15 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clear_orphan_admin_log_content_types(apps, schema_editor):
    connection = schema_editor.connection
    existing_tables = set(connection.introspection.table_names())
    if not {"django_admin_log", "django_content_type"}.issubset(existing_tables):
        return
    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE django_admin_log
               SET content_type_id = NULL
             WHERE content_type_id IS NOT NULL
               AND content_type_id NOT IN (
                   SELECT id FROM django_content_type
               )
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_assessment_training_cycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clear_orphan_admin_log_content_types, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='score',
            name='uniq_score_assessmentmodule_user',
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='锁定后评分归档不可修改', verbose_name='已锁定'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='responsible_coach',
            field=models.ForeignKey(blank=True, help_text='只有该教练可以上传资料和管理评分归档', limit_choices_to={'groups__name': '教练'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_assessment_modules', to=settings.AUTH_USER_MODEL, verbose_name='负责教练'),
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
