# Generated by Django 6.0 on 2026-01-14 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_alter_assessmentmodule_options_assessment_paper_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessment',
            options={'ordering': ['-start_date', 'name'], 'permissions': [('view_all_scores', '可以查看所有人的考核成绩')], 'verbose_name': '考核', 'verbose_name_plural': '考核'},
        ),
    ]
