# Generated by Django 6.0.6 on 2026-09-05 01:52

import assessments.models
import core.uploads
import django.core.validators
import uuid
from django.conf import settings
from django.db import migrations, models


def retire_marking_sheets(apps, schema_editor):
    documents = apps.get_model("assessments", "AssessmentDocument")
    documents.objects.using(schema_editor.connection.alias).filter(document_type="marking_scheme").update(
        document_type="attachment"
    )


class Migration(migrations.Migration):
    dependencies = [
        ('assessments', '0007_finalize_assessment_type'),
        ('scoring', '0003_alter_scoringparserconfig_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='assessmentdocument',
            name='uniq_assessment_document_module_hash',
        ),
        migrations.RemoveConstraint(
            model_name='assessmentdocument',
            name='uniq_assessment_document_general_hash',
        ),
        migrations.RunPython(retire_marking_sheets, migrations.RunPython.noop),
        migrations.AddField(
            model_name='assessmentdocument',
            name='document_date',
            field=models.DateField(blank=True, null=True, verbose_name='资料日期'),
        ),
        migrations.AddField(
            model_name='assessmentdocument',
            name='normalized_filename',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='规范文件名'),
        ),
        migrations.AddField(
            model_name='assessmentdocument',
            name='numeric_version',
            field=models.DecimalField(
                blank=True, decimal_places=1, editable=False, max_digits=9, null=True, verbose_name='数值版本'
            ),
        ),
        migrations.AddField(
            model_name='assessmentdocument',
            name='storage_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='code',
            field=models.CharField(
                help_text='1–20 位英文字母或数字。',
                max_length=80,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        '\\A[A-Za-z0-9]{1,20}\\Z', '评测代码须为 1–20 位英文字母或数字。'
                    )
                ],
                verbose_name='代码',
            ),
        ),
        migrations.AlterField(
            model_name='assessmentdocument',
            name='document_type',
            field=models.CharField(
                choices=[
                    ('test_project', '试题'),
                    ('technical_description', '技术文件'),
                    ('marking_standard', '评分标准'),
                    ('scoring_script', '评分脚本'),
                    ('result_file', '成绩或结果文件'),
                    ('attachment', '其他附件'),
                ],
                max_length=30,
                verbose_name='资料类型',
            ),
        ),
        migrations.AlterField(
            model_name='assessmentdocument',
            name='file',
            field=models.FileField(
                help_text='上传文件，支持 pdf, doc, docx, xls, xlsx, ppt, pptx, zip, gz, bz2, rar, 7z, json, txt, csv, png, jpg, jpeg，大小不超过 100MB',
                max_length=300,
                storage=core.uploads.PrivateMediaStorage('assessments'),
                upload_to=assessments.models.assessment_document_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=(
                            'pdf',
                            'doc',
                            'docx',
                            'xls',
                            'xlsx',
                            'ppt',
                            'pptx',
                            'zip',
                            'gz',
                            'bz2',
                            'rar',
                            '7z',
                            'json',
                            'txt',
                            'csv',
                            'png',
                            'jpg',
                            'jpeg',
                        ),
                        message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, ppt, pptx, zip, gz, bz2, rar, 7z, json, txt, csv, png, jpg, jpeg',
                    ),
                    core.uploads.UploadSizeValidator(100),
                    core.uploads.UploadSignatureValidator(),
                ],
                verbose_name='文件',
            ),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='code',
            field=models.CharField(
                help_text='1–8 位英文字母或数字；GEN 为公共资料保留值。',
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        '\\A(?![Gg][Ee][Nn]\\Z)[A-Za-z0-9]{1,8}\\Z',
                        '模块代码须为 1–8 位英文字母或数字，不能使用保留值 GEN。',
                    )
                ],
                verbose_name='模块代码',
            ),
        ),
        migrations.AddConstraint(
            model_name='assessmentdocument',
            constraint=models.UniqueConstraint(
                condition=models.Q(('module__isnull', False)),
                fields=('assessment', 'module', 'document_type', 'numeric_version'),
                name='uniq_assessment_document_module_version',
            ),
        ),
        migrations.AddConstraint(
            model_name='assessmentdocument',
            constraint=models.UniqueConstraint(
                condition=models.Q(('module__isnull', True)),
                fields=('assessment', 'document_type', 'numeric_version'),
                name='uniq_assessment_document_general_version',
            ),
        ),
    ]
