# Generated by Django 6.0.6 on 2026-09-05 04:13

import assessments.models
import assessments.storage
import core.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('assessments', '0008_remove_assessmentdocument_uniq_assessment_document_module_hash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentdocument',
            name='file',
            field=models.FileField(
                help_text='上传文件，支持 pdf, doc, docx, xls, xlsx, ppt, pptx, zip, gz, bz2, rar, 7z, json, txt, csv, png, jpg, jpeg，大小不超过 100MB。',
                max_length=300,
                storage=assessments.storage.AssessmentDocumentStorage(),
                upload_to=assessments.models.assessment_document_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=(
                            'pdf',
                            'doc',
                            'docx',
                            'xls',
                            'xlsx',
                            'ppt',
                            'pptx',
                            'zip',
                            'gz',
                            'bz2',
                            'rar',
                            '7z',
                            'json',
                            'txt',
                            'csv',
                            'png',
                            'jpg',
                            'jpeg',
                        ),
                        message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, ppt, pptx, zip, gz, bz2, rar, 7z, json, txt, csv, png, jpg, jpeg',
                    ),
                    core.uploads.UploadSizeValidator(100),
                    core.uploads.UploadSignatureValidator(),
                ],
                verbose_name='文件',
            ),
        ),
    ]
