# Generated by Django 6.0 on 2026-01-15 00:28

import assessments.models
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_alter_assessment_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='paper_file',
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='paper_file',
            field=models.FileField(blank=True, help_text='请上传文件，支持 xls, xlsx, csv, pdf, doc, docx, jpg, jpeg, png, zip, 7z, gz, bz2, rar，大小不超过 100MB', storage=django.core.files.storage.FileSystemStorage(location='D:\\04-01-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessments'), upload_to=assessments.models.assessment_paper_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar']), assessments.models.validate_file_size], verbose_name='试卷及评分文件'),
        ),
    ]
