# Generated by Django 6.0 on 2026-01-20 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_assessmentmodule_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='remarks',
            field=models.CharField(blank=True, max_length=200, verbose_name='备注'),
        ),
    ]
