# Generated by Django 6.0.1 on 2026-01-29 13:46

import assessments.models
import django.core.files.storage
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_alter_assessmentmodule_paper_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentmodule',
            name='paper_file',
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='question_file',
            field=models.FileField(blank=True, help_text='上传试题文件，支持 xls, xlsx, csv, pdf, doc, docx, jpg, jpeg, png, zip, 7z, gz, bz2, rar，大小不超过 100MB', storage=django.core.files.storage.FileSystemStorage(location='E:\\01-04-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessments'), upload_to=assessments.models.question_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar']), assessments.models.validate_file_size], verbose_name='试题文件'),
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='scoring_script_file',
            field=models.FileField(blank=True, help_text='上传评分脚本文件（非必须）', storage=django.core.files.storage.FileSystemStorage(location='E:\\01-04-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessments'), upload_to=assessments.models.scoring_script_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar']), assessments.models.validate_file_size], verbose_name='评分脚本文件'),
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='scoring_sheet_file',
            field=models.FileField(blank=True, help_text='上传评分表文件（非必须）', storage=django.core.files.storage.FileSystemStorage(location='E:\\01-04-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessments'), upload_to=assessments.models.scoring_sheet_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar']), assessments.models.validate_file_size], verbose_name='评分表文件'),
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='scoring_standard_file',
            field=models.FileField(blank=True, help_text='上传评分标准文件', storage=django.core.files.storage.FileSystemStorage(location='E:\\01-04-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessments'), upload_to=assessments.models.scoring_standard_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar']), assessments.models.validate_file_size], verbose_name='评分标准文件'),
        ),
        migrations.CreateModel(
            name='AssessmentAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='上传附件文件', storage=django.core.files.storage.FileSystemStorage(location='E:\\01-04-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessments'), upload_to=assessments.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar']), assessments.models.validate_file_size], verbose_name='附件文件')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='文件说明')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('assessment_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='assessments.assessmentmodule', verbose_name='考核模块')),
            ],
            options={
                'verbose_name': '考核附件',
                'verbose_name_plural': '考核附件',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
