# Generated by Django 6.0.1 on 2026-01-30 07:01

import assessments.models
import core.utils.validators
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_remove_assessmentmodule_paper_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assessmentmodule',
            options={'verbose_name': '考核模块', 'verbose_name_plural': '考核模块'},
        ),
        migrations.AlterField(
            model_name='assessmentattachment',
            name='file',
            field=models.FileField(help_text='上传附件文件', storage=django.core.files.storage.FileSystemStorage(location='D:\\04-01-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessments'), upload_to=assessments.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar']), core.utils.validators.validate_file_size], verbose_name='附件文件'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='question_file',
            field=models.FileField(blank=True, help_text='上传试题文件，支持 xls, xlsx, csv, pdf, doc, docx, jpg, jpeg, png, zip, 7z, gz, bz2, rar，大小不超过 100MB', storage=django.core.files.storage.FileSystemStorage(location='D:\\04-01-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessments'), upload_to=assessments.models.question_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar']), core.utils.validators.validate_file_size], verbose_name='试题文件'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='scoring_script_file',
            field=models.FileField(blank=True, help_text='上传评分脚本文件（非必须）', storage=django.core.files.storage.FileSystemStorage(location='D:\\04-01-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessments'), upload_to=assessments.models.scoring_script_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar']), core.utils.validators.validate_file_size], verbose_name='评分脚本文件'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='scoring_sheet_file',
            field=models.FileField(blank=True, help_text='上传评分表文件（非必须）', storage=django.core.files.storage.FileSystemStorage(location='D:\\04-01-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessments'), upload_to=assessments.models.scoring_sheet_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar']), core.utils.validators.validate_file_size], verbose_name='评分表文件'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='scoring_standard_file',
            field=models.FileField(blank=True, help_text='上传评分标准文件', storage=django.core.files.storage.FileSystemStorage(location='D:\\04-01-Codes\\GitHub\\hdaojin\\tms\\media-private\\assessments'), upload_to=assessments.models.scoring_standard_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar']), core.utils.validators.validate_file_size], verbose_name='评分标准文件'),
        ),
    ]
