# Generated by Django 6.0.3 on 2026-04-09 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0020_alter_assessmentmodule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmodule',
            name='responsible_coach',
            field=models.ForeignKey(blank=True, help_text='只有该教练可以上传资料和录入成绩', limit_choices_to={'groups__name': '教练'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_assessment_modules', to=settings.AUTH_USER_MODEL, verbose_name='负责教练'),
        ),
    ]
