# Generated by Django 6.0.3 on 2026-04-16 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0022_assessmentmodule_is_locked_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentmodule',
            name='is_material_locked',
            field=models.BooleanField(default=False, help_text='锁定后资料不可修改', verbose_name='资料已锁定'),
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='material_locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='资料锁定时间'),
        ),
        migrations.AddField(
            model_name='assessmentmodule',
            name='material_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_locked_assessment_modules', to=settings.AUTH_USER_MODEL, verbose_name='资料锁定人'),
        ),
    ]