# Generated by Django 6.0.4 on 2026-05-16 07:47

import assessments.models
import core.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0023_assessmentmodule_material_lock_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentattachment',
            name='file',
            field=models.FileField(help_text='上传附件文件，支持 pdf, doc, docx, xls, xlsx, csv, txt, md, jpg, jpeg, png, gif, zip, 7z, gz, bz2, rar, tar，大小不超过 100MB', storage=core.uploads.PrivateMediaStorage('assessments'), upload_to=assessments.models.attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv', 'txt', 'md', 'jpg', 'jpeg', 'png', 'gif', 'zip', '7z', 'gz', 'bz2', 'rar', 'tar'), message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, csv, txt, md, jpg, jpeg, png, gif, zip, 7z, gz, bz2, rar, tar'), core.uploads.UploadSizeValidator(100)], verbose_name='附件文件'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='question_file',
            field=models.FileField(blank=True, help_text='上传试题文件，支持 pdf, doc, docx，大小不超过 50MB', storage=core.uploads.PrivateMediaStorage('assessments'), upload_to=assessments.models.question_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx'), message='仅支持以下格式的文件：pdf, doc, docx'), core.uploads.UploadSizeValidator(50)], verbose_name='试题文件'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='scoring_script_file',
            field=models.FileField(blank=True, help_text='上传评分脚本文件，支持 py, sh, bat, exe, ps1, yml, yaml，大小不超过 50MB', storage=core.uploads.PrivateMediaStorage('assessments'), upload_to=assessments.models.scoring_script_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('py', 'sh', 'bat', 'exe', 'ps1', 'yml', 'yaml'), message='仅支持以下格式的文件：py, sh, bat, exe, ps1, yml, yaml'), core.uploads.UploadSizeValidator(50)], verbose_name='评分脚本文件'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='scoring_sheet_file',
            field=models.FileField(blank=True, help_text='上传评分表文件，支持 pdf, doc, docx, xls, xlsx, csv，大小不超过 50MB', storage=core.uploads.PrivateMediaStorage('assessments'), upload_to=assessments.models.scoring_sheet_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv'), message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, csv'), core.uploads.UploadSizeValidator(50)], verbose_name='评分表文件'),
        ),
        migrations.AlterField(
            model_name='assessmentmodule',
            name='scoring_standard_file',
            field=models.FileField(blank=True, help_text='上传评分标准文件，支持 pdf, doc, docx, xls, xlsx, csv，大小不超过 50MB', storage=core.uploads.PrivateMediaStorage('assessments'), upload_to=assessments.models.scoring_standard_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'xls', 'xlsx', 'csv'), message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, csv'), core.uploads.UploadSizeValidator(50)], verbose_name='评分标准文件'),
        ),
    ]
