# Generated by Django 6.0.6 on 2026-08-14 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0002_retire_legacy_standard_stack'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='default_registration_group',
            field=models.ForeignKey(blank=True, help_text='新注册用户自动加入此组；留空时不授予任何默认业务权限。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='auth.group', verbose_name='新用户默认用户组'),
        ),
        migrations.AddConstraint(
            model_name='siteconfig',
            constraint=models.CheckConstraint(condition=models.Q(('pk', 1)), name='core_siteconfig_singleton_pk'),
        ),
    ]
