# Generated by Django 5.1.6 on 2025-03-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traininglog',
            name='filename',
            field=models.CharField(default=1, max_length=200, verbose_name='文件名'),
            preserve_default=False,
        ),
    ]
