# Generated by Django 5.1.6 on 2025-03-27 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglogs', '0003_alter_traininglog_training_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='training_date',
            field=models.DateField(default=datetime.date.today, help_text='*特别注意：请填写日志对应的实际训练日期，而非上传日期', verbose_name='训练日期'),
        ),
    ]
