# Generated by Django 6.0.5 on 2026-05-22 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_competitiontype_options_and_more'),
        ('trainingcycles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainingcycle',
            name='module_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_cycles', to='curriculum.standardmoduleset', verbose_name='标准模块版本'),
        ),
        migrations.AlterField(
            model_name='trainingcycle',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_cycles', to='curriculum.project', verbose_name='标准赛项'),
        ),
    ]
