# Generated by Django 6.0.5 on 2026-05-22 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_alter_assessment_training_cycle'),
        ('trainingcycles', '0002_alter_trainingcycle_module_set_and_more'),
        ('traininglogs', '0003_alter_traininglog_training_cycle'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='TrainingCycle',
                ),
            ],
            database_operations=[],
        ),
    ]
