# Generated by Django 6.0 on 2025-12-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100, verbose_name='站点名称')),
                ('site_short_name', models.CharField(blank=True, help_text='用于简短显示，如浏览器标签页标题', max_length=50, verbose_name='站点简称')),
                ('site_description', models.TextField(blank=True, verbose_name='站点描述')),
                ('site_keywords', models.CharField(blank=True, help_text='用于SEO的关键词，逗号分隔', max_length=255, verbose_name='站点关键词')),
                ('site_author', models.CharField(blank=True, max_length=100, verbose_name='站点作者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
    ]
