# Generated by Django 6.0 on 2025-12-08 05:24

from django.db import migrations


def create_site_config(apps, schema_editor):
    SiteConfig = apps.get_model('common', 'SiteConfig')
    if SiteConfig.objects.exists():
        return  # 已存在配置，跳过初始化
    
    SiteConfig.objects.create(
        id = 1,
        site_name="Training Management System",
        site_short_name="TMS",
        site_description="Change me in admin panel",
        site_keywords="Change, me, in, admin, panel",
        site_author="hdaojin"
    )


def reverse_func(apps, schema_editor):
    SiteConfig = apps.get_model('common', 'SiteConfig')
    try:
        siteconfig = SiteConfig.objects.get(id=1)
        siteconfig.delete()
    except SiteConfig.DoesNotExist:
        pass

class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_site_config, reverse_func),
    ]
