# Generated by Django 6.0 on 2025-12-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_siteconfig_init_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='site_copyright',
            field=models.CharField(blank=True, help_text='如: © 2026 My Company', max_length=255, verbose_name='站点版权信息'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_domain',
            field=models.CharField(blank=True, help_text='如: www.example.com', max_length=100, verbose_name='站点域名'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_icp_beian',
            field=models.CharField(blank=True, help_text='如: 粤ICP备12345678号-1', max_length=50, verbose_name='ICP备案号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_icp_beian_link',
            field=models.URLField(blank=True, help_text='如: https://beian.miit.gov.cn/', verbose_name='ICP备案链接'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_ism_beian',
            field=models.CharField(blank=True, help_text='如: 粤公网安备440200001234', max_length=50, verbose_name='公安联网备案号'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='site_ism_beian_link',
            field=models.URLField(blank=True, help_text='如: https://beian.mps.gov.cn/#/query/webSearch?code=440200001234', verbose_name='公安联网备案链接'),
        ),
    ]
