# Generated by Django 6.0 on 2025-12-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_siteconfig_site_copyright_siteconfig_site_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='site_author_link',
            field=models.URLField(blank=True, help_text='如: https://example.com/about', verbose_name='站点作者网址链接'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_copyright',
            field=models.CharField(blank=True, help_text='如: TMS 版权所有', max_length=255, verbose_name='站点版权信息'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_keywords',
            field=models.CharField(blank=True, help_text='用于SEO的关键词，用逗号分隔', max_length=255, verbose_name='站点关键词'),
        ),
    ]
