# Generated by Django 6.0.6 on 2026-08-14 11:26

import core.uploads
import django.core.validators
import django.db.models.deletion
import feedback.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug'), ('feature', '功能需求'), ('suggestion', '意见建议'), ('complaint', '投诉')], db_index=True, max_length=20, verbose_name='反馈类型')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('content', models.TextField(verbose_name='详细描述')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='匿名提交')),
                ('is_private', models.BooleanField(db_index=True, default=False, verbose_name='仅工作人员可见')),
                ('status', models.CharField(choices=[('open', '待处理'), ('in_progress', '处理中'), ('resolved', '已解决'), ('closed', '已关闭')], db_index=True, default='open', max_length=20, verbose_name='状态')),
                ('resolution', models.TextField(blank=True, verbose_name='处理结果')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='更新时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_created', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks_resolved', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'verbose_name': '意见反馈',
                'verbose_name_plural': '意见反馈',
                'ordering': ['-updated_at', '-pk'],
                'permissions': [('manage_feedback', '管理意见反馈'), ('view_private_feedback', '查看私密反馈'), ('view_anonymous_identity', '查看匿名反馈人身份')],
            },
        ),
        migrations.CreateModel(
            name='FeedbackReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_replies', to=settings.AUTH_USER_MODEL, verbose_name='回复人')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='feedback.feedback', verbose_name='反馈')),
            ],
            options={
                'verbose_name': '反馈回复',
                'verbose_name_plural': '反馈回复',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=core.uploads.PrivateMediaStorage('feedback'), upload_to=feedback.models.feedback_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'jpeg', 'png', 'webp', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'md', 'csv', 'json', 'yaml', 'yml', 'xml', 'conf', 'cfg', 'ini', 'log', 'zip'), message='仅支持以下格式的文件：jpg, jpeg, png, webp, pdf, doc, docx, xls, xlsx, ppt, pptx, txt, md, csv, json, yaml, yml, xml, conf, cfg, ini, log, zip'), core.uploads.UploadSizeValidator(20)], verbose_name='附件文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('file_size', models.PositiveBigIntegerField(verbose_name='文件大小')),
                ('content_type', models.CharField(blank=True, max_length=255, verbose_name='MIME 类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedback', verbose_name='反馈')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback_attachments_uploaded', to=settings.AUTH_USER_MODEL, verbose_name='上传人')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='feedback.feedbackreply', verbose_name='回复')),
            ],
            options={
                'verbose_name': '反馈附件',
                'verbose_name_plural': '反馈附件',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['category', 'status'], name='feedback_fe_categor_ca3927_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['is_private', 'status'], name='feedback_fe_is_priv_5cf6a8_idx'),
        ),
    ]
