# Generated by Django 6.0.6 on 2026-08-17 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='category',
            field=models.CharField(choices=[('bug', 'Bug反馈'), ('feature', '功能需求'), ('suggestion', '意见建议'), ('complaint', '我要投诉')], db_index=True, max_length=20, verbose_name='反馈类型'),
        ),
    ]
