# Generated by Django 6.0 on 2025-12-10 07:46

from django.db import migrations


class Migration(migrations.Migration):

    replaces = [('samba', '0001_initial'), ('samba', '0002_delete_sambagroupmap')]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
    ]
