# Generated by Django 5.2.7 on 2025-11-04 08:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SambaGroupMap',
            fields=[
                ('group', models.OneToOneField(help_text='关联的 Django 用户组', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='samba_group_map', serialize=False, to='auth.group')),
                ('unix_name', models.CharField(blank=True, help_text='对应的 Samba 组名（Unix 系统组名）, 必须是Uninx/Linux系统可用的 ASCII 组名（如 smbusers、netops、dev_team）。', max_length=30, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='uninx_name 必须以小写字母开头，后续字符可以是小写字母、数字、下划线或连字符，且长度不超过30个字符。', regex='^[a-z][a-z0-9_-]{1,30}$')], verbose_name='Unix 组名')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '账号所属组与Samba组的映射',
                'verbose_name_plural': '账号所属组与Samba组的映射',
            },
        ),
    ]
