# Generated by Django 6.0 on 2025-12-10 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samba', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SambaGroupMap',
        ),
    ]
