# Generated by Django 6.0.4 on 2026-05-20 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('samba', '0001_squashed_0002_delete_sambagroupmap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SambaOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('action', models.CharField(choices=[('enable', '开通账户'), ('change_password', '修改密码'), ('disable', '停用账户')], max_length=32, verbose_name='操作')),
                ('status', models.CharField(choices=[('queued', '待处理'), ('running', '处理中'), ('succeeded', '已完成'), ('failed', '失败')], default='queued', max_length=16, verbose_name='状态')),
                ('payload_encrypted', models.TextField(blank=True, verbose_name='加密载荷')),
                ('result_summary', models.CharField(blank=True, max_length=255, verbose_name='结果摘要')),
                ('detail', models.TextField(blank=True, verbose_name='详细日志')),
                ('last_error', models.TextField(blank=True, verbose_name='错误信息')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samba_operations', to=settings.AUTH_USER_MODEL, verbose_name='目标用户')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': 'Samba 操作',
                'verbose_name_plural': 'Samba 操作',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
