# Generated by Django 5.2 on 2025-04-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='is_homepage',
        ),
        migrations.AddField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('default', '默认'), ('no_sidebar', '无侧边栏'), ('no_header_sidebar', '无头部和侧边栏')], default='default', max_length=50, verbose_name='页面模板'),
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(help_text="用于URL的唯一标识符, 例如：about。'首页'必须为'index'", max_length=255, unique=True, verbose_name='别名'),
        ),
    ]
