# Generated by Django 5.2 on 2025-05-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_page_is_homepage_page_template_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('default', '默认'), ('no_sidebar', '无侧边栏'), ('no_header_sidebar', '无头部和侧边栏'), ('no_header_sidebar_footer', '无头部、侧边栏和底部')], default='default', max_length=50, verbose_name='页面模板'),
        ),
    ]
