# Generated by Django 5.2.5 on 2025-08-30 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_page_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(choices=[('default', '默认'), ('no_sidebar', '无侧边栏'), ('no_header_sidebar', '无头部、无侧边栏'), ('no_header_sidebar_footer', '无头部、无侧边栏、无底部')], default='default', help_text="选择页面的布局模板, 例如：是否显示侧边栏、头部和底部等。'首页'必须选择'无头部、无侧边栏、无底部'", max_length=50, verbose_name='页面模板'),
        ),
    ]
