# Generated by Django 5.2 on 2025-04-18 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_invitationcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvitationCode',
        ),
    ]
