# Generated by Django 5.2 on 2025-05-15 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_invitationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Submission_training_log',
            field=models.BooleanField(default=True, verbose_name='是否提交训练日志'),
        ),
    ]
