# Generated by Django 5.2 on 2025-05-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_submission_training_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Submission_training_log',
            new_name='submission_training_log',
        ),
    ]
