# Generated by Django 5.2.5 on 2025-08-30 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_submission_training_log_userprofile_submission_training_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='submission_training_log',
        ),
    ]
