# Generated by Django 5.2.5 on 2025-09-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userprofile_submission_training_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='电话号码'),
            preserve_default=False,
        ),
    ]
