# Generated by Django 5.2.7 on 2025-11-05 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='家庭住址'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(max_length=100, null=True, verbose_name='紧急联系人'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(max_length=20, null=True, verbose_name='紧急联系人电话'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emergency_contact_relation',
            field=models.CharField(max_length=50, null=True, verbose_name='紧急联系人关系'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='入读精英班日期'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='leave_date',
            field=models.DateField(blank=True, null=True, verbose_name='离开精英班日期'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name_pronunciation',
            field=models.CharField(max_length=100, null=True, verbose_name='姓名全拼'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='original_class',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='原班级'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='original_headteacher',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='原班主任'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='original_headteacher_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='原班主任电话'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='school_dormitory',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='学校宿舍'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=20, null=True, verbose_name='电话号码'),
        ),
    ]
