# Generated by Django 5.2.7 on 2025-11-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_address_userprofile_emergency_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='locked',
            field=models.BooleanField(default=False, editable=False, help_text='锁定后用户无法修改个人资料。', verbose_name='信息锁定'),
        ),
    ]
