# Generated by Django 5.2.7 on 2025-11-06 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_locked'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='学号'),
        ),
    ]
