# Generated by Django 5.2.7 on 2025-11-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='紧急联系人'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='紧急联系人电话'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='紧急联系人关系'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='locked',
            field=models.BooleanField(default=False, help_text='锁定后用户无法修改个人资料。', verbose_name='信息锁定'),
        ),
    ]
