# Generated by Django 6.0 on 2025-12-10 07:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_userprofile_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.SlugField(blank=True, help_text='用于脚本或系统集成的组名英文标识，必须以字母开头, 后续字符可以是字母、数字或下划线, 且长度不超过30个字符, 如: coach。', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='codename 必须以字母开头, 后续字符可以是字母、数字或下划线, 且长度不超过30个字符。', regex='^[a-zA-Z][a-zA-Z0-9_]{1,30}$')], verbose_name='英文标识')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='auth.group')),
            ],
            options={
                'verbose_name': '用户组信息',
                'verbose_name_plural': '用户组信息',
            },
        ),
    ]
