# Generated by Django 6.0 on 2025-12-19 03:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_groupprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupprofile',
            name='codename',
            field=models.SlugField(blank=True, help_text='用于脚本或系统集成的组codename, 必须以字母开头, 后续字符可以是字母、数字或下划线, 且长度不超过30个字符, 如: coach。', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(message='codename 必须以字母开头, 后续字符可以是字母、数字或下划线, 且长度不超过30个字符。', regex='^[a-zA-Z][a-zA-Z0-9_]{1,30}$')], verbose_name='英文标识'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女'), ('S', '保密')], default='S', max_length=1, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name_pronunciation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='姓名全拼'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='电话号码'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='学号'),
        ),
    ]
