# Generated by Django 6.0 on 2026-01-24 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_groupprofile_codename_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('view_all_profiles', '能查看所有人资料')], 'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
