# Generated by Django 6.0.4 on 2026-05-20 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_userprofile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='selected_permission_bundles',
            field=models.JSONField(blank=True, default=list, help_text='后台授权时勾选的业务权限包编码列表。', verbose_name='业务权限包'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selected_permission_bundles',
            field=models.JSONField(blank=True, default=list, help_text='后台授权时勾选的业务权限包编码列表。', verbose_name='业务权限包'),
        ),
    ]
