# Generated by Django 6.0.6 on 2026-08-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_groupprofile_selected_permission_bundles_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupprofile',
            name='explicit_permissions',
            field=models.ManyToManyField(blank=True, help_text='不属于业务权限包、但需要直接授予当前用户组的 Django 权限。', related_name='+', to='auth.permission', verbose_name='额外原生权限'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='explicit_permissions',
            field=models.ManyToManyField(blank=True, help_text='不属于业务权限包、但需要直接授予当前用户的 Django 权限。', related_name='+', to='auth.permission', verbose_name='额外原生权限'),
        ),
    ]
