# Generated by Django 5.2 on 2025-08-20 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='会议名称')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='*特别注意：请填写会议的实际日期, 而非上传日期', verbose_name='会议日期')),
                ('upload', models.FileField(help_text='支持pdf格式, 文件大小不超过10MB', upload_to='meetings/%Y', verbose_name='会议记录文件')),
                ('filename', models.CharField(max_length=200, verbose_name='文件名')),
            ],
        ),
    ]
