# Generated by Django 5.2 on 2025-08-20 09:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting',
            options={'ordering': ('-date',), 'verbose_name': '会议记录', 'verbose_name_plural': '会议记录'},
        ),
        migrations.AddField(
            model_name='meeting',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='上传时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='meetings', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
    ]
