# Generated by Django 6.0.1 on 2026-01-29 05:41

import core.utils.validators
import django.utils.timezone
import meetings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_merge_20250904_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='特别注意：请填写会议的实际日期, 而非上传日期', validators=[core.utils.validators.validate_date_not_future], verbose_name='会议日期'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='file',
            field=models.FileField(help_text='支持 PDF 格式, 文件大小不超过 100MB', upload_to=meetings.models.meeting_file_upload_to, validators=[meetings.models.meeting_file_validator], verbose_name='会议记录文件'),
        ),
    ]
