# Generated by Django 6.0.4 on 2026-05-16 07:47

import core.uploads
import django.core.validators
import meetings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_alter_meeting_date_alter_meeting_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='file',
            field=models.FileField(help_text='上传会议记录文件，支持 pdf，大小不超过 100MB', upload_to=meetings.models.meeting_file_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf',), message='仅支持以下格式的文件：pdf'), core.uploads.UploadSizeValidator(100)], verbose_name='会议记录文件'),
        ),
    ]
