# Generated by Django 5.1.6 on 2025-03-26 00:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0008_alter_exampoint_difficulty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=100, verbose_name='训练任务')),
                ('training_date', models.DateField(verbose_name='训练日期')),
                ('upload', models.FileField(upload_to='training_logs/%Y/%m/', verbose_name='上传训练日志')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='skills.module', verbose_name='模块')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '训练日志',
                'verbose_name_plural': '训练日志',
                'ordering': ('-training_date',),
            },
        ),
    ]
