# Generated by Django 5.1.6 on 2025-03-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_traininglog_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='training_date',
            field=models.DateField(help_text='*特别注意：请填写日志对应的实际训练日期，而非上传日期', verbose_name='训练日期'),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='upload',
            field=models.FileField(help_text='支持doc、docx、pdf格式, 文件大小不超过10MB', upload_to='training_logs/%Y/%m', verbose_name='上传训练日志'),
        ),
    ]
