# Generated by Django 6.0.6 on 2026-08-12 03:38

import core.uploads
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import worldskills_forum.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '论坛分类',
                'verbose_name_plural': '论坛分类',
                'ordering': ['sort_order', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ForumTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='标识')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '论坛标签',
                'verbose_name_plural': '论坛标签',
                'ordering': ['name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=200, verbose_name='原作者')),
                ('source_role', models.CharField(choices=[('worldskills_official', 'WorldSkills Official'), ('chief_expert', 'Chief Expert'), ('deputy_chief_expert', 'Deputy Chief Expert'), ('expert', 'Expert'), ('organizer', 'Competition Organizer'), ('other', '其他')], max_length=40, verbose_name='来源身份')),
                ('source_role_detail', models.CharField(blank=True, max_length=200, verbose_name='其他身份说明')),
                ('posted_at', models.DateTimeField(verbose_name='论坛原始发布时间')),
                ('source_url', models.URLField(blank=True, max_length=1000, validators=[worldskills_forum.models.http_url_validator], verbose_name='原帖链接')),
                ('source_post_id', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='论坛 Post ID')),
                ('post_type', models.CharField(choices=[('discussion', '专家讨论'), ('official_reply', '官方回复'), ('official_notice', '官方通知'), ('rule_change', '规则变更'), ('important_reminder', '重要提醒')], db_index=True, max_length=30, verbose_name='信息类型')),
                ('importance', models.CharField(choices=[('normal', '普通'), ('important', '重要'), ('urgent', '紧急')], db_index=True, default='normal', max_length=20, verbose_name='重要程度')),
                ('original_content', models.TextField(verbose_name='英文原文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_posts_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '论坛帖子',
                'verbose_name_plural': '论坛帖子',
                'ordering': ['posted_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ForumPostAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('image', '图片'), ('file', '附件')], default='file', max_length=10, verbose_name='类型')),
                ('file', models.FileField(blank=True, storage=core.uploads.PrivateMediaStorage('worldskills_forum'), upload_to=worldskills_forum.models.forum_attachment_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'md', 'txt', 'csv', 'json', 'yaml', 'yml', 'conf', 'log', 'jpg', 'jpeg', 'png', 'gif', 'webp', 'zip', 'rar', '7z', 'tar', 'gz', 'bz2'), message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, ppt, pptx, md, txt, csv, json, yaml, yml, conf, log, jpg, jpeg, png, gif, webp, zip, rar, 7z, tar, gz, bz2'), core.uploads.UploadSizeValidator(50)], verbose_name='本地归档文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('source_url', models.URLField(blank=True, max_length=1000, validators=[worldskills_forum.models.http_url_validator], verbose_name='论坛原附件链接')),
                ('caption_zh', models.CharField(blank=True, max_length=500, verbose_name='中文说明')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='文件大小')),
                ('content_type', models.CharField(blank=True, max_length=255, verbose_name='MIME 类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_attachments_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='worldskills_forum.forumpost', verbose_name='帖子')),
            ],
            options={
                'verbose_name': '论坛附件',
                'verbose_name_plural': '论坛附件',
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ForumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition_year', models.PositiveSmallIntegerField(db_index=True, verbose_name='世赛年份')),
                ('translated_title', models.CharField(max_length=300, verbose_name='中文主题')),
                ('original_title', models.CharField(max_length=500, verbose_name='英文主题')),
                ('source_url', models.URLField(max_length=1000, validators=[worldskills_forum.models.http_url_validator], verbose_name='论坛主题链接')),
                ('source_topic_id', models.CharField(blank=True, max_length=120, verbose_name='论坛 Topic ID')),
                ('summary', models.TextField(blank=True, verbose_name='中文摘要')),
                ('module', models.CharField(choices=[('general', '综合'), ('A', 'Module A'), ('B', 'Module B'), ('C', 'Module C'), ('D', 'Module D'), ('other', '其他')], db_index=True, default='general', max_length=20, verbose_name='Module')),
                ('status', models.CharField(choices=[('active', '持续讨论'), ('confirmed', '已确认'), ('closed', '已结束'), ('archived', '已归档')], db_index=True, default='active', max_length=20, verbose_name='状态')),
                ('importance', models.CharField(choices=[('normal', '普通'), ('important', '重要'), ('urgent', '紧急')], db_index=True, default='normal', max_length=20, verbose_name='重要程度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='worldskills_forum.forumcategory', verbose_name='分类')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_topics_created', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('tags', models.ManyToManyField(blank=True, related_name='topics', to='worldskills_forum.forumtag', verbose_name='标签')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_topics_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '论坛主题',
                'verbose_name_plural': '论坛主题',
                'ordering': ['-competition_year', '-updated_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='forumpost',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='worldskills_forum.forumtopic', verbose_name='主题'),
        ),
        migrations.CreateModel(
            name='ForumTopicReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_viewed_at', models.DateTimeField(verbose_name='最后查看时间')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='worldskills_forum.forumtopic', verbose_name='主题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_topic_read_states', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '论坛主题阅读状态',
                'verbose_name_plural': '论坛主题阅读状态',
            },
        ),
        migrations.CreateModel(
            name='ForumTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_content', models.TextField(verbose_name='中文翻译')),
                ('published_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='TMS 发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='worldskills_forum.forumpost', verbose_name='帖子')),
                ('translated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_translations_published', to=settings.AUTH_USER_MODEL, verbose_name='翻译人')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_translations_updated', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '论坛翻译',
                'verbose_name_plural': '论坛翻译',
                'ordering': ['-published_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='forumtopic',
            index=models.Index(fields=['category'], name='worldskills_categor_6b93c1_idx'),
        ),
        migrations.AddIndex(
            model_name='forumpost',
            index=models.Index(fields=['topic', 'posted_at'], name='worldskills_topic_i_c4557c_idx'),
        ),
        migrations.AddConstraint(
            model_name='forumtopicreadstate',
            constraint=models.UniqueConstraint(fields=('user', 'topic'), name='unique_forum_topic_read_state'),
        ),
    ]
