# Generated by Django 6.0.6 on 2026-08-12 08:20

import django.db.models.deletion
from django.db import migrations, models


SOURCE_ROLES = [
    ("世界技能组织官方", "worldskills_official", True, False),
    ("首席专家", "chief_expert", False, False),
    ("副首席专家", "deputy_chief_expert", False, False),
    ("专家", "expert", False, False),
    ("竞赛组织方", "organizer", False, False),
    ("其他", "other", False, True),
]


def create_source_roles_and_migrate_posts(apps, schema_editor):
    role_model = apps.get_model("worldskills_forum", "ForumSourceRole")
    post_model = apps.get_model("worldskills_forum", "ForumPost")
    roles = {}
    for sort_order, (name, slug, is_official, allows_detail) in enumerate(SOURCE_ROLES):
        role, _created = role_model.objects.get_or_create(
            slug=slug,
            defaults={
                "name": name,
                "sort_order": sort_order,
                "is_official": is_official,
                "allows_detail": allows_detail,
            },
        )
        roles[slug] = role
    for post in post_model.objects.all().iterator():
        post.source_role_config = roles.get(post.source_role, roles["other"])
        post.save(update_fields=["source_role_config"])


def restore_source_role_codes(apps, schema_editor):
    post_model = apps.get_model("worldskills_forum", "ForumPost")
    for post in post_model.objects.select_related("source_role_config").all().iterator():
        post.source_role = post.source_role_config.slug
        post.save(update_fields=["source_role"])


class Migration(migrations.Migration):
    dependencies = [
        ('worldskills_forum', '0003_editable_forum_modules'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumSourceRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                (
                    'slug',
                    models.SlugField(allow_unicode=True, blank=True, max_length=120, unique=True, verbose_name='标识'),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('is_official', models.BooleanField(default=False, verbose_name='官方来源')),
                ('allows_detail', models.BooleanField(default=False, verbose_name='允许填写身份补充说明')),
            ],
            options={
                'verbose_name': '论坛来源身份',
                'verbose_name_plural': '论坛来源身份',
                'ordering': ['sort_order', 'name', 'pk'],
            },
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='source_role_detail',
            field=models.CharField(blank=True, max_length=200, verbose_name='身份补充说明'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='source_role_config',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='posts_pending_migration',
                to='worldskills_forum.forumsourcerole',
                verbose_name='来源身份',
            ),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='source_role',
            field=models.CharField(
                choices=[
                    ('worldskills_official', '世界技能组织官方'),
                    ('chief_expert', '首席专家'),
                    ('deputy_chief_expert', '副首席专家'),
                    ('expert', '专家'),
                    ('organizer', '竞赛组织方'),
                    ('other', '其他'),
                ],
                max_length=40,
                null=True,
                verbose_name='来源身份',
            ),
        ),
        migrations.RunPython(
            create_source_roles_and_migrate_posts,
            restore_source_role_codes,
        ),
        migrations.RemoveField(
            model_name='forumpost',
            name='source_role',
        ),
        migrations.RenameField(
            model_name='forumpost',
            old_name='source_role_config',
            new_name='source_role',
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='source_role',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='posts',
                to='worldskills_forum.forumsourcerole',
                verbose_name='来源身份',
            ),
        ),
    ]
