# Generated by Django 6.0.6 on 2026-08-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worldskills_forum', '0004_forumsourcerole_alter_forumpost_source_role_detail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='forumtopic',
            options={'ordering': ['-competition_year', '-updated_at', '-pk'], 'permissions': [('change_all_forum_content', '管理全部论坛内容')], 'verbose_name': '论坛主题', 'verbose_name_plural': '论坛主题'},
        ),
    ]
