# Generated by Django 6.0.6 on 2026-08-13 04:04

import worldskills_forum.models
from django.db import migrations, models
from django.db.models import Count


def validate_existing_forum_sources(apps, schema_editor):
    topic_model = apps.get_model("worldskills_forum", "ForumTopic")
    post_model = apps.get_model("worldskills_forum", "ForumPost")
    conflicts = []

    duplicate_topic_ids = (
        topic_model.objects.exclude(source_topic_id="")
        .values("source_topic_id")
        .annotate(row_count=Count("pk"))
        .filter(row_count__gt=1)
    )
    for row in duplicate_topic_ids:
        ids = list(
            topic_model.objects.filter(source_topic_id=row["source_topic_id"]).values_list("pk", flat=True)
        )
        conflicts.append(f"source_topic_id={row['source_topic_id']!r} 的 ForumTopic 主键重复：{ids}")

    duplicate_urls = (
        topic_model.objects.values("source_url")
        .annotate(row_count=Count("pk"))
        .filter(row_count__gt=1)
    )
    for row in duplicate_urls:
        ids = list(topic_model.objects.filter(source_url=row["source_url"]).values_list("pk", flat=True))
        conflicts.append(f"source_url={row['source_url']!r} 的 ForumTopic 主键重复：{ids}")

    duplicate_post_ids = (
        post_model.objects.exclude(source_post_id="")
        .values("topic_id", "source_post_id")
        .annotate(row_count=Count("pk"))
        .filter(row_count__gt=1)
    )
    for row in duplicate_post_ids:
        ids = list(
            post_model.objects.filter(
                topic_id=row["topic_id"],
                source_post_id=row["source_post_id"],
            ).values_list("pk", flat=True)
        )
        conflicts.append(
            "topic_id={topic_id}, source_post_id={source_post_id!r} 的 ForumPost 主键重复：{ids}".format(
                topic_id=row["topic_id"],
                source_post_id=row["source_post_id"],
                ids=ids,
            )
        )

    if conflicts:
        raise RuntimeError(
            "无法自动添加 WorldSkills Forum 来源唯一约束，请先人工处理以下重复数据：\n- "
            + "\n- ".join(conflicts)
        )


def normalize_empty_source_ids(apps, schema_editor):
    topic_model = apps.get_model("worldskills_forum", "ForumTopic")
    post_model = apps.get_model("worldskills_forum", "ForumPost")
    topic_model.objects.filter(source_topic_id="").update(source_topic_id=None)
    post_model.objects.filter(source_post_id="").update(source_post_id=None)


def restore_empty_source_ids(apps, schema_editor):
    topic_model = apps.get_model("worldskills_forum", "ForumTopic")
    post_model = apps.get_model("worldskills_forum", "ForumPost")
    topic_model.objects.filter(source_topic_id__isnull=True).update(source_topic_id="")
    post_model.objects.filter(source_post_id__isnull=True).update(source_post_id="")


class Migration(migrations.Migration):

    dependencies = [
        ('worldskills_forum', '0004_forumsourcerole_alter_forumpost_source_role_detail_and_more'),
    ]

    operations = [
        migrations.RunPython(validate_existing_forum_sources, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='forumpost',
            name='source_post_id',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True, verbose_name='论坛帖子 ID'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='source_topic_id',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='论坛主题 ID'),
        ),
        migrations.RunPython(normalize_empty_source_ids, restore_empty_source_ids),
        migrations.AlterField(
            model_name='forumtopic',
            name='source_topic_id',
            field=models.CharField(blank=True, max_length=120, null=True, unique=True, verbose_name='论坛主题 ID'),
        ),
        migrations.AlterField(
            model_name='forumtopic',
            name='source_url',
            field=models.URLField(max_length=1000, unique=True, validators=[worldskills_forum.models.http_url_validator], verbose_name='论坛主题链接'),
        ),
        migrations.AddConstraint(
            model_name='forumpost',
            constraint=models.UniqueConstraint(
                fields=('topic', 'source_post_id'),
                name='uniq_forumpost_topic_source_post_id',
            ),
        ),
    ]
