# Generated by Django 6.0.6 on 2026-06-15 14:46

import core.uploads
import django.core.validators
import django.db.models.deletion
import marking.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarkingAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='评分点编号')),
                ('aspect_type', models.CharField(choices=[('M', '测量'), ('J', '评价')], max_length=1, verbose_name='评分类型')),
                ('description', models.TextField(verbose_name='评分点')),
                ('command', models.TextField(blank=True, verbose_name='命令或操作')),
                ('requirement', models.TextField(blank=True, verbose_name='期望结果')),
                ('wsos_section', models.CharField(blank=True, max_length=50, verbose_name='WSOS 章节')),
                ('calculation_row', models.CharField(blank=True, max_length=100, verbose_name='计算行')),
                ('max_mark', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='分值')),
                ('source_row_number', models.PositiveIntegerField(verbose_name='来源行号')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '评分点',
                'verbose_name_plural': '评分点',
                'ordering': ['scheme', 'subcriterion__sort_order', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MarkingParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_identifier', models.CharField(blank=True, max_length=100, verbose_name='外部编号')),
                ('display_name', models.CharField(max_length=200, verbose_name='显示名称')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='所属单位')),
                ('member_name', models.CharField(blank=True, max_length=100, verbose_name='代表队')),
                ('snapshot', models.JSONField(blank=True, default=dict, verbose_name='参评对象快照')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '参评对象',
                'verbose_name_plural': '参评对象',
                'ordering': ['scheme', 'sort_order', 'display_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MarkingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_awarded', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='得分')),
                ('source', models.CharField(choices=[('cmp', 'CMP 导入'), ('imported', '文件导入'), ('manual', '人工录入')], default='imported', max_length=20, verbose_name='来源')),
                ('evidence', models.TextField(blank=True, verbose_name='证据摘要')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='原始结果')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='评分时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '评分结果',
                'verbose_name_plural': '评分结果',
                'ordering': ['participant', 'aspect__sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MarkingResultImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='上传 CMP 标准结果包，支持 json，大小不超过 20MB', storage=core.uploads.PrivateMediaStorage('marking'), upload_to=marking.models.result_package_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('json',), message='仅支持以下格式的文件：json'), core.uploads.UploadSizeValidator(20)], verbose_name='JSON 结果包')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('file_sha256', models.CharField(db_index=True, max_length=64, verbose_name='文件 SHA256')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='导入摘要')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
            ],
            options={
                'verbose_name': '结果包导入',
                'verbose_name_plural': '结果包导入',
                'ordering': ['-imported_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MarkingScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_object_id', models.PositiveBigIntegerField(verbose_name='绑定对象 ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('module_code', models.CharField(max_length=50, verbose_name='模块编号')),
                ('module_name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('total_mark', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='总分')),
                ('parser_version', models.CharField(max_length=30, verbose_name='解析器版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '评分方案',
                'verbose_name_plural': '评分方案',
                'ordering': ['-created_at', 'module_code', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MarkingSchemeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='上传新版单模块评分表，支持 xlsx，大小不超过 50MB', storage=core.uploads.PrivateMediaStorage('marking'), upload_to=marking.models.marking_scheme_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('xlsx',), message='仅支持以下格式的文件：xlsx'), core.uploads.UploadSizeValidator(50)], verbose_name='评分表文件')),
                ('original_filename', models.CharField(blank=True, max_length=255, verbose_name='原始文件名')),
                ('file_sha256', models.CharField(db_index=True, max_length=64, verbose_name='文件 SHA256')),
                ('status', models.CharField(choices=[('imported', '已导入'), ('failed', '导入失败')], default='imported', max_length=20, verbose_name='状态')),
                ('parser_version', models.CharField(max_length=30, verbose_name='解析器版本')),
                ('parse_summary', models.JSONField(blank=True, default=dict, verbose_name='解析摘要')),
                ('target_object_id', models.PositiveBigIntegerField(verbose_name='绑定对象 ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
            ],
            options={
                'verbose_name': '评分表导入',
                'verbose_name_plural': '评分表导入',
                'ordering': ['-uploaded_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MarkingSubCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='子评分项编号')),
                ('name', models.CharField(max_length=300, verbose_name='子评分项名称或描述')),
                ('day_of_marking', models.CharField(max_length=50, verbose_name='评分日')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '评分子项',
                'verbose_name_plural': '评分子项',
                'ordering': ['scheme', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='JudgementOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='分档值')),
                ('description', models.TextField(verbose_name='分档说明')),
                ('source_row_number', models.PositiveIntegerField(verbose_name='来源行号')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='显示顺序')),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgement_options', to='marking.markingaspect', verbose_name='评价评分点')),
            ],
            options={
                'verbose_name': '评价分档',
                'verbose_name_plural': '评价分档',
                'ordering': ['aspect', 'sort_order', 'score_value'],
            },
        ),
        migrations.CreateModel(
            name='MarkingAspectSkillNodeMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主技能')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='权重')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('aspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_node_mappings', to='marking.markingaspect', verbose_name='评分点')),
            ],
            options={
                'verbose_name': '评分点技能映射',
                'verbose_name_plural': '评分点技能映射',
                'ordering': ['aspect', '-is_primary', 'skill_node__sort_order', 'pk'],
            },
        ),
    ]
