# Generated by Django 6.0.6 on 2026-06-15 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competition_standards', '0001_initial'),
        ('competitions', '0004_competitiontrainingcycletarget'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('marking', '0001_initial'),
        ('skilltrees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='markingaspectskillnodemap',
            name='skill_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marking_aspect_mappings', to='skilltrees.skillnode', verbose_name='技能节点'),
        ),
        migrations.AddField(
            model_name='markingparticipant',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marking_participations', to='competitions.competitor', verbose_name='关联竞赛选手'),
        ),
        migrations.AddField(
            model_name='markingparticipant',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marking_participations', to=settings.AUTH_USER_MODEL, verbose_name='关联用户'),
        ),
        migrations.AddField(
            model_name='markingresult',
            name='aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='marking.markingaspect', verbose_name='评分点'),
        ),
        migrations.AddField(
            model_name='markingresult',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='marking.markingparticipant', verbose_name='参评对象'),
        ),
        migrations.AddField(
            model_name='markingresultimport',
            name='imported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marking_result_imports', to=settings.AUTH_USER_MODEL, verbose_name='导入者'),
        ),
        migrations.AddField(
            model_name='markingscheme',
            name='standard_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marking_schemes', to='competition_standards.standardmodule', verbose_name='标准模块'),
        ),
        migrations.AddField(
            model_name='markingscheme',
            name='target_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marking_schemes', to='contenttypes.contenttype', verbose_name='绑定对象类型'),
        ),
        migrations.AddField(
            model_name='markingresultimport',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='result_imports', to='marking.markingscheme', verbose_name='评分方案'),
        ),
        migrations.AddField(
            model_name='markingparticipant',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='marking.markingscheme', verbose_name='评分方案'),
        ),
        migrations.AddField(
            model_name='markingaspect',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aspects', to='marking.markingscheme', verbose_name='评分方案'),
        ),
        migrations.AddField(
            model_name='markingschemeimport',
            name='target_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='marking_scheme_imports', to='contenttypes.contenttype', verbose_name='绑定对象类型'),
        ),
        migrations.AddField(
            model_name='markingschemeimport',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marking_scheme_imports', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
        migrations.AddField(
            model_name='markingscheme',
            name='source_import',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scheme', to='marking.markingschemeimport', verbose_name='来源导入'),
        ),
        migrations.AddField(
            model_name='markingsubcriterion',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcriteria', to='marking.markingscheme', verbose_name='评分方案'),
        ),
        migrations.AddField(
            model_name='markingaspect',
            name='subcriterion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aspects', to='marking.markingsubcriterion', verbose_name='评分子项'),
        ),
        migrations.AddConstraint(
            model_name='judgementoption',
            constraint=models.UniqueConstraint(fields=('aspect', 'score_value'), name='uniq_judgement_option'),
        ),
        migrations.AddConstraint(
            model_name='markingaspectskillnodemap',
            constraint=models.UniqueConstraint(fields=('aspect', 'skill_node'), name='uniq_marking_aspect_skillnode'),
        ),
        migrations.AddConstraint(
            model_name='markingaspectskillnodemap',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('aspect',), name='uniq_primary_skillnode_per_aspect'),
        ),
        migrations.AddConstraint(
            model_name='markingresult',
            constraint=models.UniqueConstraint(fields=('participant', 'aspect'), name='uniq_marking_result'),
        ),
        migrations.AddConstraint(
            model_name='markingparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('scheme', 'user'), name='uniq_marking_participant_user'),
        ),
        migrations.AddConstraint(
            model_name='markingparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('competitor__isnull', False)), fields=('scheme', 'competitor'), name='uniq_marking_participant_competitor'),
        ),
        migrations.AddConstraint(
            model_name='markingparticipant',
            constraint=models.UniqueConstraint(condition=models.Q(('external_identifier', ''), _negated=True), fields=('scheme', 'external_identifier'), name='uniq_marking_participant_external'),
        ),
        migrations.AddConstraint(
            model_name='markingscheme',
            constraint=models.UniqueConstraint(fields=('target_content_type', 'target_object_id', 'module_code'), name='uniq_marking_scheme_target_module'),
        ),
        migrations.AddConstraint(
            model_name='markingsubcriterion',
            constraint=models.UniqueConstraint(fields=('scheme', 'code'), name='uniq_marking_subcriterion'),
        ),
        migrations.AddConstraint(
            model_name='markingaspect',
            constraint=models.UniqueConstraint(fields=('scheme', 'code'), name='uniq_marking_aspect_code'),
        ),
        migrations.AddConstraint(
            model_name='markingaspect',
            constraint=models.UniqueConstraint(fields=('scheme', 'source_row_number'), name='uniq_marking_aspect_source_row'),
        ),
    ]
