# Generated by Django 6.0 on 2025-12-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='与 NOTES_ROOT 下的目录名一一对应，例如 teaching-notes-Debian', max_length=100, unique=True, verbose_name='目录名')),
                ('title', models.CharField(max_length=200, verbose_name='显示名称')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('is_visible', models.BooleanField(default=True, verbose_name='是否在列表中显示')),
                ('order', models.PositiveIntegerField(default=0, help_text='列表页按此字段升序排序', verbose_name='排序值')),
                ('tags', models.CharField(blank=True, help_text='简单的标签字符串，用逗号分隔，例如 Linux,基础', max_length=200, verbose_name='标签')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='如果为空，表示所有登录用户可见；如果不为空，仅这些组的用户可见', to='auth.group', verbose_name='可见用户组')),
            ],
            options={
                'verbose_name': '笔记仓库',
                'verbose_name_plural': '笔记仓库',
                'ordering': ['order', 'slug'],
            },
        ),
    ]
