# Generated by Django 6.0.6 on 2026-06-17 10:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('archives', '0001_initial'),
        ('events', '0001_initial'),
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('version', models.CharField(blank=True, max_length=50, verbose_name='版本')),
                ('language', models.CharField(default='zh-hans', max_length=50, verbose_name='语言')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('structured', '已结构化'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_papers', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('event_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_papers', to='events.eventmodule', verbose_name='事件模块')),
                ('source_asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exam_papers', to='archives.archiveasset', verbose_name='试题文件')),
            ],
            options={
                'verbose_name': '试题',
                'verbose_name_plural': '试题',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ExamRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=80, verbose_name='要求编号')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('original_text', models.TextField(blank=True, verbose_name='原始文本')),
                ('normalized_text', models.TextField(blank=True, verbose_name='规范化文本')),
                ('requirement_type', models.CharField(choices=[('explicit', '显性要求'), ('implicit', '隐含考点'), ('constraint', '约束条件'), ('other', '其他')], default='explicit', max_length=20, verbose_name='要求类型')),
                ('source_location', models.CharField(blank=True, max_length=150, verbose_name='来源位置')),
                ('estimated_difficulty', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='难度估计')),
                ('is_explicitly_marked', models.BooleanField(default=False, verbose_name='评分表明确计分')),
                ('extraction_source', models.CharField(choices=[('manual', '人工'), ('parser', '解析器'), ('ai', 'AI')], default='manual', max_length=20, verbose_name='提取来源')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('capability_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_requirements', to='standards.capabilitydomain', verbose_name='能力领域')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='examcontent.exampaper', verbose_name='试题')),
            ],
            options={
                'verbose_name': '试题要求',
                'verbose_name_plural': '试题要求',
                'ordering': ['paper', 'code', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('paper', 'code'), name='uniq_examrequirement_paper_code')],
            },
        ),
    ]
