# Generated by Django 5.2.5 on 2025-08-21 02:35

import django.db.models.deletion
import notices.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='标题(可行)')),
                ('content', models.TextField(verbose_name='通知内容')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=notices.models.notice_attachment_upload_to, verbose_name='附件(可选)')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='是否发布')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_published', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'verbose_name': '通知',
                'verbose_name_plural': '通知',
                'ordering': ('-is_published', '-published_at', '-updated_at'),
            },
        ),
    ]
