# Generated by Django 5.2.5 on 2025-08-21 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='标题(可选)'),
        ),
    ]
