# Generated by Django 5.2.5 on 2025-08-21 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0002_alter_notice_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
    ]
