# Generated by Django 5.2.5 on 2025-08-21 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0003_alter_notice_published_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='查看时间')),
                ('notice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_by', to='notices.notice', verbose_name='通知')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices_read', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '通知已读记录',
                'verbose_name_plural': '通知已读记录',
                'indexes': [models.Index(fields=['user', 'notice'], name='notices_not_user_id_74fee3_idx'), models.Index(fields=['notice', 'user'], name='notices_not_notice__31b36d_idx')],
                'unique_together': {('user', 'notice')},
            },
        ),
    ]
