# Generated by Django 5.2.5 on 2025-08-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('notices', '0004_noticeread'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='target_groups',
            field=models.ManyToManyField(blank=True, help_text='如果未选择任何组，则向所有用户发送', to='auth.group', verbose_name='目标组'),
        ),
    ]
