# Generated by Django 5.2.5 on 2025-08-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0005_notice_target_groups'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NoticeRead',
        ),
    ]
