# Generated by Django 5.2.5 on 2025-08-21 11:01

import django.db.models.deletion
import notices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0006_delete_noticeread'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=notices.models.notice_attachment_upload_to, verbose_name='附件文件')),
                ('name', models.CharField(help_text='如果不填写，将使用文件名', max_length=255, verbose_name='附件名称')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('file_size', models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='notices.notice', verbose_name='通知')),
            ],
            options={
                'verbose_name': '通知附件',
                'verbose_name_plural': '通知附件',
                'ordering': ('uploaded_at',),
            },
        ),
    ]
