# Generated by Django 5.2.5 on 2025-08-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0007_noticeattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='attachment',
        ),
    ]
