# Generated by Django 5.2.5 on 2025-08-21 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0008_remove_attachment_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticeattachment',
            name='name',
        ),
    ]
