# Generated by Django 5.2.5 on 2025-08-30 03:50

import notices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0009_remove_attachment_name_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticeattachment',
            options={'ordering': ('uploaded_at',), 'verbose_name': '附件', 'verbose_name_plural': '附件'},
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='发布后用户才能看到此通知, 未发布即存为草稿', verbose_name='是否发布'),
        ),
        migrations.AlterField(
            model_name='noticeattachment',
            name='file',
            field=models.FileField(help_text='支持多个文件上传', upload_to=notices.models.notice_attachment_upload_to, verbose_name='附件文件'),
        ),
    ]
