# Generated by Django 5.2.5 on 2025-09-01 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0010_alter_noticeattachment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notices_published', to=settings.AUTH_USER_MODEL, verbose_name='发布人'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='标题(可选)'),
        ),
        migrations.AlterField(
            model_name='noticeattachment',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='文件大小(字节)'),
        ),
    ]
