# Generated by Django 5.2.5 on 2025-09-11 04:55

import django.core.validators
import notices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0011_alter_notice_published_at_alter_notice_published_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeattachment',
            name='file',
            field=models.FileField(help_text='支持多个文件上传', upload_to=notices.models.notice_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'md', 'jpg', 'jpeg', 'png', 'gif', 'txt', 'zip', 'rar', '7z', 'tar', 'gz', 'bz2'], message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, ppt, pptx, md, jpg, jpeg, png, gif, txt, zip, rar, 7z, tar, gz, bz2')], verbose_name='附件文件'),
        ),
    ]
