# Generated by Django 5.2.5 on 2025-09-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0012_alter_noticeattachment_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ('-published_at', '-updated_at'), 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
    ]
