# Generated by Django 5.2.5 on 2025-09-11 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0013_alter_notice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ('-updated_at', '-published_at'), 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
    ]
