# Generated by Django 5.2.5 on 2025-09-11 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0014_alter_notice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'ordering': ('-published_at', '-id'), 'verbose_name': '通知', 'verbose_name_plural': '通知'},
        ),
        migrations.RemoveField(
            model_name='notice',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='updated_at',
        ),
    ]
