# Generated by Django 6.0.1 on 2026-02-04 07:58

import core.utils.validators
import django.core.validators
import functools
import notices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0015_alter_notice_options_remove_notice_is_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeattachment',
            name='file',
            field=models.FileField(help_text='支持多个文件上传', upload_to=notices.models.notice_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'md', 'txt', 'jpg', 'jpeg', 'png', 'gif', 'zip', 'rar', '7z', 'tar', 'gz', 'bz2'], message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, ppt, pptx, md, txt, jpg, jpeg, png, gif, zip, rar, 7z, tar, gz, bz2'), functools.partial(core.utils.validators.validate_file_size, max_size_mb=100)], verbose_name='附件文件'),
        ),
    ]
