# Generated by Django 6.0.4 on 2026-05-16 07:47

import core.uploads
import django.core.validators
import notices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0016_alter_noticeattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeattachment',
            name='file',
            field=models.FileField(help_text='支持多个文件上传，支持 pdf, doc, docx, xls, xlsx, ppt, pptx, md, txt, jpg, jpeg, png, gif, zip, rar, 7z, tar, gz, bz2，大小不超过 100MB', upload_to=notices.models.notice_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'md', 'txt', 'jpg', 'jpeg', 'png', 'gif', 'zip', 'rar', '7z', 'tar', 'gz', 'bz2'), message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, ppt, pptx, md, txt, jpg, jpeg, png, gif, zip, rar, 7z, tar, gz, bz2'), core.uploads.UploadSizeValidator(100)], verbose_name='附件文件'),
        ),
    ]
