# Generated by Django 6.0.6 on 2026-06-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountdownEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='事件名称')),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True, verbose_name='访问标识')),
                ('subtitle', models.CharField(blank=True, max_length=200, verbose_name='副标题')),
                ('event_type', models.CharField(choices=[('worldskills', '世界技能大赛'), ('national', '全国技能大赛'), ('provincial', '省级技能大赛'), ('municipal', '市级技能大赛'), ('school', '校内比赛'), ('training', '集训活动'), ('exam', '考核测评'), ('meeting', '会议活动'), ('other', '其他活动')], default='other', max_length=20, verbose_name='事件类型')),
                ('project_name', models.CharField(blank=True, max_length=120, verbose_name='项目名称')),
                ('target_at', models.DateTimeField(verbose_name='目标时间')),
                ('location', models.CharField(blank=True, default='', max_length=120, verbose_name='地点')),
                ('theme', models.CharField(blank=True, choices=[('network', '网络系统管理大屏')], default='network', max_length=50, verbose_name='主题风格')),
                ('description', models.TextField(blank=True, verbose_name='说明文字')),
                ('countdown_prefix', models.CharField(blank=True, default='距离开始还有', help_text='显示在倒计时数字上方或附近的提示文字，例如：距离开幕还有、距离比赛开始还有。', max_length=50, verbose_name='倒计时前缀')),
                ('finished_message', models.CharField(blank=True, default='活动已经开始', help_text='当倒计时目标时间已到或已过时显示的提示文字。', max_length=100, verbose_name='结束提示语')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('display_order', models.PositiveIntegerField(default=10, verbose_name='显示排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '倒计时事件',
                'verbose_name_plural': '倒计时事件',
                'ordering': ['display_order', 'target_at'],
            },
        ),
    ]
