# Generated by Django 6.0.6 on 2026-06-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_countdown', '0002_countdownevent_project_english_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countdownevent',
            name='theme',
            field=models.CharField(blank=True, choices=[('network', '世赛网络系统管理项目倒计时大屏')], default='network', max_length=50, verbose_name='主题风格'),
        ),
    ]
