# Generated by Django 5.1.6 on 2025-03-18 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_remove_competition_bronze_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-level', 'name'), 'verbose_name': '竞赛', 'verbose_name_plural': '竞赛'},
        ),
        migrations.AlterModelOptions(
            name='competitiondetail',
            options={'verbose_name': '竞赛详情', 'verbose_name_plural': '竞赛详情'},
        ),
        migrations.AlterField(
            model_name='competition',
            name='level',
            field=models.CharField(choices=[('0IN', '国际级'), ('1NA', '国家级'), ('2PR', '省级'), ('3MU', '市级'), ('4OT', '其他')], default='4OT', max_length=3, verbose_name='级别'),
        ),
        migrations.CreateModel(
            name='CompetitionTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='参赛队名称')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.competition', verbose_name='竞赛')),
            ],
            options={
                'verbose_name': '参赛队',
                'verbose_name_plural': '参赛队',
                'ordering': ('name',),
            },
        ),
    ]
