# Generated by Django 5.1.6 on 2025-03-18 07:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_competition_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_result', models.CharField(blank=True, help_text='我们选手的成绩, 填写"金牌" "银牌" "铜牌" "优胜奖" "未获奖"，或名次，如"第一名"，或具体成绩，如"78.5分"', max_length=100, verbose_name='我们的选手成绩')),
                ('Competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.competition', verbose_name='竞赛')),
                ('bronze', models.ForeignKey(blank=True, help_text='获得铜牌的参赛队', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.competitionteam', verbose_name='获得铜牌的参赛队')),
                ('gold', models.ForeignKey(blank=True, help_text='获得金牌的参赛队', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.competitionteam', verbose_name='获得金牌的参赛队')),
                ('our_competitor', models.ForeignKey(help_text='我们的参赛选手', on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to=settings.AUTH_USER_MODEL, verbose_name='我们的参赛选手')),
                ('silver', models.ForeignKey(blank=True, help_text='获得银牌的参赛队', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='competitions.competitionteam', verbose_name='获得银牌的参赛队')),
            ],
            options={
                'verbose_name': '比赛结果',
                'verbose_name_plural': '比赛结果',
            },
        ),
    ]
