# Generated by Django 5.1.6 on 2025-03-18 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_competionresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competionresult',
            name='Competition',
        ),
        migrations.AlterUniqueTogether(
            name='competitionteam',
            unique_together={('competition', 'name')},
        ),
        migrations.AddField(
            model_name='competionresult',
            name='competition',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='competitions.competition', verbose_name='竞赛'),
            preserve_default=False,
        ),
    ]
