# Generated by Django 5.1.6 on 2025-03-18 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_remove_competionresult_competition_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionteam',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='competionresult',
            name='competition',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='result', to='competitions.competition', verbose_name='竞赛'),
        ),
        migrations.AlterField(
            model_name='competitionteam',
            name='name',
            field=models.CharField(help_text='参赛队名称', max_length=100, unique=True, verbose_name='参赛队名称'),
        ),
    ]
