# Generated by Django 5.1.6 on 2025-03-18 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_alter_competitionteam_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionteam',
            name='competition',
        ),
        migrations.AlterField(
            model_name='competionresult',
            name='our_competitor',
            field=models.ForeignKey(blank=True, help_text='我们的参赛选手', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to=settings.AUTH_USER_MODEL, verbose_name='我们的参赛选手'),
        ),
        migrations.AlterField(
            model_name='competitiondetail',
            name='location',
            field=models.CharField(blank=True, help_text='比赛举办城市', max_length=100, verbose_name='地点'),
        ),
        migrations.CreateModel(
            name='CompetitionTeamRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='competitions.competition', verbose_name='竞赛')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_relations', to='competitions.competitionteam', verbose_name='参赛队')),
            ],
            options={
                'verbose_name': '竞赛-参赛队关系',
                'verbose_name_plural': '竞赛-参赛队关系',
                'unique_together': {('competition', 'team')},
            },
        ),
        migrations.AddField(
            model_name='competitionteam',
            name='competitions',
            field=models.ManyToManyField(related_name='all_teams', through='competitions.CompetitionTeamRelation', to='competitions.competition', verbose_name='参加的竞赛'),
        ),
    ]
