# Generated by Django 5.1.6 on 2025-03-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_remove_competitionteam_competition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='weight',
            field=models.FloatField(default=1.0, help_text='比赛的权重，用于计算考点的重要性', verbose_name='权重'),
        ),
    ]
