# Generated by Django 5.1.6 on 2025-03-21 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0008_competition_weight'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionteamrelation',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='competitionteamrelation',
            constraint=models.UniqueConstraint(fields=('competition', 'team'), name='unique_competition_team'),
        ),
    ]
