# Generated by Django 6.0.1 on 2026-02-05 00:45

import conduct.models
import core.utils.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import functools
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='总分')),
                ('reward_count', models.PositiveIntegerField(default=0, verbose_name='奖励次数')),
                ('penalty_count', models.PositiveIntegerField(default=0, verbose_name='惩罚次数')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('student', models.OneToOneField(limit_choices_to={'groups__name': '选手'}, on_delete=django.db.models.deletion.CASCADE, related_name='conduct_summary', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
            ],
            options={
                'verbose_name': '奖惩汇总',
                'verbose_name_plural': '奖惩汇总',
                'ordering': ['-total_score'],
            },
        ),
        migrations.CreateModel(
            name='ConductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类型名称')),
                ('category', models.CharField(choices=[('REWARD', '奖励'), ('PENALTY', '惩罚')], max_length=10, verbose_name='分类')),
                ('score', models.DecimalField(decimal_places=2, help_text='正数为奖励分，负数为惩罚分', max_digits=6, verbose_name='对应分值')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conduct_types', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '奖惩类型',
                'verbose_name_plural': '奖惩类型',
                'ordering': ['category', '-score', 'name'],
                'permissions': [('manage_conduct_types', '管理奖惩类型')],
            },
        ),
        migrations.CreateModel(
            name='ConductRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_date', models.DateField(default=django.utils.timezone.localdate, help_text='请填写实际发生日期', validators=[core.utils.validators.validate_date_not_future], verbose_name='事件发生日期')),
                ('score', models.DecimalField(decimal_places=2, help_text='默认使用类型分值，可微调', max_digits=6, verbose_name='实际得分')),
                ('reason', models.TextField(verbose_name='具体原因/描述')),
                ('attachment', models.FileField(blank=True, help_text='支持PDF、图片等格式，文件大小不超过 100MB', null=True, upload_to=conduct.models.conduct_attachment_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'doc', 'docx'], message='仅支持PDF、图片或Word文档'), functools.partial(core.utils.validators.validate_file_size, max_size_mb=100)], verbose_name='附件')),
                ('status', models.CharField(choices=[('PENDING', '待审核'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='PENDING', max_length=10, verbose_name='状态')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_note', models.TextField(blank=True, verbose_name='审核意见')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_conducts', to=settings.AUTH_USER_MODEL, verbose_name='记录人')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_conducts', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('student', models.ForeignKey(limit_choices_to={'groups__name': '选手'}, on_delete=django.db.models.deletion.CASCADE, related_name='conduct_records', to=settings.AUTH_USER_MODEL, verbose_name='学生')),
                ('record_type', models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='conduct.conducttype', verbose_name='奖惩类型')),
            ],
            options={
                'verbose_name': '奖惩记录',
                'verbose_name_plural': '奖惩记录',
                'ordering': ['-occurred_date', '-recorded_at'],
                'permissions': [('add_conduct_record', '录入奖惩记录'), ('review_conduct_record', '审核奖惩记录'), ('view_all_conduct_records', '查看所有奖惩记录')],
            },
        ),
    ]
