# Generated by Django 6.0.2 on 2026-02-06 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduct', '0002_alter_conductrecord_attachment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConductGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='大类名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '奖惩大类',
                'verbose_name_plural': '奖惩大类',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='conducttype',
            options={'ordering': ['group', 'category', '-score', 'name'], 'permissions': [('manage_conduct_types', '管理奖惩类型')], 'verbose_name': '奖惩类型', 'verbose_name_plural': '奖惩类型'},
        ),
        migrations.RemoveField(
            model_name='conductrecord',
            name='score',
        ),
        migrations.AddField(
            model_name='conducttype',
            name='group',
            field=models.ForeignKey(default=1, help_text='奖惩所属的大类别', on_delete=django.db.models.deletion.PROTECT, related_name='conduct_types', to='conduct.conductgroup', verbose_name='大类'),
            preserve_default=False,
        ),
    ]
