# Generated by Django 6.0.2 on 2026-02-07 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduct', '0003_conductgroup_alter_conducttype_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conducttype',
            name='group',
        ),
        migrations.RemoveField(
            model_name='conducttype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='conductrecord',
            name='record_type',
        ),
        migrations.CreateModel(
            name='ConductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('REWARD', '奖励'), ('PENALTY', '惩罚'), ('WARNING', '警告')], help_text='行为性质：奖励、惩罚或警告', max_length=20, verbose_name='性质')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '奖惩分类',
                'verbose_name_plural': '奖惩分类',
                'ordering': ['nature', 'order', 'name'],
                'unique_together': {('nature', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ConductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='事项名称')),
                ('score', models.DecimalField(decimal_places=2, help_text='奖励为正数，惩罚为负数，警告为0', max_digits=6, verbose_name='分值')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='conduct.conductcategory', verbose_name='所属分类')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_conduct_items', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
            ],
            options={
                'verbose_name': '奖惩事项',
                'verbose_name_plural': '奖惩事项',
                'ordering': ['category__nature', 'category__order', '-score', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.AddField(
            model_name='conductrecord',
            name='item',
            field=models.ForeignKey(default=1, limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='records', to='conduct.conductitem', verbose_name='奖惩事项'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ConductGroup',
        ),
        migrations.DeleteModel(
            name='ConductType',
        ),
    ]
