# Generated by Django 6.0.3 on 2026-04-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduct', '0004_remove_conducttype_group_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conductitem',
            options={'ordering': ['category__nature', 'category__order', 'name'], 'verbose_name': '奖惩事项', 'verbose_name_plural': '奖惩事项'},
        ),
        migrations.RemoveField(
            model_name='conductitem',
            name='score',
        ),
        migrations.AddField(
            model_name='conductrecord',
            name='severity',
            field=models.CharField(choices=[('MINOR', '轻微'), ('MODERATE', '一般'), ('SEVERE', '严重'), ('CRITICAL', '特别严重')], default='MODERATE', help_text='分值由事项性质和严重程度规则共同决定', max_length=20, verbose_name='严重程度'),
        ),
        migrations.AlterField(
            model_name='conductcategory',
            name='nature',
            field=models.CharField(choices=[('REWARD', '奖励'), ('PENALTY', '惩罚')], help_text='行为性质：奖励、惩罚', max_length=20, verbose_name='性质'),
        ),
        migrations.CreateModel(
            name='ConductSeverityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(choices=[('REWARD', '奖励'), ('PENALTY', '惩罚')], max_length=20, verbose_name='性质')),
                ('severity', models.CharField(choices=[('MINOR', '轻微'), ('MODERATE', '一般'), ('SEVERE', '严重'), ('CRITICAL', '特别严重')], max_length=20, verbose_name='严重程度')),
                ('score', models.DecimalField(decimal_places=2, help_text='奖励为正数，惩罚为负数。', max_digits=6, verbose_name='分值')),
                ('order', models.IntegerField(default=0, help_text='数字越小越靠前', verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '奖惩分值规则',
                'verbose_name_plural': '奖惩分值规则',
                'ordering': ['nature', 'order', 'severity'],
                'unique_together': {('nature', 'severity')},
            },
        ),
    ]
