# Generated by Django 6.0.3 on 2026-04-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conduct', '0009_alter_conductcategory_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductseverityrule',
            name='severity',
            field=models.CharField(choices=[('MINOR', '轻微'), ('MODERATE', '一般'), ('SEVERE', '严重'), ('CRITICAL', '特别严重')], max_length=20, verbose_name='程度'),
        ),
    ]
