---
# 定义考核应用的菜单项

menu_slug: "assessment"
app_name: "assessment"
items:
  - name: "考核管理"
    icon: 
      pic: "icon-[tabler--wallpaper]"
      size: 4
    is_group_header: true
    children:
        - name: "考核列表"
          named_url: "assessment:list"
          icon: 
            pic: "icon-[tabler--list-check]"
            size: 4
          is_visible: true
          login_required: true
        - name: "资料上传"
          named_url: "assessment:file_upload_list"
          icon:
            pic: "icon-[tabler--upload]"
            size: 4
          is_visible: true
          login_required: true
          required_perms:
            - "assessment.add_assessmentattachment"
