---
menu_slug: "competition_standards"
app_name: "competition_standards"
items:
  - name: "训练周期"
    icon:
      pic: "icon-[tabler--calendar]"
      size: 4
    is_group_header: true
    children:
      - name: "周期列表"
        named_url: "competition_standards:list"
        icon:
          pic: "icon-[tabler--list-details]"
          size: 4
        is_visible: true
        login_required: true