---
menu_slug: "competitions"
app_name: "competitions"
items:
  - name: "竞赛信息"
    icon:
      pic: "icon-[tabler--trophy]"
      size: 4
    is_group_header: true
    children:
      - name: "竞赛列表"
        named_url: "competitions:competition_list"
        icon:
          pic: "icon-[tabler--list-details]"
          size: 4
        is_visible: true
        login_required: true
      - name: "新增专家"
        named_url: "competitions:expert_create"
        icon:
          pic: "icon-[tabler--user-star]"
          size: 4
        is_visible: true
        login_required: true
        required_perms:
          - "competitions.add_expert"
      - name: "新增岗位人员"
        named_url: "competitions:skillposition_create"
        icon:
          pic: "icon-[tabler--briefcase-2]"
          size: 4
        is_visible: true
        login_required: true
        required_perms:
          - "competitions.add_skillposition"
      - name: "录入竞赛总成绩"
        named_url: "competitions:competitionresult_create"
        icon:
          pic: "icon-[tabler--chart-bar]"
          size: 4
        is_visible: true
        login_required: true
        required_perms:
          - "competitions.add_competitionresult"