menu_slug: "feedback"
app_name: None
items:
  - name: "问题反馈"
    external_url: "https://github.com/hdaojin/tms/issues/new"
    icon: 
      pic: "icon-[tabler--message-question]"
      size: 4
    is_visible: true
    login_required: false
    target_blank: true