---
# 定义通知公告应用的菜单项

menu_slug: "notices"
app_name: "notices"
items:
  - name: "通知公告管理"
    icon: 
      pic: "icon-[tabler--bell]"
      size: 4
    is_group_header: true
    children:
      - name: "通知公告列表"
        named_url: "notices:notice_list"
        icon: 
          pic: "icon-[tabler--list]"
          size: 4
        is_visible: true
        login_required: true
  
      - name: "创建通知公告"
        named_url: "notices:notice_create"
        icon: 
          pic: "icon-[tabler--plus]"
          size: 4
        is_visible: true
        login_required: true
  