---
menu_slug: "skilltrees"
app_name: "skilltrees"
items:
  - name: "技能树"
    icon:
      pic: "icon-[tabler--hierarchy-3]"
      size: 4
    is_group_header: true
    children:
      - name: "技能树列表"
        named_url: "skilltrees:list"
        icon:
          pic: "icon-[tabler--list-search]"
          size: 4
        is_visible: true
        login_required: true
      - name: "新建技能树"
        named_url: "skilltrees:create"
        icon:
          pic: "icon-[tabler--plus]"
          size: 4
        is_visible: true
        login_required: true
        required_perms:
          - "skilltrees.add_skilltree"
