---
# 定义训练日志应用的菜单项
menu_slug: "traininglogs"
app_name: "traininglogs"
items:
  - name: 训练日志管理
    icon: 
      pic: icon-[tabler--file-text]
    is_group_header: true
    children:
      - name: 我的训练日志
        named_url: "traininglogs:traininglog_list"
        icon: 
          pic: icon-[tabler--file-stack]
        is_visible: true
        login_required: true

      - name: 教练训练日志
        named_url: "traininglogs:traininglog_coach_list"
        icon: 
          pic: icon-[tabler--file-search]
        is_visible: true
        login_required: true
        perm_match_all: true
        required_perms: 
          - traininglogs.view_coach_traininglog

      - name: 选手训练日志
        named_url: "traininglogs:traininglog_competitor_list"
        icon: 
          pic: icon-[tabler--file-search]
        is_visible: true
        login_required: true
        perm_match_all: true
        required_perms: 
          - traininglogs.view_competitor_traininglog

      - name: 上传训练日志
        named_url: "traininglogs:traininglog_upload"
        icon: 
          pic: icon-[tabler--upload]
        is_visible: true
        login_required: true
        perm_match_all: false
        required_perms:
          - traininglogs.add_traininglog

      - name: 日志提交统计
        named_url: "traininglogs:traininglog_stats"
        icon: 
          pic: icon-[tabler--chart-bar]
        is_visible: true
        login_required: true
