# Generated by Django 6.0.6 on 2026-08-11 02:12

import core.uploads
import django.db.models.deletion
import glossary.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlossaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_term', models.CharField(max_length=255, verbose_name='英文')),
                ('english_key', models.CharField(editable=False, max_length=255, verbose_name='英文比较键')),
                ('acronym', models.CharField(blank=True, max_length=100, verbose_name='Acronym')),
                ('chinese_translation', models.TextField(verbose_name='中文释义')),
                ('english_aliases', models.JSONField(blank=True, default=list, verbose_name='英文答案别名')),
                ('chinese_aliases', models.JSONField(blank=True, default=list, verbose_name='中文答案别名')),
                ('source', models.CharField(choices=[('import', '文件导入'), ('proposal', '词条提案'), ('manager', '管理者录入')], default='manager', max_length=20, verbose_name='来源')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_glossary_entries', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_glossary_entries', to=settings.AUTH_USER_MODEL, verbose_name='更新人')),
            ],
            options={
                'verbose_name': '词条',
                'verbose_name_plural': '词条',
                'ordering': ['glossary', 'english_key', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ProfessionalGlossary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='词库名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_professional_glossaries', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('skill_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional_glossaries', to='standards.skillproject', verbose_name='技能项目')),
            ],
            options={
                'verbose_name': '专业词库',
                'verbose_name_plural': '专业词库',
                'ordering': ['skill_project', 'name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.FileField(storage=core.uploads.PrivateMediaStorage('glossary'), upload_to=glossary.models.glossary_import_upload_path, verbose_name='源 XLSX')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA256')),
                ('status', models.CharField(choices=[('preview', '待确认'), ('invalid', '校验未通过'), ('confirmed', '已确认'), ('stale', '已过期')], default='preview', max_length=20, verbose_name='状态')),
                ('parsed_payload', models.JSONField(default=dict, verbose_name='解析快照')),
                ('decision_payload', models.JSONField(blank=True, default=dict, verbose_name='确认决策')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='导入结果')),
                ('glossary_version', models.DateTimeField(verbose_name='词库预览版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('imported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='glossary_imports', to=settings.AUTH_USER_MODEL, verbose_name='导入人')),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imports', to='glossary.professionalglossary', verbose_name='专业词库')),
            ],
            options={
                'verbose_name': '词库导入记录',
                'verbose_name_plural': '词库导入记录',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='GlossaryEntryProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_term', models.CharField(max_length=255, verbose_name='英文')),
                ('english_key', models.CharField(editable=False, max_length=255, verbose_name='英文比较键')),
                ('acronym', models.CharField(blank=True, max_length=100, verbose_name='Acronym')),
                ('chinese_translation', models.TextField(verbose_name='中文释义')),
                ('english_aliases', models.JSONField(blank=True, default=list, verbose_name='英文答案别名')),
                ('chinese_aliases', models.JSONField(blank=True, default=list, verbose_name='中文答案别名')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='pending', max_length=20, verbose_name='审核状态')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_note', models.TextField(blank=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('resulting_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_proposal', to='glossary.glossaryentry', verbose_name='生成词条')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_glossary_entry_proposals', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='glossary_entry_proposals', to=settings.AUTH_USER_MODEL, verbose_name='提交人')),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_proposals', to='glossary.professionalglossary', verbose_name='专业词库')),
            ],
            options={
                'verbose_name': '词条提案',
                'verbose_name_plural': '词条提案',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.AddField(
            model_name='glossaryentry',
            name='glossary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='glossary.professionalglossary', verbose_name='专业词库'),
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('en_to_zh', '英文答中文'), ('zh_to_en', '中文答英文'), ('mixed', '均衡随机')], max_length=20, verbose_name='学习模式')),
                ('target_count', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='目标题量')),
                ('status', models.CharField(choices=[('active', '进行中'), ('completed', '已完成'), ('stopped', '已停止')], default='active', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('glossary', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_sessions', to='glossary.professionalglossary', verbose_name='专业词库')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='glossary_study_sessions', to=settings.AUTH_USER_MODEL, verbose_name='学习者')),
            ],
            options={
                'verbose_name': '学习会话',
                'verbose_name_plural': '学习会话',
                'ordering': ['-started_at', '-pk'],
                'permissions': [('view_all_study_statistics', '能查看全部专业词汇学习统计')],
            },
        ),
        migrations.CreateModel(
            name='StudyAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField(verbose_name='题号')),
                ('direction', models.CharField(choices=[('en_to_zh', '英文答中文'), ('zh_to_en', '中文答英文')], max_length=20, verbose_name='题目方向')),
                ('prompt_snapshot', models.TextField(verbose_name='题面快照')),
                ('expected_answers_snapshot', models.JSONField(default=list, verbose_name='标准答案快照')),
                ('submitted_answer', models.TextField(blank=True, verbose_name='提交答案')),
                ('normalized_submitted_answer', models.TextField(blank=True, verbose_name='规范化答案')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='正确')),
                ('presented_at', models.DateTimeField(auto_now_add=True, verbose_name='出题时间')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='作答时间')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_attempts', to='glossary.glossaryentry', verbose_name='词条')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='glossary.studysession', verbose_name='学习会话')),
            ],
            options={
                'verbose_name': '作答记录',
                'verbose_name_plural': '作答记录',
                'ordering': ['session', 'sequence'],
            },
        ),
        migrations.AddConstraint(
            model_name='professionalglossary',
            constraint=models.UniqueConstraint(fields=('skill_project', 'name'), name='uniq_glossary_project_name'),
        ),
        migrations.AddConstraint(
            model_name='glossaryentry',
            constraint=models.UniqueConstraint(fields=('glossary', 'english_key'), name='uniq_glossary_english_key'),
        ),
        migrations.AddConstraint(
            model_name='studyattempt',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='uniq_study_attempt_sequence'),
        ),
    ]
