# Generated by Django 6.0.6 on 2026-08-18 02:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringParserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_key', models.CharField(max_length=80, unique=True, verbose_name='解析器标识')),
                ('display_name', models.CharField(max_length=120, verbose_name='显示名称')),
                ('alias', models.CharField(blank=True, max_length=80, verbose_name='别名')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认解析器')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '评分表解析器',
                'verbose_name_plural': '评分表解析器',
                'ordering': ['order', 'display_name', 'parser_key'],
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(('is_default', True)),
                        fields=('is_default',),
                        name='uniq_default_scoring_parser_config',
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name='ScoringScheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('module_code', models.CharField(max_length=50, verbose_name='模块代码')),
                ('module_name', models.CharField(max_length=150, verbose_name='模块名称')),
                (
                    'total_mark',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                        verbose_name='总分',
                    ),
                ),
                ('parser_version', models.CharField(blank=True, max_length=30, verbose_name='解析器版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'assessment_module',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='scoring_schemes',
                        to='assessments.assessmentmodule',
                        verbose_name='评测模块',
                    ),
                ),
                (
                    'imported_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='imported_scoring_schemes',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='导入人',
                    ),
                ),
                (
                    'source_document',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='scoring_schemes',
                        to='assessments.assessmentdocument',
                        verbose_name='来源评分表',
                    ),
                ),
            ],
            options={
                'verbose_name': '评分方案',
                'verbose_name_plural': '评分方案',
                'ordering': ['-created_at', 'module_code', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ScoringResultImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='导入摘要')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                (
                    'imported_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='scoring_result_imports',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='导入者',
                    ),
                ),
                (
                    'source_document',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='scoring_result_imports',
                        to='assessments.assessmentdocument',
                        verbose_name='来源结果包',
                    ),
                ),
                (
                    'scheme',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='result_imports',
                        to='scoring.scoringscheme',
                        verbose_name='评分方案',
                    ),
                ),
            ],
            options={
                'verbose_name': '结果包导入',
                'verbose_name_plural': '结果包导入',
                'ordering': ['-imported_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ScoringParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_identifier', models.CharField(blank=True, max_length=100, verbose_name='外部编号')),
                ('display_name', models.CharField(max_length=200, verbose_name='显示名称')),
                ('organization', models.CharField(blank=True, max_length=200, verbose_name='所属单位')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                (
                    'assessment_participant',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='scoring_participations',
                        to='assessments.assessmentparticipant',
                        verbose_name='评测参与人员',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='scoring_participations',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='关联用户',
                    ),
                ),
                (
                    'scheme',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='participants',
                        to='scoring.scoringscheme',
                        verbose_name='评分方案',
                    ),
                ),
            ],
            options={
                'verbose_name': '参评对象',
                'verbose_name_plural': '参评对象',
                'ordering': ['scheme', 'order', 'display_name', 'pk'],
                'permissions': [('view_all_scoringparticipant', '查看全部参评对象')],
            },
        ),
        migrations.CreateModel(
            name='ScoringSchemeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.CharField(
                        choices=[('parsed', '已解析'), ('confirmed', '已确认')],
                        default='parsed',
                        max_length=20,
                        verbose_name='状态',
                    ),
                ),
                ('parser_key', models.CharField(max_length=80, verbose_name='解析器标识')),
                ('parser_display_name', models.CharField(max_length=120, verbose_name='解析器显示名称')),
                ('parser_alias', models.CharField(blank=True, max_length=80, verbose_name='解析器别名')),
                ('parser_description', models.TextField(blank=True, verbose_name='解析器说明')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('module_code', models.CharField(max_length=50, verbose_name='模块代码')),
                ('module_name', models.CharField(max_length=150, verbose_name='模块名称')),
                ('module_mark', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='模块总分')),
                ('total_mark', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='评分点总分')),
                ('raw_snapshot', models.JSONField(blank=True, default=dict, verbose_name='原始快照')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='字段映射')),
                ('validation_report', models.JSONField(blank=True, default=dict, verbose_name='校验报告')),
                ('parsed_payload', models.JSONField(blank=True, default=dict, verbose_name='解析数据')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                (
                    'assessment_module',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='scoring_scheme_imports',
                        to='assessments.assessmentmodule',
                        verbose_name='评测模块',
                    ),
                ),
                (
                    'imported_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='scoring_scheme_imports',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='导入人',
                    ),
                ),
                (
                    'scheme',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='scheme_imports',
                        to='scoring.scoringscheme',
                        verbose_name='生成评分方案',
                    ),
                ),
                (
                    'source_document',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='scoring_scheme_imports',
                        to='assessments.assessmentdocument',
                        verbose_name='来源评分表',
                    ),
                ),
            ],
            options={
                'verbose_name': '评分表导入记录',
                'verbose_name_plural': '评分表导入记录',
                'ordering': ['-imported_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ScoringSubCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='子评分项编号')),
                ('name', models.CharField(max_length=300, verbose_name='子评分项名称或描述')),
                ('day_of_marking', models.CharField(blank=True, max_length=50, verbose_name='评分日')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                (
                    'scheme',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='subcriteria',
                        to='scoring.scoringscheme',
                        verbose_name='评分方案',
                    ),
                ),
            ],
            options={
                'verbose_name': '评分子项',
                'verbose_name_plural': '评分子项',
                'ordering': ['scheme', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ScoringAspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='评分点编号')),
                (
                    'aspect_type',
                    models.CharField(choices=[('M', '测量'), ('J', '评价')], max_length=1, verbose_name='评分类型'),
                ),
                ('description', models.TextField(verbose_name='评分点')),
                ('command', models.TextField(blank=True, verbose_name='命令或操作')),
                ('requirement', models.TextField(blank=True, verbose_name='期望结果')),
                ('calculation_row', models.CharField(blank=True, max_length=100, verbose_name='Calculation Row')),
                (
                    'max_mark',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                        verbose_name='分值',
                    ),
                ),
                ('source_row_number', models.PositiveIntegerField(verbose_name='来源行号')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                (
                    'scheme',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='aspects',
                        to='scoring.scoringscheme',
                        verbose_name='评分方案',
                    ),
                ),
                (
                    'subcriterion',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='aspects',
                        to='scoring.scoringsubcriterion',
                        verbose_name='评分子项',
                    ),
                ),
            ],
            options={
                'verbose_name': '评分点',
                'verbose_name_plural': '评分点',
                'ordering': ['scheme', 'subcriterion__order', 'order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='JudgementOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_value', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='分档值')),
                ('description', models.TextField(verbose_name='分档说明')),
                ('source_row_number', models.PositiveIntegerField(verbose_name='来源行号')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                (
                    'aspect',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='judgement_options',
                        to='scoring.scoringaspect',
                        verbose_name='评价评分点',
                    ),
                ),
            ],
            options={
                'verbose_name': '评价分档',
                'verbose_name_plural': '评价分档',
                'ordering': ['aspect', 'order', 'score_value'],
                'constraints': [
                    models.UniqueConstraint(fields=('aspect', 'score_value'), name='uniq_judgement_option')
                ],
            },
        ),
        migrations.CreateModel(
            name='ScoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'score_awarded',
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal('0.00'),
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(Decimal('0.00'))],
                        verbose_name='得分',
                    ),
                ),
                (
                    'source',
                    models.CharField(
                        choices=[('cmp', 'CMP 导入'), ('imported', '文件导入'), ('manual', '人工录入')],
                        default='imported',
                        max_length=20,
                        verbose_name='来源',
                    ),
                ),
                ('evidence', models.TextField(blank=True, verbose_name='证据摘要')),
                ('raw_payload', models.JSONField(blank=True, default=dict, verbose_name='原始结果')),
                ('graded_at', models.DateTimeField(blank=True, null=True, verbose_name='评分时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'aspect',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='results',
                        to='scoring.scoringaspect',
                        verbose_name='评分点',
                    ),
                ),
                (
                    'participant',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='results',
                        to='scoring.scoringparticipant',
                        verbose_name='参评对象',
                    ),
                ),
            ],
            options={
                'verbose_name': '评分结果',
                'verbose_name_plural': '评分结果',
                'ordering': ['participant', 'aspect__order', 'pk'],
                'permissions': [('view_all_scoringresult', '查看全部评分结果')],
                'constraints': [models.UniqueConstraint(fields=('participant', 'aspect'), name='uniq_scoring_result')],
            },
        ),
        migrations.AddConstraint(
            model_name='scoringscheme',
            constraint=models.UniqueConstraint(
                fields=('assessment_module', 'module_code'), name='uniq_scoringscheme_assessmentmodule_code'
            ),
        ),
        migrations.AddConstraint(
            model_name='scoringparticipant',
            constraint=models.UniqueConstraint(
                condition=models.Q(('assessment_participant__isnull', False)),
                fields=('scheme', 'assessment_participant'),
                name='uniq_scoringparticipant_assessment_participant',
            ),
        ),
        migrations.AddConstraint(
            model_name='scoringparticipant',
            constraint=models.UniqueConstraint(
                condition=models.Q(('user__isnull', False)),
                fields=('scheme', 'user'),
                name='uniq_scoringparticipant_user',
            ),
        ),
        migrations.AddConstraint(
            model_name='scoringparticipant',
            constraint=models.UniqueConstraint(
                condition=models.Q(('external_identifier', ''), _negated=True),
                fields=('scheme', 'external_identifier'),
                name='uniq_scoringparticipant_external',
            ),
        ),
        migrations.AddConstraint(
            model_name='scoringsubcriterion',
            constraint=models.UniqueConstraint(fields=('scheme', 'code'), name='uniq_scoring_subcriterion'),
        ),
        migrations.AddConstraint(
            model_name='scoringaspect',
            constraint=models.UniqueConstraint(fields=('scheme', 'code'), name='uniq_scoring_aspect_code'),
        ),
        migrations.AddConstraint(
            model_name='scoringaspect',
            constraint=models.UniqueConstraint(
                fields=('scheme', 'source_row_number'), name='uniq_scoring_aspect_source_row'
            ),
        ),
    ]
