# Generated by Django 6.0.6 on 2026-06-19 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archives', '0001_initial'),
        ('events', '0001_initial'),
        ('scoring', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringaspect',
            name='calculation_row',
            field=models.CharField(blank=True, max_length=100, verbose_name='Calculation Row'),
        ),
        migrations.CreateModel(
            name='ScoringParserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parser_key', models.CharField(max_length=80, unique=True, verbose_name='解析器标识')),
                ('display_name', models.CharField(max_length=120, verbose_name='显示名称')),
                ('alias', models.CharField(blank=True, max_length=80, verbose_name='别名')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('is_default', models.BooleanField(default=False, verbose_name='默认解析器')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '评分表解析器',
                'verbose_name_plural': '评分表解析器',
                'ordering': ['order', 'display_name', 'parser_key'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='uniq_default_scoring_parser_config')],
            },
        ),
        migrations.CreateModel(
            name='ScoringSchemeImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('parsed', '已解析'), ('confirmed', '已确认')], default='parsed', max_length=20, verbose_name='状态')),
                ('parser_key', models.CharField(max_length=80, verbose_name='解析器标识')),
                ('parser_display_name', models.CharField(max_length=120, verbose_name='解析器显示名称')),
                ('parser_alias', models.CharField(blank=True, max_length=80, verbose_name='解析器别名')),
                ('parser_description', models.TextField(blank=True, verbose_name='解析器说明')),
                ('title', models.CharField(max_length=255, verbose_name='标题')),
                ('module_code', models.CharField(max_length=50, verbose_name='模块代码')),
                ('module_name', models.CharField(max_length=150, verbose_name='模块名称')),
                ('module_mark', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='模块总分')),
                ('total_mark', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='评分点总分')),
                ('raw_snapshot', models.JSONField(blank=True, default=dict, verbose_name='原始快照')),
                ('field_mapping', models.JSONField(blank=True, default=dict, verbose_name='字段映射')),
                ('validation_report', models.JSONField(blank=True, default=dict, verbose_name='校验报告')),
                ('parsed_payload', models.JSONField(blank=True, default=dict, verbose_name='解析数据')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='确认时间')),
                ('event_module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scoring_scheme_imports', to='events.eventmodule', verbose_name='事件模块')),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring_scheme_imports', to=settings.AUTH_USER_MODEL, verbose_name='导入人')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheme_imports', to='scoring.scoringscheme', verbose_name='生成评分方案')),
                ('source_asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scoring_scheme_imports', to='archives.archiveasset', verbose_name='来源评分表')),
            ],
            options={
                'verbose_name': '评分表导入记录',
                'verbose_name_plural': '评分表导入记录',
                'ordering': ['-imported_at', '-pk'],
            },
        ),
    ]
