# Generated by Django 6.0.6 on 2026-09-04 14:57

import django.db.models.deletion
from django.db import migrations, models


def _reclassify_source_documents(apps, *, database_alias, old_type, new_type):
    AssessmentDocument = apps.get_model('assessments', 'AssessmentDocument')
    ScoringScheme = apps.get_model('scoring', 'ScoringScheme')
    ScoringSchemeImport = apps.get_model('scoring', 'ScoringSchemeImport')
    source_ids = set(
        ScoringScheme.objects.using(database_alias)
        .exclude(source_document_id=None)
        .values_list('source_document_id', flat=True)
    )
    source_ids.update(
        ScoringSchemeImport.objects.using(database_alias).values_list('source_document_id', flat=True)
    )

    for document in AssessmentDocument.objects.using(database_alias).filter(
        pk__in=source_ids,
        document_type=old_type,
    ):
        replacement = (
            AssessmentDocument.objects.using(database_alias)
            .filter(
                assessment_id=document.assessment_id,
                module_id=document.module_id,
                document_type=new_type,
                file_sha256=document.file_sha256,
            )
            .exclude(pk=document.pk)
            .first()
        )
        if replacement is None:
            AssessmentDocument.objects.using(database_alias).filter(pk=document.pk).update(
                document_type=new_type
            )
            continue
        ScoringScheme.objects.using(database_alias).filter(source_document_id=document.pk).update(
            source_document_id=replacement.pk
        )
        ScoringSchemeImport.objects.using(database_alias).filter(source_document_id=document.pk).update(
            source_document_id=replacement.pk
        )


def use_marking_standard_sources(apps, schema_editor):
    database_alias = schema_editor.connection.alias
    _reclassify_source_documents(
        apps,
        database_alias=database_alias,
        old_type='marking_scheme',
        new_type='marking_standard',
    )
    ScoringParserConfig = apps.get_model('scoring', 'ScoringParserConfig')
    ScoringParserConfig.objects.using(database_alias).filter(
        parser_key='cmp_single_module_v1',
        display_name='CMP 单模块评分表',
    ).update(display_name='CMP 单模块评分标准')
    ScoringParserConfig.objects.using(database_alias).filter(
        parser_key='cmp_single_module_v1',
        description='严格解析 CMP 官方单模块评分表模板，支持 M 测量评分点和 J 评价四档分档。',
    ).update(description='严格解析 CMP 官方单模块评分标准模板，支持 M 测量评分点和 J 评价四档分档。')


def restore_marking_scheme_sources(apps, schema_editor):
    database_alias = schema_editor.connection.alias
    _reclassify_source_documents(
        apps,
        database_alias=database_alias,
        old_type='marking_standard',
        new_type='marking_scheme',
    )
    ScoringParserConfig = apps.get_model('scoring', 'ScoringParserConfig')
    ScoringParserConfig.objects.using(database_alias).filter(
        parser_key='cmp_single_module_v1',
        display_name='CMP 单模块评分标准',
    ).update(display_name='CMP 单模块评分表')
    ScoringParserConfig.objects.using(database_alias).filter(
        parser_key='cmp_single_module_v1',
        description='严格解析 CMP 官方单模块评分标准模板，支持 M 测量评分点和 J 评价四档分档。',
    ).update(description='严格解析 CMP 官方单模块评分表模板，支持 M 测量评分点和 J 评价四档分档。')


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_finalize_assessment_type'),
        ('scoring', '0002_unify_scoring_results_with_assessment_participants'),
    ]

    operations = [
        migrations.RunPython(use_marking_standard_sources, restore_marking_scheme_sources),
        migrations.AlterModelOptions(
            name='scoringparserconfig',
            options={'ordering': ['order', 'display_name', 'parser_key'], 'verbose_name': '评分标准解析器', 'verbose_name_plural': '评分标准解析器'},
        ),
        migrations.AlterModelOptions(
            name='scoringschemeimport',
            options={'ordering': ['-imported_at', '-pk'], 'verbose_name': '评分标准导入记录', 'verbose_name_plural': '评分标准导入记录'},
        ),
        migrations.AlterField(
            model_name='scoringscheme',
            name='source_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoring_schemes', to='assessments.assessmentdocument', verbose_name='来源评分标准'),
        ),
        migrations.AlterField(
            model_name='scoringschemeimport',
            name='source_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scoring_scheme_imports', to='assessments.assessmentdocument', verbose_name='来源评分标准'),
        ),
    ]
