# Generated by Codex on 2026-06-20

from django.db import migrations


def seed_cmp_single_module_parser(apps, schema_editor):
    ScoringParserConfig = apps.get_model("scoring", "ScoringParserConfig")
    existing = ScoringParserConfig.objects.filter(parser_key="cmp_single_module_v1").first()
    is_default = bool(existing and existing.is_default)
    if not is_default:
        is_default = not ScoringParserConfig.objects.filter(is_default=True).exclude(parser_key="cmp_single_module_v1").exists()
    ScoringParserConfig.objects.update_or_create(
        parser_key="cmp_single_module_v1",
        defaults={
            "display_name": "CMP 单模块评分表",
            "alias": "CMP v1",
            "description": "严格解析 CMP 官方单模块评分表模板，支持 M 测量评分点和 J 评价四档分档。",
            "is_enabled": True,
            "is_default": is_default,
            "order": 0,
        },
    )


class Migration(migrations.Migration):
    dependencies = [
        ("scoring", "0002_scoringaspect_calculation_row_scoringparserconfig_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_cmp_single_module_parser, migrations.RunPython.noop),
    ]
