# Generated by Django 6.0.6 on 2026-08-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0003_seed_cmp_single_module_parser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoringparticipant',
            options={'ordering': ['scheme', 'order', 'display_name', 'pk'], 'permissions': [('view_all_scoringparticipant', '查看全部参评对象')], 'verbose_name': '参评对象', 'verbose_name_plural': '参评对象'},
        ),
        migrations.AlterModelOptions(
            name='scoringresult',
            options={'ordering': ['participant', 'aspect__order', 'pk'], 'permissions': [('view_all_scoringresult', '查看全部评分结果')], 'verbose_name': '评分结果', 'verbose_name_plural': '评分结果'},
        ),
    ]
