# Generated by Django 6.0.5 on 2026-05-23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


LEGACY_TABLES = {
    'curriculum_competitiontype',
    'curriculum_project',
    'curriculum_standardmoduleset',
    'curriculum_moduleaxis',
    'curriculum_standardmodule',
    'curriculum_standardmoduleaxismap',
    'trainingcycles_trainingcycle',
}

TARGET_TABLES = {
    'competition_standards_competitiontype',
    'competition_standards_project',
    'competition_standards_standardmoduleset',
    'competition_standards_moduleaxis',
    'competition_standards_standardmodule',
    'competition_standards_standardmoduleaxismap',
    'competition_standards_trainingcycle',
}


def assert_no_uncut_legacy_tables(apps, schema_editor):
    connection = schema_editor.connection
    existing_tables = set(connection.introspection.table_names())
    existing_legacy_tables = sorted(existing_tables & LEGACY_TABLES)
    existing_target_tables = sorted(existing_tables & TARGET_TABLES)
    if not existing_legacy_tables and not existing_target_tables:
        return

    tables = ', '.join(existing_legacy_tables + existing_target_tables)
    raise RuntimeError(
        '检测到赛训标准体系旧表或目标表已存在，但 competition_standards.0001_initial 尚未记录。'
        '请先运行 uv run manage.py cutover_competition_standards --execute 完成数据切换；'
        f'当前检测到的数据表：{tables}'
    )


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(assert_no_uncut_legacy_tables, migrations.RunPython.noop),
        migrations.CreateModel(
            name='CompetitionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='用于标识竞赛的唯一代码，如WSC或WorldSkills', max_length=50, unique=True, verbose_name='赛事代码')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='赛事名称')),
                ('level', models.CharField(choices=[('international', '世界级'), ('national', '国家级'), ('provincial', '省级'), ('municipal', '市级'), ('district', '区级'), ('school', '校级'), ('class', '班级'), ('other', '其他')], default='international', help_text='竞赛的级别', max_length=20, verbose_name='级别')),
                ('weight', models.DecimalField(decimal_places=1, default=Decimal('7.0'), help_text='用于统计该竞赛所涉考点的重要性，数值越大表示该竞赛所涉考点越重要，取值范围0.0-7.0，原则上与竞赛级别对应。', max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('7.0'))], verbose_name='权重')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '赛事类型',
                'verbose_name_plural': '赛事类型',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='同一赛事类型下唯一，如ITNSA', max_length=50, verbose_name='赛项代码')),
                ('name', models.CharField(max_length=100, verbose_name='赛项名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('competition_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='competition_standards.competitiontype', verbose_name='所属赛事类型')),
            ],
            options={
                'verbose_name': '标准赛项',
                'verbose_name_plural': '标准赛项',
                'ordering': ['competition_type_id', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StandardModuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='同一标准赛项下唯一，用于标识某一版标准模块体系。', max_length=50, verbose_name='版本代码')),
                ('name', models.CharField(help_text='例如：2025 版、2026 版。', max_length=100, verbose_name='版本名称')),
                ('description', models.TextField(blank=True, verbose_name='版本说明')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='数值越小越靠前显示。', verbose_name='显示顺序')),
                ('is_current', models.BooleanField(default=False, help_text='同一标准赛项同一时刻只允许一套当前启用的标准模块版本。', verbose_name='当前启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_sets', to='competition_standards.project', verbose_name='所属标准赛项')),
            ],
            options={
                'verbose_name': '标准模块版本',
                'verbose_name_plural': '标准模块版本',
                'ordering': ['project', '-is_current', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='用于标识训练周期的唯一代码。', max_length=50, unique=True, verbose_name='周期代码')),
                ('name', models.CharField(max_length=100, verbose_name='周期名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.CharField(choices=[('planning', '筹备中'), ('active', '进行中'), ('completed', '已结束'), ('archived', '已归档')], default='planning', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('module_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_cycles', to='competition_standards.standardmoduleset', verbose_name='标准模块版本')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_cycles', to='competition_standards.project', verbose_name='标准赛项')),
            ],
            options={
                'verbose_name': '训练周期',
                'verbose_name_plural': '训练周期',
                'db_table': 'competition_standards_trainingcycle',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ModuleAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='同一标准赛项下唯一，用于标识能力主线。', max_length=50, verbose_name='主线代码')),
                ('name', models.CharField(max_length=100, verbose_name='主线名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='数值越小越靠前显示。', verbose_name='显示顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_axes', to='competition_standards.project', verbose_name='所属标准赛项')),
            ],
            options={
                'verbose_name': '能力主线',
                'verbose_name_plural': '能力主线',
                'ordering': ['project', 'sort_order', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StandardModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='模块编号')),
                ('name', models.CharField(max_length=100, verbose_name='模块名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('default_counts_towards_ranking', models.BooleanField(default=True, help_text='新建考核模块时默认继承此设置。', verbose_name='默认计入排名分')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='数值越小越靠前显示。', verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('module_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='competition_standards.standardmoduleset', verbose_name='所属标准模块版本')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='competition_standards.project', verbose_name='所属标准赛项')),
            ],
            options={
                'verbose_name': '标准模块',
                'verbose_name_plural': '标准模块',
                'ordering': ['project', 'module_set__sort_order', 'sort_order', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StandardModuleAxisMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='用于标识该标准模块当前主要归属的能力主线。', verbose_name='主映射')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='用于表示该标准模块映射到该能力主线时的相对权重。', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='权重')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_mappings', to='competition_standards.standardmodule', verbose_name='标准模块')),
                ('module_axis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_module_mappings', to='competition_standards.moduleaxis', verbose_name='能力主线')),
            ],
            options={
                'verbose_name': '标准模块能力主线映射',
                'verbose_name_plural': '标准模块能力主线映射',
                'ordering': ['module', '-is_primary', 'module_axis__sort_order', 'module_axis__code', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('competition_type', 'code'), name='unique_project_code_within_competition_type'),
        ),
        migrations.AddConstraint(
            model_name='standardmoduleset',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_module_set_code_within_project'),
        ),
        migrations.AddConstraint(
            model_name='standardmoduleset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('project',), name='unique_current_module_set_per_project'),
        ),
        migrations.AddConstraint(
            model_name='moduleaxis',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_module_axis_code_within_project'),
        ),
        migrations.AddConstraint(
            model_name='standardmodule',
            constraint=models.UniqueConstraint(fields=('module_set', 'code'), name='uniq_standardmodule_moduleset_code'),
        ),
        migrations.AddConstraint(
            model_name='standardmoduleaxismap',
            constraint=models.UniqueConstraint(fields=('module', 'module_axis'), name='uniq_standardmoduleaxis_module_axis'),
        ),
        migrations.AddConstraint(
            model_name='standardmoduleaxismap',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('module',), name='unique_primary_axis_mapping_per_standard_module'),
        ),
    ]
