# Generated by Django 5.1.6 on 2025-03-18 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_point', models.CharField(max_length=100, verbose_name='技能点')),
                ('exam_point', models.CharField(blank=True, max_length=500, verbose_name='考点')),
                ('detail_content', models.TextField(blank=True, verbose_name='详细内容')),
                ('score', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='分值')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition', verbose_name='所属竞赛')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.module', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
            },
        ),
    ]
