# Generated by Django 5.1.6 on 2025-03-18 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_remove_competitionteam_competition_and_more'),
        ('skills', '0003_skill_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='skill_point',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='detail_content',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='exam_point',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='module',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='score',
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
        migrations.CreateModel(
            name='ExamPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='考点')),
                ('detail_content', models.TextField(blank=True, null=True, verbose_name='详细内容')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='分值')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competition', verbose_name='所属竞赛')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.module', verbose_name='所属模块')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skill', verbose_name='技能点')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.topic', verbose_name='所属专题')),
            ],
            options={
                'verbose_name': '考点',
                'verbose_name_plural': '考点',
            },
        ),
    ]
