# Generated by Django 5.1.6 on 2025-03-18 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_rename_skill_point_skill_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exampoint',
            name='competition',
        ),
        migrations.RemoveField(
            model_name='exampoint',
            name='module',
        ),
        migrations.RemoveField(
            model_name='exampoint',
            name='topic',
        ),
    ]
