# Generated by Django 5.1.6 on 2025-03-26 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0007_alter_exampoint_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampoint',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=3, help_text='1-5, 1最简单，5最难', verbose_name='难度系数'),
        ),
    ]
