# Generated by Django 5.2.5 on 2025-08-30 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_alter_meeting_options_meeting_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='upload',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='特别注意：请填写会议的实际日期, 而非上传日期', verbose_name='会议日期'),
        ),
    ]
