# Generated by Django 5.2.5 on 2025-09-04 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_remove_meeting_filename'),
        ('meeting', '0003_rename_upload_meeting_file_alter_meeting_date'),
    ]

    operations = [
    ]
