# Generated by Django 5.2.5 on 2025-09-04 11:02

import django.utils.timezone
import meeting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_merge_20250904_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate, help_text='特别注意：请填写会议的实际日期, 而非上传日期', validators=[meeting.models.date_validator], verbose_name='会议日期'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='file',
            field=models.FileField(help_text='支持pdf格式, 文件大小不超过10MB', upload_to=meeting.models.meeting_file_upload_to, validators=[meeting.models.file_validator], verbose_name='会议记录文件'),
        ),
    ]
