# Generated by Django 6.0.5 on 2026-05-22 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_competitiontype_options_and_more'),
        ('traininglogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_logs', to='curriculum.standardmodule', verbose_name='标准模块'),
        ),
    ]
