# Generated by Django 6.0.1 on 2026-01-30 07:01

import core.utils.validators
import django.core.validators
import traininglogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='file',
            field=models.FileField(help_text='支持格式：pdf，文件大小不超过 100MB', upload_to=traininglogs.models.traininglog_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'], message='仅支持以下格式的文件：pdf'), core.utils.validators.validate_file_size], verbose_name='日志文件'),
        ),
    ]
