# Generated by Django 6.0 on 2026-01-07 02:12

import django.core.validators
import traininglogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='file',
            field=models.FileField(help_text='支持格式：doc, docx, pdf，文件大小不超过100MB', upload_to=traininglogs.models.traininglog_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'], message='仅支持以下格式的文件：doc, docx, pdf'), traininglogs.models.file_size_validator], verbose_name='日志文件'),
        ),
    ]
