# Generated by Django 6.0.1 on 2026-02-04 07:58

import core.utils.validators
import django.core.validators
import functools
import traininglogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglogs', '0002_alter_traininglog_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='file',
            field=models.FileField(help_text='支持格式：doc, docx, pdf，文件大小不超过 20MB', upload_to=traininglogs.models.traininglog_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'], message='仅支持以下格式的文件：doc, docx, pdf'), functools.partial(core.utils.validators.validate_file_size, max_size_mb=20)], verbose_name='日志文件'),
        ),
    ]
