# Generated by Django 6.0.5 on 2026-05-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition_standards', '0001_initial'),
        ('traininglogs', '0002_alter_traininglog_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='training_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_logs', to='competition_standards.trainingcycle', verbose_name='训练周期'),
        ),
    ]
