# Generated by Django 6.0.1 on 2026-04-17 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traininglogs', '0003_alter_traininglog_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traininglog',
            unique_together={('uploaded_by', 'training_date')},
        ),
    ]