# Generated by Django 6.0.4 on 2026-05-16 07:47

import core.uploads
import django.core.validators
import traininglogs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglogs', '0004_traininglog_unique_uploaded_by_training_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='file',
            field=models.FileField(help_text='上传训练日志文件，支持 doc, docx, pdf，大小不超过 20MB', upload_to=traininglogs.models.traininglog_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('doc', 'docx', 'pdf'), message='仅支持以下格式的文件：doc, docx, pdf'), core.uploads.UploadSizeValidator(20)], verbose_name='日志文件'),
        ),
    ]
