# Generated by Django 5.2 on 2025-05-15 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_alter_exampoint_difficulty'),
        ('traininglogs', '0004_alter_traininglog_training_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_logs', to='skills.module', verbose_name='训练模块'),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='task',
            field=models.CharField(max_length=20, verbose_name='训练任务'),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='upload',
            field=models.FileField(help_text='支持doc、docx、pdf格式, 文件大小不超过10MB', upload_to='training_logs/%Y/%m', verbose_name='日志文件'),
        ),
    ]
