# Generated by Django 5.2 on 2025-08-20 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglogs', '0005_alter_traininglog_module_alter_traininglog_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_logs', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
    ]
