# Generated by Django 5.2.5 on 2025-08-30 03:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglogs', '0006_alter_traininglog_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='training_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='*特别注意：请填写日志对应的实际训练日期，而非上传日期', verbose_name='训练日期'),
        ),
    ]
