# Generated by Django 5.2.5 on 2025-09-01 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_alter_exampoint_competition'),
        ('traininglogs', '0007_alter_traininglog_training_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='traininglog',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_logs', to='skills.module', verbose_name='训练模块'),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.PROTECT, related_name='training_logs', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
            preserve_default=False,
        ),
    ]
