# Generated by Django 5.2.5 on 2025-09-04 11:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import traininglogs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traininglogs', '0009_rename_upload_to_file_drop_filename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininglog',
            options={'ordering': ('-training_date', '-uploaded_at'), 'verbose_name': '训练日志', 'verbose_name_plural': '训练日志'},
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='file',
            field=models.FileField(help_text='支持格式：doc, docx, pdf，文件大小不超过10MB', upload_to=traininglogs.models.traininglog_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'], message='仅支持以下格式的文件：doc, docx, pdf'), traininglogs.models.file_size_validator], verbose_name='日志文件'),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='task',
            field=models.CharField(max_length=100, verbose_name='训练任务'),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='training_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='*特别注意：请填写日志对应的实际训练日期，而非上传日期', validators=[traininglogs.models.training_date_validator], verbose_name='训练日期'),
        ),
        migrations.AlterField(
            model_name='traininglog',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='training_logs', to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
    ]
