# Generated by Django 5.2.5 on 2025-09-08 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traininglogs', '0010_alter_traininglog_options_alter_traininglog_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininglog',
            options={'ordering': ('-training_date', '-uploaded_at'), 'permissions': [('view_all_traininglog', '查看所有训练日志'), ('view_coach_traininglog', '查看教练训练日志'), ('view_competitor_traininglog', '查看选手训练日志')], 'verbose_name': '训练日志', 'verbose_name_plural': '训练日志'},
        ),
    ]
