# Generated by Django 6.0 on 2025-12-10 03:30

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='用于标识竞赛的唯一代码，如WSC或WorldSkills', max_length=50, unique=True, verbose_name='竞赛代码')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='竞赛名称')),
                ('level', models.CharField(choices=[('international', '国际级'), ('national', '国家级'), ('provincial', '省级'), ('municipal', '市级'), ('district', '区级'), ('school', '校级'), ('class', '班级'), ('other', '其他')], default='international', help_text='竞赛的级别', max_length=20, verbose_name='级别')),
                ('weight', models.DecimalField(decimal_places=1, default=Decimal('7.0'), help_text='用于统计该竞赛所涉考点的重要性，数值越大表示该竞赛所涉考点越重要，取值范围0.0-7.0，原则上与竞赛级别对应。', max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('7.0'))], verbose_name='权重')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '竞赛',
                'verbose_name_plural': '竞赛',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='用于标识竞赛项目的唯一代码，如ITNSA', max_length=50, unique=True, verbose_name='竞赛项目代码')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='竞赛项目名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='competitions.competition', verbose_name='所属竞赛')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='competitions.project', verbose_name='所属竞赛项目')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
                'ordering': ['code'],
            },
        ),
    ]
