# Generated by Django 5.1.6 on 2025-03-18 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('start_date', models.DateField(help_text='比赛开始日期', verbose_name='开始日期')),
                ('end_date', models.DateField(help_text='比赛结束日期', verbose_name='结束日期')),
                ('location', models.CharField(help_text='比赛举办城市', max_length=100, verbose_name='地点')),
                ('gold', models.CharField(blank=True, help_text='获得金牌的国家或地区', max_length=100, verbose_name='金牌获得者')),
                ('silver', models.CharField(blank=True, help_text='获得银牌的国家或地区', max_length=100, verbose_name='银牌获得者')),
                ('bronze', models.CharField(blank=True, help_text='获得铜牌的国家或地区', max_length=100, verbose_name='铜牌获得者')),
                ('our_result', models.CharField(blank=True, help_text='我们选手的成绩, 填写" "金牌" "银牌" "铜牌" "优胜奖" "未获奖"，或名次，如"第一名"，或具体成绩，如"78.5分"', max_length=100, verbose_name='我们的选手成绩')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('our_competitor', models.ForeignKey(help_text='我们的参赛选手', on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to=settings.AUTH_USER_MODEL, verbose_name='我们的参赛选手')),
            ],
            options={
                'verbose_name': '竞赛',
                'verbose_name_plural': '竞赛',
            },
        ),
    ]
