# Generated by Django 6.0 on 2026-01-20 06:07

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='用于标识竞赛的唯一代码，如WSC或WorldSkills', max_length=50, unique=True, verbose_name='赛事代码')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='赛事名称')),
                ('level', models.CharField(choices=[('international', '国际级'), ('national', '国家级'), ('provincial', '省级'), ('municipal', '市级'), ('district', '区级'), ('school', '校级'), ('class', '班级'), ('other', '其他')], default='international', help_text='竞赛的级别', max_length=20, verbose_name='级别')),
                ('weight', models.DecimalField(decimal_places=1, default=Decimal('7.0'), help_text='用于统计该竞赛所涉考点的重要性，数值越大表示该竞赛所涉考点越重要，取值范围0.0-7.0，原则上与竞赛级别对应。', max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('7.0'))], verbose_name='权重')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '赛事类型',
                'verbose_name_plural': '赛事类型',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('code', models.CharField(help_text='ISO代码或缩写', max_length=20, unique=True, verbose_name='代码')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/', verbose_name='旗帜')),
            ],
            options={
                'verbose_name': '代表队',
                'verbose_name_plural': '代表队',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ['-start_date', 'name'], 'verbose_name': '具体赛事', 'verbose_name_plural': '具体赛事'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['project', 'code'], 'verbose_name': '模块', 'verbose_name_plural': '模块'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': '标准项目', 'verbose_name_plural': '标准项目'},
        ),
        migrations.RemoveField(
            model_name='competition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='level',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='project',
            name='competition',
        ),
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='结束日期'),
        ),
        migrations.AddField(
            model_name='competition',
            name='location',
            field=models.CharField(blank=True, max_length=100, verbose_name='举办地点'),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='code',
            field=models.CharField(help_text='具体赛事唯一编号，如：WSC2024', max_length=50, unique=True, verbose_name='赛事编号'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='name',
            field=models.CharField(help_text='具体赛事名称，如：第47届世界技能大赛', max_length=100, verbose_name='赛事名称'),
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=50, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='competitions.project', verbose_name='所属标准项目'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(help_text='用于标识竞赛项目的唯一代码，如ITNSA', max_length=50, unique=True, verbose_name='项目代码'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='项目名称'),
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('project', 'code')},
        ),
        migrations.CreateModel(
            name='CompetitionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='本届赛项描述')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_projects', to='competitions.competition', verbose_name='所属赛事')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_projects', to='competitions.project', verbose_name='标准项目')),
            ],
            options={
                'verbose_name': '具体赛项',
                'verbose_name_plural': '具体赛项',
                'ordering': ['competition', 'project'],
                'unique_together': {('competition', 'project')},
            },
        ),
        migrations.CreateModel(
            name='CompetitionModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='如不填则使用标准模块名称', max_length=100, verbose_name='本届模块名称')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_modules', to='competitions.module', verbose_name='标准模块')),
                ('competition_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_modules', to='competitions.competitionproject', verbose_name='所属具体赛项')),
            ],
            options={
                'verbose_name': '具体赛项模块',
                'verbose_name_plural': '具体赛项模块',
                'ordering': ['competition_project', 'module__code'],
                'unique_together': {('competition_project', 'module')},
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='competition_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='competitions.competitiontype', verbose_name='所属赛事类型'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='competition_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='competitions.competitiontype', verbose_name='所属赛事类型'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='选手姓名', max_length=100, verbose_name='姓名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('competition_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitors', to='competitions.competitionproject', verbose_name='参赛项目')),
                ('user', models.ForeignKey(blank=True, help_text='如果是校内选手，请关联用户账号；如果是外部选手，留空即可。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_profiles', to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competitors', to='competitions.member', verbose_name='代表队')),
            ],
            options={
                'verbose_name': '参赛选手',
                'verbose_name_plural': '参赛选手',
                'ordering': ['competition_project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_100', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='百分制成绩')),
                ('score_700', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='700分制成绩')),
                ('rank', models.PositiveIntegerField(blank=True, null=True, verbose_name='排名')),
                ('medal', models.CharField(choices=[('gold', '金牌'), ('silver', '银牌'), ('bronze', '铜牌'), ('first', '一等奖'), ('second', '二等奖'), ('third', '三等奖'), ('excellence', '优胜奖'), ('none', '无')], default='none', max_length=20, verbose_name='奖项')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='competitions.competitor', verbose_name='选手')),
            ],
            options={
                'verbose_name': '竞赛总成绩',
                'verbose_name_plural': '竞赛总成绩',
                'ordering': ['competitor__competition_project', 'rank', '-score_700'],
            },
        ),
        migrations.CreateModel(
            name='ModuleResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='通常为百分制或其他原始分', max_digits=5, verbose_name='模块得分')),
                ('competition_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='competitions.competitionmodule', verbose_name='具体模块')),
                ('competition_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_results', to='competitions.competitionresult', verbose_name='所属总成绩')),
            ],
            options={
                'verbose_name': '模块成绩',
                'verbose_name_plural': '模块成绩',
                'ordering': ['competition_module'],
                'unique_together': {('competition_result', 'competition_module')},
            },
        ),
    ]
