# Generated by Django 6.0.4 on 2026-05-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
        ('competition_standards', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competitionmodule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='competitionmoduleaxismap',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='competitionmodulestandardmodulemap',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='competitionproject',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='competitionmodule',
            constraint=models.UniqueConstraint(fields=('competition_project', 'code'), name='uniq_competitionmodule_competition_project_code'),
        ),
        migrations.AddConstraint(
            model_name='competitionmoduleaxismap',
            constraint=models.UniqueConstraint(fields=('competition_module', 'module_axis'), name='uniq_compmodule_axis'),
        ),
        migrations.AddConstraint(
            model_name='competitionmodulestandardmodulemap',
            constraint=models.UniqueConstraint(fields=('competition_module', 'module'), name='uniq_compmodule_standardmodule'),
        ),
        migrations.AddConstraint(
            model_name='competitionproject',
            constraint=models.UniqueConstraint(fields=('competition', 'project'), name='uniq_competitionproject_competition_project'),
        ),
    ]
