# Generated by Django 5.1.6 on 2025-03-18 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='bronze',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='description',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='gold',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='location',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='our_competitor',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='our_result',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='silver',
        ),
        migrations.RemoveField(
            model_name='competition',
            name='start_date',
        ),
        migrations.AddField(
            model_name='competition',
            name='level',
            field=models.CharField(choices=[('IN', '国际级'), ('NA', '国家级'), ('PR', '省级'), ('MU', '市级'), ('OT', '其他')], default='OT', max_length=2, verbose_name='级别'),
        ),
        migrations.CreateModel(
            name='CompetitionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='比赛开始日期', verbose_name='开始日期')),
                ('end_date', models.DateField(help_text='比赛结束日期', verbose_name='结束日期')),
                ('location', models.CharField(help_text='比赛举办城市', max_length=100, verbose_name='地点')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('competition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='competitions.competition', verbose_name='竞赛')),
            ],
        ),
    ]
