# Generated by Django 6.0 on 2026-01-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competitiontype_member_alter_competition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=1, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='competitor',
            name='organization',
            field=models.CharField(blank=True, help_text='具体所属学校或单位，区别于代表队', max_length=100, verbose_name='所属单位'),
        ),
    ]
