# Generated by Django 6.0 on 2025-12-09 01:03

from django.db import migrations


def create_default_competition_project_modules(apps, schema_editor):
    Competition = apps.get_model('competitions', 'Competition')
    Project = apps.get_model('competitions', 'Project')
    Module = apps.get_model('competitions', 'Module')
    
    wsc, _created = Competition.objects.get_or_create(
        code='WSC',
        name='WorldSkills Competition',
        level='international',
        description='WorldSkills Competition (WSC) is the world championship of skills, held every two years.'
    )

    itnsa, _created = Project.objects.get_or_create(
        competition=wsc,
        code='ITNSA',
        name='IT Network Systems Administration',
        description='The IT Network Systems Administration (ITNSA) project focuses on skills related to managing and maintaining IT network systems.'
    )


    modules = [
        ("A", "Linux", "Linux environment setup and administration."),
        ("B", "Windows", "Windows Server environment setup and administration."),
        ("C", "Network", "Network configuration and management."),
        ("D", "TroubleShooting", "Diagnosing and resolving IT issues."),
        ("E", "English", "English communication skills for IT professionals."),
    ]

    for code, name, description in modules:
        Module.objects.get_or_create(
            project=itnsa,
            code=code,
            name=name,
            description=description,
        )


def reverse_func(apps, schema_editor):
    Competition = apps.get_model('competitions', 'Competition')
    Project = apps.get_model('competitions', 'Project')
    Module = apps.get_model('competitions', 'Module')

    try:
        wsc = Competition.objects.get(code='WSC')
        itnsa = Project.objects.get(code='ITNSA', competition=wsc)
        
        Module.objects.filter(project=itnsa).delete()
        itnsa.delete()
        wsc.delete()
    except Competition.DoesNotExist:
        pass
    except Project.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_competition_weight'),
    ]

    operations = [
        migrations.RunPython(create_default_competition_project_modules, reverse_func),
    ]
