# Generated by Django 6.0.5 on 2026-05-22 02:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_competitionmodule_unique_together_and_more'),
        ('curriculum', '0005_alter_competitiontype_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionmodule',
            options={'ordering': ['competition_project', 'sort_order', 'code', 'pk'], 'verbose_name': '本届官方模块', 'verbose_name_plural': '本届官方模块'},
        ),
        migrations.AlterModelOptions(
            name='competitionproject',
            options={'ordering': ['competition', 'project'], 'verbose_name': '具体赛项', 'verbose_name_plural': '具体赛项'},
        ),
        migrations.AlterModelOptions(
            name='competitionmoduleaxismap',
            options={'ordering': ['competition_module', '-is_primary', 'module_axis__sort_order', 'module_axis__code', 'pk'], 'verbose_name': '官方模块能力主线映射', 'verbose_name_plural': '官方模块能力主线映射'},
        ),
        migrations.AlterField(
            model_name='competitionmodule',
            name='code',
            field=models.CharField(help_text='按该届官方模块原始编号填写。', max_length=50, verbose_name='官方模块编号'),
        ),
        migrations.AlterField(
            model_name='competitionmodule',
            name='description',
            field=models.TextField(blank=True, verbose_name='官方模块说明'),
        ),
        migrations.AlterField(
            model_name='competitionmodule',
            name='name',
            field=models.CharField(help_text='按该届官方模块原始名称填写。', max_length=100, verbose_name='官方模块名称'),
        ),
        migrations.AlterField(
            model_name='competitionmoduleaxismap',
            name='competition_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_mappings', to='competitions.competitionmodule', verbose_name='本届官方模块'),
        ),
        migrations.AlterField(
            model_name='competitionmoduleaxismap',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='用于标识该官方模块当前主要归属的能力主线。', verbose_name='主映射'),
        ),
        migrations.AlterField(
            model_name='competitionmoduleaxismap',
            name='module_axis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_module_mappings', to='curriculum.moduleaxis', verbose_name='能力主线'),
        ),
        migrations.AlterField(
            model_name='competitionmoduleaxismap',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='用于表示该官方模块映射到该能力主线时的相对权重。', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='competitionmodulestandardmodulemap',
            name='competition_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_mappings', to='competitions.competitionmodule', verbose_name='本届官方模块'),
        ),
        migrations.AlterField(
            model_name='competitionproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_projects', to='curriculum.project', verbose_name='标准赛项'),
        ),
    ]
