# Generated by Django 6.0 on 2026-01-20 06:37

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('competitions', '0003_competitor_gender_competitor_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitorUser',
            fields=[
            ],
            options={
                'verbose_name': '关联用户',
                'verbose_name_plural': '关联用户',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='competitionresult',
            options={'ordering': ['competitor__competition_project', 'rank', '-score_700'], 'verbose_name': '具体赛事总成绩', 'verbose_name_plural': '具体赛事总成绩'},
        ),
        migrations.AlterModelOptions(
            name='competitiontype',
            options={'ordering': ['level', 'name'], 'verbose_name': '竞赛类型', 'verbose_name_plural': '竞赛类型'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['name'], 'verbose_name': '参赛代表队', 'verbose_name_plural': '参赛代表队'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['project', 'code'], 'verbose_name': '竞赛模块', 'verbose_name_plural': '竞赛模块'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['name'], 'verbose_name': '竞赛项目', 'verbose_name_plural': '竞赛项目'},
        ),
        migrations.AlterField(
            model_name='module',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='competitions.project', verbose_name='所属竞赛项目'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='user',
            field=models.ForeignKey(blank=True, help_text='如果是校内选手，请关联用户账号；如果是外部选手，留空即可。', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitor_profiles', to='competitions.competitoruser', verbose_name='关联用户'),
        ),
    ]
