# Generated by Django 6.0.5 on 2026-05-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_alter_competitionmodule_options_and_more'),
        ('curriculum', '0006_trainingcycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionTrainingCycleTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('primary', '主目标赛项'), ('reference', '参考赛项')], max_length=20, verbose_name='关系类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('competition_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_cycle_targets', to='competitions.competitionproject', verbose_name='具体赛项')),
                ('training_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_targets', to='curriculum.trainingcycle', verbose_name='备赛周期')),
            ],
            options={
                'verbose_name': '备赛周期赛事目标',
                'verbose_name_plural': '备赛周期赛事目标',
                'ordering': ['training_cycle', 'kind', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('training_cycle', 'kind'), name='unique_training_cycle_target_kind')],
            },
        ),
    ]
