# Generated by Django 6.0 on 2026-01-20 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0004_competitoruser_alter_competitionresult_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionproject',
            options={'ordering': ['competition', 'project'], 'verbose_name': '具体赛事项目', 'verbose_name_plural': '具体赛事项目'},
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='所属单位')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('competition_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experts', to='competitions.competitionproject', verbose_name='所属赛项')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='experts', to='competitions.member', verbose_name='代表队')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_profiles', to='competitions.competitoruser', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '专家',
                'verbose_name_plural': '专家',
                'ordering': ['competition_project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('position_name', models.CharField(help_text='如：技能竞赛经理(Skill Competition Manager)、首席专家(Chief Expert)、场地经理(Workshop Manager)', max_length=100, verbose_name='岗位名称')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='所属单位')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('competition_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_positions', to='competitions.competitionproject', verbose_name='所属赛项')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_positions', to='competitions.competitoruser', verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '技能岗位人员',
                'verbose_name_plural': '技能岗位人员',
                'ordering': ['competition_project', 'position_name', 'name'],
            },
        ),
    ]
