# Generated by Django 6.0 on 2026-01-20 07:52

import competitions.models
import django.core.files.storage
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0005_alter_competitionproject_options_expert_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expert',
            options={'ordering': ['competition_project', 'name'], 'verbose_name': '参赛专家(裁判)', 'verbose_name_plural': '参赛专家(裁判)'},
        ),
        migrations.AlterModelOptions(
            name='skillposition',
            options={'ordering': ['competition_project', 'position_name', 'name'], 'verbose_name': '具体赛事技能岗位人员', 'verbose_name_plural': '具体赛事技能岗位人员'},
        ),
        migrations.AddField(
            model_name='competitionproject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competitionproject',
            name='document',
            field=models.FileField(blank=True, help_text='上传与该赛项相关的归档文件，支持格式：xls, xlsx, csv, pdf, doc, docx, jpg, jpeg, png, zip, 7z, gz, bz2, rar，文件大小不超过100MB', storage=django.core.files.storage.FileSystemStorage(location='D:\\04-01-Codes\\GitHub\\hdaojin\\tms\\media-private\\competitions'), upload_to=competitions.models.competition_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar'], message='仅支持以下格式的文件：xls, xlsx, csv, pdf, doc, docx, jpg, jpeg, png, zip, 7z, gz, bz2, rar'), competitions.models.validate_competition_file_size], verbose_name='赛项文件'),
        ),
        migrations.AddField(
            model_name='competitionproject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
    ]
