# Generated by Django 6.0 on 2026-01-20 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0006_alter_expert_options_alter_skillposition_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_projects', to='competitions.project', verbose_name='竞赛项目'),
        ),
    ]
