# Generated by Django 6.0 on 2026-01-20 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0007_alter_competitionproject_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition_modules', to='competitions.module', verbose_name='竞赛模块'),
        ),
    ]
