# Generated by Django 5.1.6 on 2025-03-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_competitionteamrelation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiondetail',
            name='description',
            field=models.TextField(blank=True, help_text='比赛的详细描述', null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='competitiondetail',
            name='end_date',
            field=models.DateField(blank=True, help_text='比赛结束日期', null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='competitiondetail',
            name='location',
            field=models.CharField(blank=True, help_text='比赛举办城市', max_length=100, null=True, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='competitiondetail',
            name='start_date',
            field=models.DateField(blank=True, help_text='比赛开始日期', null=True, verbose_name='开始日期'),
        ),
    ]
