# Generated by Django 6.0.1 on 2026-01-30 07:01

import competitions.models
import core.utils.validators
import django.core.files.storage
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_competitionproject_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionproject',
            name='document',
            field=models.FileField(blank=True, help_text='上传与该赛项相关的归档文件，支持格式：xls, xlsx, csv, pdf, doc, docx, jpg, jpeg, png, zip, 7z, gz, bz2, rar，文件大小不超过100MB', storage=django.core.files.storage.FileSystemStorage(location='D:\\04-01-Codes\\GitHub\\hdaojin\\tms\\media-private\\competitions'), upload_to=competitions.models.competition_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar'], message='仅支持以下格式的文件：xls, xlsx, csv, pdf, doc, docx, jpg, jpeg, png, zip, 7z, gz, bz2, rar'), core.utils.validators.validate_file_size], verbose_name='赛项文件'),
        ),
    ]
