# Generated by Django 5.2.5 on 2025-09-01 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_alter_competitiondetail_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='competionresult',
            name='bronze',
            field=models.ForeignKey(blank=True, default='', help_text='获得铜牌的参赛队', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competitions.competitionteam', verbose_name='获得铜牌的参赛队'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competionresult',
            name='competition',
            field=models.OneToOneField(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='result', to='competitions.competition', verbose_name='竞赛'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competionresult',
            name='gold',
            field=models.ForeignKey(blank=True, default='', help_text='获得金牌的参赛队', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competitions.competitionteam', verbose_name='获得金牌的参赛队'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competionresult',
            name='our_competitor',
            field=models.ForeignKey(blank=True, default='', help_text='我们的参赛选手', on_delete=django.db.models.deletion.PROTECT, related_name='competitions', to=settings.AUTH_USER_MODEL, verbose_name='我们的参赛选手'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competionresult',
            name='silver',
            field=models.ForeignKey(blank=True, default='', help_text='获得银牌的参赛队', on_delete=django.db.models.deletion.PROTECT, related_name='+', to='competitions.competitionteam', verbose_name='获得银牌的参赛队'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='competition',
            name='level',
            field=models.IntegerField(choices=[(None, '其他'), (0, '国际级'), (1, '国家级'), (2, '省级'), (3, '市级'), (4, '区级'), (5, '校级'), (6, '班级')], default=2, help_text='比赛的级别', verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='competitiondetail',
            name='description',
            field=models.TextField(blank=True, default='', help_text='比赛的详细描述', verbose_name='描述'),
            preserve_default=False,
        ),
    ]
