# Generated by Django 5.2.5 on 2025-09-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_alter_competionresult_bronze_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(unique=True, verbose_name='技能编号')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='技能名称')),
                ('description', models.TextField(blank=True, verbose_name='技能描述')),
            ],
            options={
                'verbose_name': '竞赛项目',
                'verbose_name_plural': '竞赛项目',
                'ordering': ['name'],
            },
        ),
    ]
