# Generated by Django 5.2.9 on 2025-12-03 05:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0012_skill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'ordering': ('-start_date', 'name', 'level'), 'verbose_name': '竞赛', 'verbose_name_plural': '竞赛'},
        ),
        migrations.AddField(
            model_name='competition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, help_text='比赛的详细描述', verbose_name='描述'),
        ),
        migrations.AddField(
            model_name='competition',
            name='end_date',
            field=models.DateField(blank=True, help_text='比赛结束日期', null=True, verbose_name='结束日期'),
        ),
        migrations.AddField(
            model_name='competition',
            name='is_team_event',
            field=models.BooleanField(default=False, help_text='是否为团体赛', verbose_name='团体赛'),
        ),
        migrations.AddField(
            model_name='competition',
            name='location',
            field=models.CharField(blank=True, help_text='比赛举办城市', max_length=100, null=True, verbose_name='地点'),
        ),
        migrations.AddField(
            model_name='competition',
            name='organizer',
            field=models.CharField(blank=True, help_text='比赛的主办单位', max_length=200, null=True, verbose_name='主办单位'),
        ),
        migrations.AddField(
            model_name='competition',
            name='start_date',
            field=models.DateField(blank=True, help_text='比赛开始日期', null=True, verbose_name='开始日期'),
        ),
        migrations.AddField(
            model_name='competition',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='最后更新时间'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='level',
            field=models.CharField(choices=[('international', '国际级'), ('national', '国家级'), ('provincial', '省级'), ('municipal', '市级'), ('district', '区级'), ('school', '校级'), ('other', '其他')], default='provincial', help_text='比赛的级别', max_length=20, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='weight',
            field=models.DecimalField(decimal_places=1, help_text='用于统计该比赛所涉考点的重要性，数值越大表示该比赛所涉考点越重要, 取值范围0.0-6.0, 原则上与比赛级别对应。', max_digits=6, verbose_name='权重'),
        ),
    ]
