# Generated by Django 5.2.9 on 2025-12-04 00:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0013_remove_competionresult_bronze_and_more'),
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('start_date', models.DateField(help_text='考核开始日期', null=True, verbose_name='开始日期')),
                ('end_date', models.DateField(help_text='考核结束日期', null=True, verbose_name='结束日期')),
                ('location', models.CharField(blank=True, help_text='考核地点', max_length=100, null=True, verbose_name='地点')),
                ('organizer', models.CharField(blank=True, help_text='考核的组织单位', max_length=200, null=True, verbose_name='组织单位')),
                ('description', models.TextField(blank=True, help_text='考核的详细描述', verbose_name='描述')),
                ('is_team_event', models.BooleanField(default=False, help_text='是否为团体考核', verbose_name='团体考核')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '考核',
                'verbose_name_plural': '考核',
                'ordering': ('-start_date', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=25, verbose_name='分值')),
                ('remarks', models.TextField(blank=True, help_text='对该成绩的备注说明', null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='competitions.examination', verbose_name='考核')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_scores', to='skills.module', verbose_name='模块')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to=settings.AUTH_USER_MODEL, verbose_name='姓名')),
            ],
            options={
                'verbose_name': '考核成绩',
                'verbose_name_plural': '考核成绩',
                'ordering': ('-examination__start_date', 'user__username', 'model__code'),
            },
        ),
        # 删除对旧模型和字段的破坏性操作，保留新增 Examination/ExamScore 以及 Competition 字段调整
        migrations.AlterField(
            model_name='competition',
            name='end_date',
            field=models.DateField(help_text='比赛结束日期', null=True, verbose_name='结束日期'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='level',
            field=models.CharField(choices=[('international', '国际级'), ('national', '国家级'), ('provincial', '省级'), ('municipal', '市级'), ('district', '区级'), ('school', '校级'), ('class', '班级'), ('other', '其他')], default='international', help_text='比赛的级别', max_length=20, verbose_name='级别'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='location',
            field=models.CharField(help_text='比赛举办城市', max_length=100, null=True, verbose_name='地点'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='organizer',
            field=models.CharField(help_text='比赛的主办单位', max_length=200, null=True, verbose_name='主办单位'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='start_date',
            field=models.DateField(help_text='比赛开始日期', null=True, verbose_name='开始日期'),
        ),
        migrations.AlterField(
            model_name='competition',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=7.0, help_text='用于统计该比赛所涉考点的性，数值越大表示该比赛所涉考点越重要, 取值范围0.0-7.0, 原则上与比赛级别对应。', max_digits=7.0, verbose_name='权重'),
        ),
        # 保留历史模型不在此迁移中删除，避免对现有数据库造成破坏
        migrations.AddConstraint(
            model_name='examscore',
            constraint=models.UniqueConstraint(fields=('examination', 'model', 'user'), name='unique_exam_score'),
        ),
    ]
