# Generated by Django 5.2.9 on 2025-12-04 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0014_examination_examscore_remove_competionresult_bronze_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competition',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=7.0, help_text='用于统计该比赛所涉考点的重要性，数值越大表示该比赛所涉考点越重要，取值范围0.0-7.0，原则上与比赛级别对应。', max_digits=7, verbose_name='权重'),
        ),
    ]
