# Generated by Django 6.0.4 on 2026-04-21 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0015_archive_integrity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionmodule',
            name='module',
        ),
        migrations.AlterField(
            model_name='competitionmodule',
            name='code',
            field=models.CharField(help_text='按该届官方模块原始编号填写。', max_length=50, verbose_name='本届模块编号'),
        ),
        migrations.AlterField(
            model_name='competitionmodule',
            name='name',
            field=models.CharField(help_text='按该届官方模块原始名称填写。', max_length=100, verbose_name='本届模块名称'),
        ),
        migrations.AddConstraint(
            model_name='competitionmodulemapping',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('competition_module',), name='unique_primary_mapping_per_competition_module'),
        ),
    ]
