# Generated by Django 6.0.4 on 2026-04-22 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_member_level_and_competition_scope'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModuleResult',
        ),
    ]
