# Generated by Django 5.2.9 on 2025-12-04 01:32

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0017_remove_competionresult_bronze_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examscore',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, help_text='该模块成绩的分值，取值范围0.00-25.00', max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('25.00'))], verbose_name='分值'),
        ),
    ]
