# Generated by Django 6.0.4 on 2026-04-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_delete_moduleresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionresult',
            options={'ordering': ['competitor__competition_project', 'rank', '-score_700'], 'verbose_name': '具体赛事最终归档结果', 'verbose_name_plural': '具体赛事最终归档结果'},
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='medal',
            field=models.CharField(choices=[('gold', '金牌'), ('silver', '银牌'), ('bronze', '铜牌'), ('first', '一等奖'), ('second', '二等奖'), ('third', '三等奖'), ('excellence', '优胜奖'), ('none', '无')], default='none', help_text='按官方最终奖项填写；未获奖则保留“无”。', max_length=20, verbose_name='最终奖项'),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='rank',
            field=models.PositiveIntegerField(blank=True, help_text='按官方最终名次填写；如未公布可留空。', null=True, verbose_name='最终排名'),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='score_100',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='用于归档官方最终公布的百分制成绩；如无可留空。', max_digits=5, null=True, verbose_name='归档百分制成绩'),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='score_700',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='用于归档官方最终公布的 700 分制成绩；如无可留空。', max_digits=6, null=True, verbose_name='归档700分制成绩'),
        ),
    ]
