# Generated by GitHub Copilot on 2025-12-04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0018_remove_competionresult_bronze_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "DROP TABLE IF EXISTS \"competitions_competitionteamrelation\";"
                "DROP TABLE IF EXISTS \"competitions_competitionteam\";"
                "DROP TABLE IF EXISTS \"competitions_competitiondetail\";"
                "DROP TABLE IF EXISTS \"competitions_competionresult\";"
            ),
            reverse_sql=(
                # 不自动重建这些表；重构后不需要它们
                ""
            ),
        ),
    ]
