# Generated by Django 6.0.4 on 2026-04-22 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0020_competitionperson_project_global_and_assignment_refactor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitionresult',
            options={'ordering': ['competitor__competition_project', 'rank', '-score_700'], 'verbose_name': '具体赛事总成绩', 'verbose_name_plural': '具体赛事总成绩'},
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='medal',
            field=models.CharField(choices=[('gold', '金牌'), ('silver', '银牌'), ('bronze', '铜牌'), ('first', '一等奖'), ('second', '二等奖'), ('third', '三等奖'), ('excellence', '优胜奖'), ('none', '无')], default='none', max_length=20, verbose_name='奖项'),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='排名'),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='score_100',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='百分制成绩'),
        ),
        migrations.AlterField(
            model_name='competitionresult',
            name='score_700',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='700分制成绩'),
        ),
    ]
