# Generated by Django 6.0.4 on 2026-04-22 10:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0023_assessmentmodule_material_lock_fields'),
        ('competitions', '0022_competitor_person_refactor'),
        ('skills', '0006_finalize_exam_point_scope_and_skills'),
        ('traininglogs', '0004_traininglog_unique_uploaded_by_training_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompetitionModuleMapping',
            new_name='CompetitionModuleStandardModuleMap',
        ),
        migrations.RenameModel(
            old_name='ModuleSet',
            new_name='StandardModuleSet',
        ),
        migrations.AlterModelOptions(
            name='competitionmodulestandardmodulemap',
            options={'ordering': ['competition_module', '-is_primary', 'module__sort_order', 'module__code', 'pk'], 'verbose_name': '官方模块标准映射', 'verbose_name_plural': '官方模块标准映射'},
        ),
        migrations.AlterField(
            model_name='competition',
            name='code',
            field=models.CharField(help_text='具体赛事唯一编号，如：47WSC2024', max_length=50, unique=True, verbose_name='赛事编号'),
        ),
        migrations.CreateModel(
            name='ModuleAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='同一项目下唯一，用于标识能力主线。', max_length=50, verbose_name='主线代码')),
                ('name', models.CharField(max_length=100, verbose_name='主线名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='数值越小越靠前显示。', verbose_name='显示顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_axes', to='competitions.project', verbose_name='所属竞赛项目')),
            ],
            options={
                'verbose_name': '模块主线',
                'verbose_name_plural': '模块主线',
                'ordering': ['project', 'sort_order', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompetitionModuleAxisMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='用于标识该官方模块当前主要归属的模块主线。', verbose_name='主映射')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='用于表示该官方模块映射到该模块主线时的相对权重。', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='权重')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('competition_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_mappings', to='competitions.competitionmodule', verbose_name='具体赛项模块')),
                ('module_axis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='competition_module_mappings', to='competitions.moduleaxis', verbose_name='模块主线')),
            ],
            options={
                'verbose_name': '官方模块主线映射',
                'verbose_name_plural': '官方模块主线映射',
                'ordering': ['competition_module', '-is_primary', 'module_axis__sort_order', 'module_axis__code', 'pk'],
            },
        ),
        migrations.RenameModel(
            old_name='Module',
            new_name='StandardModule',
        ),
        migrations.AlterModelOptions(
            name='standardmodule',
            options={'ordering': ['project', 'module_set__sort_order', 'sort_order', 'code', 'name'], 'verbose_name': '标准模块', 'verbose_name_plural': '标准模块'},
        ),
        migrations.CreateModel(
            name='StandardModuleAxisMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='用于标识该标准模块当前主要归属的模块主线。', verbose_name='主映射')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='用于表示该标准模块映射到该模块主线时的相对权重。', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='权重')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_mappings', to='competitions.standardmodule', verbose_name='标准模块')),
                ('module_axis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_module_mappings', to='competitions.moduleaxis', verbose_name='模块主线')),
            ],
            options={
                'verbose_name': '标准模块主线映射',
                'verbose_name_plural': '标准模块主线映射',
                'ordering': ['module', '-is_primary', 'module_axis__sort_order', 'module_axis__code', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='moduleaxis',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_module_axis_code_within_project'),
        ),
        migrations.AddConstraint(
            model_name='competitionmoduleaxismap',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('competition_module',), name='unique_primary_axis_mapping_per_competition_module'),
        ),
        migrations.AlterUniqueTogether(
            name='competitionmoduleaxismap',
            unique_together={('competition_module', 'module_axis')},
        ),
        migrations.AddConstraint(
            model_name='standardmoduleaxismap',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('module',), name='unique_primary_axis_mapping_per_standard_module'),
        ),
        migrations.AlterUniqueTogether(
            name='standardmoduleaxismap',
            unique_together={('module', 'module_axis')},
        ),
    ]
