# Generated by Django 6.0.4 on 2026-04-27 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0023_rename_competitionmodulemapping_competitionmodulestandardmodulemap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述'),
        ),
    ]