# Generated by Django 6.0.4 on 2026-04-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0024_competition_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitiontype',
            name='level',
            field=models.CharField(choices=[('international', '世界级'), ('national', '国家级'), ('provincial', '省级'), ('municipal', '市级'), ('district', '区级'), ('school', '校级'), ('class', '班级'), ('other', '其他')], default='international', help_text='竞赛的级别', max_length=20, verbose_name='级别'),
        ),
    ]
