# Generated by Django 6.0.4 on 2026-05-16 07:47

import competitions.models
import core.uploads
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0027_competitor_unique_person_per_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitionproject',
            name='document',
            field=models.FileField(blank=True, help_text='上传与该赛项相关的归档文件，支持 xls, xlsx, csv, pdf, doc, docx, jpg, jpeg, png, zip, 7z, gz, bz2, rar, tar，大小不超过 100MB', storage=core.uploads.PrivateMediaStorage('competitions'), upload_to=competitions.models.competition_document_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('xls', 'xlsx', 'csv', 'pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png', 'zip', '7z', 'gz', 'bz2', 'rar', 'tar'), message='仅支持以下格式的文件：xls, xlsx, csv, pdf, doc, docx, jpg, jpeg, png, zip, 7z, gz, bz2, rar, tar'), core.uploads.UploadSizeValidator(100)], verbose_name='赛项文件'),
        ),
    ]
