# Generated by Django 6.0.4 on 2026-05-18 08:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0001_initial'),
        ('competition_standards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='技能点')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'ordering': ['topic', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='数值越小越靠前显示。', verbose_name='显示顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['group', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TagGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='标识')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='数值越小越靠前显示。', verbose_name='显示顺序')),
            ],
            options={
                'verbose_name': '标签分组',
                'verbose_name_plural': '标签分组',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='必填；同一竞赛下名称唯一。', max_length=500, verbose_name='考点')),
                ('detail_content', models.TextField(blank=True, null=True, verbose_name='详细内容')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, help_text='1-5，1 最简单，5 最难', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='难度系数')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='分值')),
                ('competition_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_points', to='competitions.competitionproject', verbose_name='所属具体赛项')),
            ],
            options={
                'verbose_name': '考点',
                'verbose_name_plural': '考点',
                'ordering': ['competition_project', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamPointSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='用于标识该考点的主要能力点。', verbose_name='主技能')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='用于表示该技能点在综合考点中的相对权重。', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='权重')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('exam_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_point_skills', to='skills.exampoint', verbose_name='考点')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_point_skills', to='skills.skill', verbose_name='技能点')),
            ],
            options={
                'verbose_name': '考点技能关联',
                'verbose_name_plural': '考点技能关联',
                'ordering': ['exam_point', '-is_primary', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='exampoint',
            name='skills',
            field=models.ManyToManyField(related_name='exam_points', through='skills.ExamPointSkill', to='skills.skill', verbose_name='技能点'),
        ),
        migrations.AddField(
            model_name='exampoint',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='exam_points', to='skills.tag', verbose_name='标签'),
        ),
        migrations.AddField(
            model_name='tag',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='skills.taggroup', verbose_name='所属分组'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='competition_standards.standardmodule', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '专题',
                'verbose_name_plural': '专题',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.topic', verbose_name='所属专题'),
        ),
        migrations.AddConstraint(
            model_name='exampointskill',
            constraint=models.UniqueConstraint(fields=('exam_point', 'skill'), name='unique_exam_point_skill'),
        ),
        migrations.AddIndex(
            model_name='exampoint',
            index=models.Index(fields=['name', 'difficulty'], name='index_exam_point'),
        ),
        migrations.AddConstraint(
            model_name='exampoint',
            constraint=models.UniqueConstraint(fields=('competition_project', 'name'), name='unique_exam_point_within_project'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='unique_tag_name_within_group'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='unique_topic'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('topic', 'name'), name='unique_skill'),
        ),
    ]
