# Generated by Django 5.2.5 on 2025-10-11 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('competitions', '0012_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='编号')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
            ],
            options={
                'verbose_name': '模块',
                'verbose_name_plural': '模块',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='skills.module', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '专题',
                'verbose_name_plural': '专题',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='技能点')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.topic', verbose_name='所属专题')),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'ordering': ['topic', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ExamPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='考点')),
                ('detail_content', models.TextField(blank=True, null=True, verbose_name='详细内容')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, help_text='1-5, 1最简单，5最难', verbose_name='难度系数')),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='分值')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_points', to='competitions.competition', verbose_name='所属竞赛')),
                ('skill', models.ManyToManyField(related_name='exam_points', to='skills.skill', verbose_name='技能点')),
            ],
            options={
                'verbose_name': '考点',
                'verbose_name_plural': '考点',
                'ordering': ['competition', 'name'],
                'indexes': [models.Index(fields=['name', 'difficulty'], name='index_exam_point')],
                'constraints': [models.UniqueConstraint(fields=('competition', 'name'), name='unique_exam_point')],
            },
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='unique_topic'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('topic', 'name'), name='unique_skill'),
        ),
    ]
