# Generated by Django 5.1.6 on 2025-03-18 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='detail_content',
            field=models.TextField(blank=True, null=True, verbose_name='详细内容'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='分值'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.module', verbose_name='所属模块')),
            ],
            options={
                'verbose_name': '专题',
                'verbose_name_plural': '专题',
            },
        ),
    ]
