# Generated by Django 5.1.6 on 2025-03-18 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_skill_detail_content_alter_skill_score_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='topic',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='skills.topic', verbose_name='所属专题'),
            preserve_default=False,
        ),
    ]
