# Generated by Django 5.1.6 on 2025-03-21 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0009_alter_competitionteamrelation_unique_together_and_more'),
        ('skills', '0005_remove_exampoint_competition_remove_exampoint_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='competitions.competition', verbose_name='所属竞赛'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='module',
            constraint=models.UniqueConstraint(fields=('competition', 'code'), name='unique_module_code'),
        ),
    ]
