# Generated by Django 5.1.6 on 2025-03-21 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0010_alter_competitiondetail_description_and_more'),
        ('skills', '0006_module_competition_module_unique_module_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exampoint',
            options={'ordering': ['competition', 'name'], 'verbose_name': '考点', 'verbose_name_plural': '考点'},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['code'], 'verbose_name': '模块', 'verbose_name_plural': '模块'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['topic', 'name'], 'verbose_name': '技能', 'verbose_name_plural': '技能'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['module', 'name'], 'verbose_name': '专题', 'verbose_name_plural': '专题'},
        ),
        migrations.RemoveConstraint(
            model_name='module',
            name='unique_module_code',
        ),
        migrations.RemoveField(
            model_name='module',
            name='competition',
        ),
        migrations.AddField(
            model_name='exampoint',
            name='competition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='competitions.competition', verbose_name='所属竞赛'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exampoint',
            name='difficulty',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='难度系数'),
        ),
        migrations.RemoveField(
            model_name='exampoint',
            name='skill',
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.topic', verbose_name='所属专题'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='skills.module', verbose_name='所属模块'),
        ),
        migrations.AddIndex(
            model_name='exampoint',
            index=models.Index(fields=['name', 'difficulty'], name='index_exam_point'),
        ),
        migrations.AddConstraint(
            model_name='exampoint',
            constraint=models.UniqueConstraint(fields=('competition', 'name'), name='unique_exam_point'),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('topic', 'name'), name='unique_skill'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('module', 'name'), name='unique_topic'),
        ),
        migrations.AddField(
            model_name='exampoint',
            name='skill',
            field=models.ManyToManyField(related_name='exam_points', to='skills.skill', verbose_name='技能点'),
        ),
    ]
