# Generated by Django 5.2.5 on 2025-09-01 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0011_alter_competionresult_bronze_and_more'),
        ('skills', '0008_alter_exampoint_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampoint',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_points', to='competitions.competition', verbose_name='所属竞赛'),
        ),
    ]
