# Generated by Django 6.0.4 on 2026-05-18 08:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='用于标识竞赛的唯一代码，如WSC或WorldSkills', max_length=50, unique=True, verbose_name='赛事代码')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='赛事名称')),
                ('level', models.CharField(choices=[('international', '世界级'), ('national', '国家级'), ('provincial', '省级'), ('municipal', '市级'), ('district', '区级'), ('school', '校级'), ('class', '班级'), ('other', '其他')], default='international', help_text='竞赛的级别', max_length=20, verbose_name='级别')),
                ('weight', models.DecimalField(decimal_places=1, default=Decimal('7.0'), help_text='用于统计该竞赛所涉考点的重要性，数值越大表示该竞赛所涉考点越重要，取值范围0.0-7.0，原则上与竞赛级别对应。', max_digits=2, validators=[django.core.validators.MinValueValidator(Decimal('0.0')), django.core.validators.MaxValueValidator(Decimal('7.0'))], verbose_name='权重')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '竞赛类型',
                'verbose_name_plural': '竞赛类型',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='同一竞赛类型下唯一，如ITNSA', max_length=50, verbose_name='项目代码')),
                ('name', models.CharField(max_length=100, verbose_name='项目名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('competition_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='curriculum.competitiontype', verbose_name='所属竞赛类型')),
            ],
            options={
                'verbose_name': '竞赛项目',
                'verbose_name_plural': '竞赛项目',
                'ordering': ['competition_type', 'name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ModuleAxis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='同一项目下唯一，用于标识能力主线。', max_length=50, verbose_name='主线代码')),
                ('name', models.CharField(max_length=100, verbose_name='主线名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='数值越小越靠前显示。', verbose_name='显示顺序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_axes', to='curriculum.project', verbose_name='所属竞赛项目')),
            ],
            options={
                'verbose_name': '模块主线',
                'verbose_name_plural': '模块主线',
                'ordering': ['project', 'sort_order', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StandardModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='编号')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='数值越小越靠前显示。', verbose_name='显示顺序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='curriculum.project', verbose_name='所属竞赛项目')),
            ],
            options={
                'verbose_name': '标准模块',
                'verbose_name_plural': '标准模块',
                'ordering': ['project', 'module_set__sort_order', 'sort_order', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StandardModuleAxisMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text='用于标识该标准模块当前主要归属的模块主线。', verbose_name='主映射')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='用于表示该标准模块映射到该模块主线时的相对权重。', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='权重')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='axis_mappings', to='curriculum.standardmodule', verbose_name='标准模块')),
                ('module_axis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_module_mappings', to='curriculum.moduleaxis', verbose_name='模块主线')),
            ],
            options={
                'verbose_name': '标准模块主线映射',
                'verbose_name_plural': '标准模块主线映射',
                'ordering': ['module', '-is_primary', 'module_axis__sort_order', 'module_axis__code', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='StandardModuleSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='同一项目下唯一，用于标识某一版标准模块集。', max_length=50, verbose_name='模块集代码')),
                ('name', models.CharField(help_text='例如：2025 版标准模块、2026 版标准模块。', max_length=100, verbose_name='模块集名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='数值越小越靠前显示。', verbose_name='显示顺序')),
                ('is_current', models.BooleanField(default=False, help_text='同一项目同一时刻只允许一套当前启用的标准模块集。', verbose_name='当前启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_sets', to='curriculum.project', verbose_name='所属竞赛项目')),
            ],
            options={
                'verbose_name': '标准模块集',
                'verbose_name_plural': '标准模块集',
                'ordering': ['project', '-is_current', 'sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='standardmodule',
            name='module_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='curriculum.standardmoduleset', verbose_name='所属标准模块集'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('competition_type', 'code'), name='unique_project_code_within_competition_type'),
        ),
        migrations.AddConstraint(
            model_name='moduleaxis',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_module_axis_code_within_project'),
        ),
        migrations.AddConstraint(
            model_name='standardmoduleaxismap',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('module',), name='unique_primary_axis_mapping_per_standard_module'),
        ),
        migrations.AlterUniqueTogether(
            name='standardmoduleaxismap',
            unique_together={('module', 'module_axis')},
        ),
        migrations.AddConstraint(
            model_name='standardmoduleset',
            constraint=models.UniqueConstraint(fields=('project', 'code'), name='unique_module_set_code_within_project'),
        ),
        migrations.AddConstraint(
            model_name='standardmoduleset',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('project',), name='unique_current_module_set_per_project'),
        ),
        migrations.AlterUniqueTogether(
            name='standardmodule',
            unique_together={('module_set', 'code')},
        ),
    ]
