# Generated by Django 6.0.4 on 2026-05-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_standardmodule_default_counts_towards_ranking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='standardmodule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='standardmoduleaxismap',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='standardmodule',
            constraint=models.UniqueConstraint(fields=('module_set', 'code'), name='uniq_standardmodule_moduleset_code'),
        ),
        migrations.AddConstraint(
            model_name='standardmoduleaxismap',
            constraint=models.UniqueConstraint(fields=('module', 'module_axis'), name='uniq_standardmoduleaxis_module_axis'),
        ),
    ]
