# Generated by Django 6.0.5 on 2026-05-22 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0003_alter_standardmodule_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['competition_type_id', 'name', 'code'], 'verbose_name': '竞赛项目', 'verbose_name_plural': '竞赛项目'},
        ),
    ]
