# Generated by Django 6.0.5 on 2026-05-22 02:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_alter_project_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitiontype',
            options={'ordering': ['level', 'name'], 'verbose_name': '赛事类型', 'verbose_name_plural': '赛事类型'},
        ),
        migrations.AlterModelOptions(
            name='moduleaxis',
            options={'ordering': ['project', 'sort_order', 'code', 'name'], 'verbose_name': '能力主线', 'verbose_name_plural': '能力主线'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['competition_type_id', 'name', 'code'], 'verbose_name': '标准赛项', 'verbose_name_plural': '标准赛项'},
        ),
        migrations.AlterModelOptions(
            name='standardmoduleaxismap',
            options={'ordering': ['module', '-is_primary', 'module_axis__sort_order', 'module_axis__code', 'pk'], 'verbose_name': '标准模块能力主线映射', 'verbose_name_plural': '标准模块能力主线映射'},
        ),
        migrations.AlterModelOptions(
            name='standardmoduleset',
            options={'ordering': ['project', '-is_current', 'sort_order', 'name'], 'verbose_name': '标准模块版本', 'verbose_name_plural': '标准模块版本'},
        ),
        migrations.AlterField(
            model_name='moduleaxis',
            name='code',
            field=models.CharField(help_text='同一标准赛项下唯一，用于标识能力主线。', max_length=50, verbose_name='主线代码'),
        ),
        migrations.AlterField(
            model_name='moduleaxis',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_axes', to='curriculum.project', verbose_name='所属标准赛项'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(help_text='同一赛事类型下唯一，如ITNSA', max_length=50, verbose_name='赛项代码'),
        ),
        migrations.AlterField(
            model_name='project',
            name='competition_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='curriculum.competitiontype', verbose_name='所属赛事类型'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='赛项名称'),
        ),
        migrations.AlterField(
            model_name='standardmodule',
            name='code',
            field=models.CharField(max_length=50, verbose_name='模块编号'),
        ),
        migrations.AlterField(
            model_name='standardmodule',
            name='module_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modules', to='curriculum.standardmoduleset', verbose_name='所属标准模块版本'),
        ),
        migrations.AlterField(
            model_name='standardmodule',
            name='name',
            field=models.CharField(max_length=100, verbose_name='模块名称'),
        ),
        migrations.AlterField(
            model_name='standardmodule',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='curriculum.project', verbose_name='所属标准赛项'),
        ),
        migrations.AlterField(
            model_name='standardmoduleaxismap',
            name='is_primary',
            field=models.BooleanField(default=False, help_text='用于标识该标准模块当前主要归属的能力主线。', verbose_name='主映射'),
        ),
        migrations.AlterField(
            model_name='standardmoduleaxismap',
            name='module_axis',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_module_mappings', to='curriculum.moduleaxis', verbose_name='能力主线'),
        ),
        migrations.AlterField(
            model_name='standardmoduleaxismap',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='用于表示该标准模块映射到该能力主线时的相对权重。', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='权重'),
        ),
        migrations.AlterField(
            model_name='standardmoduleset',
            name='code',
            field=models.CharField(help_text='同一标准赛项下唯一，用于标识某一版标准模块体系。', max_length=50, verbose_name='版本代码'),
        ),
        migrations.AlterField(
            model_name='standardmoduleset',
            name='description',
            field=models.TextField(blank=True, verbose_name='版本说明'),
        ),
        migrations.AlterField(
            model_name='standardmoduleset',
            name='is_current',
            field=models.BooleanField(default=False, help_text='同一标准赛项同一时刻只允许一套当前启用的标准模块版本。', verbose_name='当前启用'),
        ),
        migrations.AlterField(
            model_name='standardmoduleset',
            name='name',
            field=models.CharField(help_text='例如：2025 版、2026 版。', max_length=100, verbose_name='版本名称'),
        ),
        migrations.AlterField(
            model_name='standardmoduleset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_sets', to='curriculum.project', verbose_name='所属标准赛项'),
        ),
    ]
