# Generated by Django 6.0.5 on 2026-05-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_alter_competitiontype_options_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='TrainingCycle',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('code', models.CharField(help_text='用于标识备赛周期的唯一代码。', max_length=50, unique=True, verbose_name='周期代码')),
                        ('name', models.CharField(max_length=100, verbose_name='周期名称')),
                        ('start_date', models.DateField(verbose_name='开始日期')),
                        ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                        ('status', models.CharField(choices=[('planning', '筹备中'), ('active', '进行中'), ('completed', '已结束'), ('archived', '已归档')], default='planning', max_length=20, verbose_name='状态')),
                        ('description', models.TextField(blank=True, verbose_name='描述')),
                        ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                        ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                        ('module_set', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_cycles', to='curriculum.standardmoduleset', verbose_name='标准模块版本')),
                        ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_cycles', to='curriculum.project', verbose_name='标准赛项')),
                    ],
                    options={
                        'verbose_name': '备赛周期',
                        'verbose_name_plural': '备赛周期',
                        'db_table': 'trainingcycles_trainingcycle',
                        'ordering': ['-start_date', 'name'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
