# Generated by Django 6.0.6 on 2026-08-18 02:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        ('scoring', '0001_initial'),
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'source_type',
                    models.CharField(
                        choices=[
                            ('scoring_aspect', '评分点'),
                            ('test_project', '试题'),
                            ('marking_standard', '评分标准'),
                            ('script_check', '评分脚本检查项'),
                            ('cmp_result_item', 'CMP 结果项'),
                            ('manual', '人工补充'),
                            ('other', '其他'),
                        ],
                        max_length=30,
                        verbose_name='来源类型',
                    ),
                ),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('original_text', models.TextField(blank=True, verbose_name='原始文本')),
                ('normalized_text', models.TextField(blank=True, verbose_name='规范文本')),
                ('source_location', models.CharField(blank=True, max_length=200, verbose_name='来源位置')),
                (
                    'estimated_mark',
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='估计分值',
                    ),
                ),
                (
                    'estimated_difficulty',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name='难度估计',
                    ),
                ),
                ('evidence_level', models.CharField(blank=True, max_length=50, verbose_name='证据等级')),
                (
                    'extraction_source',
                    models.CharField(
                        choices=[
                            ('manual', '人工'),
                            ('parser', '解析器'),
                            ('ai', 'AI'),
                            ('cmp', 'CMP'),
                            ('imported', '导入'),
                        ],
                        default='manual',
                        max_length=20,
                        verbose_name='提取来源',
                    ),
                ),
                (
                    'confidence',
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name='置信度',
                    ),
                ),
                (
                    'review_status',
                    models.CharField(
                        choices=[
                            ('draft', '草稿'),
                            ('pending', '待审核'),
                            ('approved', '已批准'),
                            ('rejected', '已拒绝'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='审核状态',
                    ),
                ),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_note', models.TextField(blank=True, verbose_name='审核备注')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'assessment_module',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='evidences',
                        to='assessments.assessmentmodule',
                        verbose_name='评测模块',
                    ),
                ),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_evidences',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='创建人',
                    ),
                ),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reviewed_evidences',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='审核人',
                    ),
                ),
                (
                    'scoring_aspect',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='knowledge_evidence',
                        to='scoring.scoringaspect',
                        verbose_name='来源评分点',
                    ),
                ),
                (
                    'skill_project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='knowledge_evidences',
                        to='standards.skillproject',
                        verbose_name='技能项目',
                    ),
                ),
                (
                    'source_document',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='evidences',
                        to='assessments.assessmentdocument',
                        verbose_name='来源资料',
                    ),
                ),
            ],
            options={
                'verbose_name': '考点证据',
                'verbose_name_plural': '考点证据',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceSkillMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, verbose_name='主技能')),
                (
                    'weight',
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal('1.0000'),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal('0.0001')),
                            django.core.validators.MaxValueValidator(Decimal('1.0000')),
                        ],
                        verbose_name='权重',
                    ),
                ),
                (
                    'mapping_source',
                    models.CharField(
                        choices=[('manual', '人工'), ('ai', 'AI'), ('imported', '导入'), ('parser', '解析器')],
                        default='manual',
                        max_length=20,
                        verbose_name='映射来源',
                    ),
                ),
                (
                    'confidence',
                    models.FloatField(
                        default=1.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                        verbose_name='置信度',
                    ),
                ),
                ('reason', models.TextField(blank=True, verbose_name='理由')),
                (
                    'review_status',
                    models.CharField(
                        choices=[
                            ('draft', '草稿'),
                            ('pending', '待审核'),
                            ('approved', '已批准'),
                            ('rejected', '已拒绝'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='审核状态',
                    ),
                ),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'reviewed_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='reviewed_evidence_skill_mappings',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='审核人',
                    ),
                ),
                (
                    'skill',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='evidence_mappings',
                        to='standards.skill',
                        verbose_name='技能',
                    ),
                ),
                (
                    'evidence',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='skill_mappings',
                        to='evidence.knowledgeevidence',
                        verbose_name='考点证据',
                    ),
                ),
            ],
            options={
                'verbose_name': '考点技能映射',
                'verbose_name_plural': '考点技能映射',
                'ordering': ['evidence', '-is_primary', 'skill__order', 'pk'],
                'constraints': [
                    models.UniqueConstraint(fields=('evidence', 'skill'), name='uniq_evidence_skill'),
                    models.UniqueConstraint(
                        condition=models.Q(('is_primary', True)),
                        fields=('evidence',),
                        name='uniq_primary_skill_per_evidence',
                    ),
                ],
            },
        ),
    ]
