# Generated by Django 5.2.5 on 2025-09-01 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('flatpages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="用于标识菜单的唯一标识符，如 'main', 'user', 'sidebar' 等", unique=True, verbose_name='菜单标识')),
                ('name', models.CharField(help_text='菜单的显示名称', max_length=100, verbose_name='菜单名称')),
                ('description', models.TextField(blank=True, help_text='对菜单的简要描述', verbose_name='菜单描述')),
                ('locations', models.JSONField(blank=True, default=list, help_text='菜单显示的位置，可多选', verbose_name='显示位置')),
                ('is_active', models.BooleanField(default=True, help_text='是否启用此菜单', verbose_name='启用')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='菜单项的显示名称', max_length=100, verbose_name='菜单项名称')),
                ('icon', models.CharField(blank=True, help_text="菜单项的图标类名，如 'icon-[tabler--home]'", max_length=100, verbose_name='图标')),
                ('order', models.PositiveIntegerField(default=0, help_text='菜单项的显示顺序，数字越小越靠前', verbose_name='排序')),
                ('is_visible', models.BooleanField(default=True, help_text='是否在菜单中显示此项', verbose_name='可见')),
                ('start_at', models.DateTimeField(blank=True, help_text='菜单项显示的开始时间，留空表示立即开始', null=True, verbose_name='开始时间')),
                ('end_at', models.DateTimeField(blank=True, help_text='菜单项显示的结束时间，留空表示无限期', null=True, verbose_name='结束时间')),
                ('required_perms', models.JSONField(blank=True, default=list, help_text="访问此菜单项所需的权限列表['app_label.permission_codename'], 如 ['is_authenticated', 'meeting.view_meeting']，留空表示不限制", verbose_name='所需权限')),
                ('url_name', models.CharField(blank=True, help_text="Django 命名路由名称，如 'home', 'meeting:list' 等", max_length=200, verbose_name='命名路由')),
                ('url_kwargs', models.JSONField(blank=True, default=dict, help_text="命名路由的参数，如 {'pk': 1}，留空表示无参数", verbose_name='路由参数')),
                ('url_query', models.JSONField(blank=True, default=dict, help_text="命名路由的查询参数，如 {'tab': 'files'}，留空表示无查询参数", verbose_name='路由查询参数')),
                ('external_url', models.URLField(blank=True, help_text="外部链接地址，如 'https://example.com'", max_length=500, verbose_name='外部链接')),
                ('object_id', models.PositiveIntegerField(blank=True, help_text='内容对象的主键ID', null=True, verbose_name='对象ID')),
                ('target_blank', models.BooleanField(default=False, help_text='是否在新标签页中打开链接', verbose_name='新标签页打开')),
                ('css_classes', models.CharField(blank=True, help_text="菜单项的自定义CSS类名，如 'text-primary font-bold'", max_length=200, verbose_name='CSS类')),
                ('htmx_attrs', models.JSONField(blank=True, default=dict, help_text="菜单项的HTMX属性，如 {'hx-get': '/some/url/'}，留空表示无HTMX属性", verbose_name='HTMX属性')),
                ('content_type', models.ForeignKey(blank=True, help_text='选择一个内容类型', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='内容类型')),
                ('flatpage', models.ForeignKey(blank=True, help_text='选择一个 FlatPage 页面', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flatpages.flatpage', verbose_name='FlatPage 页面')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='navigation.menu', verbose_name='所属菜单')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.menuitem', verbose_name='上级菜单项')),
            ],
            options={
                'verbose_name': '菜单项',
                'verbose_name_plural': '菜单项',
                'ordering': ['menu', 'parent__id', 'order', 'id'],
            },
        ),
    ]
