# Generated by Django 5.2.5 on 2025-09-01 06:26

import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': '菜单组', 'verbose_name_plural': '菜单组'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('main', '主菜单'), ('user', '用户菜单'), ('sidebar', '侧边栏菜单'), ('footer', '页脚菜单'), ('custom', '自定义位置')], default='main', help_text='菜单显示的位置，可多选', max_length=200, verbose_name='显示位置'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True, help_text='内容对象的主键ID', verbose_name='对象ID'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='navigation.menuitem', verbose_name='上级菜单项'),
        ),
    ]
