# Generated by Django 5.2.5 on 2025-09-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_alter_menu_options_alter_menu_locations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='url_name',
            new_name='named_url',
        ),
    ]
