# Generated by Django 5.2.5 on 2025-09-01 10:50

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0003_rename_url_name_menuitem_named_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['parent__id', 'order', 'id'], 'verbose_name': '菜单项', 'verbose_name_plural': '菜单项'},
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='menu',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='menus',
            field=models.ManyToManyField(help_text='此菜单项可以同时属于多个菜单组', related_name='items', to='navigation.menu', verbose_name='所属菜单组'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(blank=True, help_text='对菜单的简要描述', verbose_name='菜单组描述'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('header', '顶部菜单'), ('user', '用户菜单'), ('sidebar', '侧边栏菜单'), ('footer', '页脚菜单'), ('custom', '自定义位置')], default='header', help_text='菜单显示的位置，可多选', max_length=200, verbose_name='显示位置'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='name',
            field=models.CharField(help_text='菜单的显示名称', max_length=100, verbose_name='菜单组名称'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(help_text="用于标识菜单的唯一标识符，如 'main', 'user', 'meeting' 等", unique=True, verbose_name='菜单组标识'),
        ),
    ]
