# Generated by Django 5.2.5 on 2025-09-02 06:01

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0004_alter_menuitem_options_remove_menuitem_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='menu',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('header', '顶部菜单'), ('sidebar', '侧边栏菜单'), ('follow', '跟随应用'), ('footer', '页脚菜单'), ('custom', '自定义位置')], default='sidebar', help_text='菜单显示的位置，可多选', max_length=200, verbose_name='显示位置'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='required_perms',
            field=models.JSONField(blank=True, default=list, help_text='访问此菜单项所需的权限列表。支持特殊权限："is_authenticated"(已登录)、"is_staff"(管理员)、"is_superuser"(超级用户)，以及标准权限如"app_label.permission_codename"。例：["is_authenticated", "meeting.view_meeting"]表示需要登录且有查看会议权限的用户才能访问此菜单项，留空表示不限制', verbose_name='所需权限'),
        ),
    ]
