# Generated by Django 5.2.5 on 2025-09-03 00:12

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0005_remove_menuitem_content_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='locations',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('header', '顶部菜单'), ('sidebar', '侧边栏菜单'), ('follow', '跟随应用'), ('footer', '页脚菜单'), ('custom', '自定义位置')], default='header', help_text='菜单显示的位置，可多选', max_length=200, verbose_name='显示位置'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='css_classes',
            field=models.CharField(blank=True, help_text='菜单项的自定义CSS类名，如 "text-primary font-bold"', max_length=200, verbose_name='CSS类'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='htmx_attrs',
            field=models.JSONField(blank=True, default=dict, help_text='菜单项的HTMX属性，如 {"hx-get": "/some/url/"}，留空表示无HTMX属性', verbose_name='HTMX属性'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, help_text='菜单项的图标类名，如 icon-[tabler--home]', max_length=100, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, help_text='从已发现的命名URL列表中选择；留空表示不使用命名路由', max_length=200, verbose_name='命名路由'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url_kwargs',
            field=models.JSONField(blank=True, default=dict, help_text='命名路由的参数，如 {"pk": 1}，留空表示无参数', verbose_name='路由参数'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url_query',
            field=models.JSONField(blank=True, default=dict, help_text='命名路由的查询参数，如 {"tab": "files"}，留空表示无查询参数', verbose_name='路由查询参数'),
        ),
    ]
