# Generated by Django 5.2.5 on 2025-09-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0006_alter_menu_locations_alter_menuitem_css_classes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='login_required',
            field=models.BooleanField(default=True, help_text='是否仅对已登录用户显示此菜单项', verbose_name='登录可见'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='perm_match_all',
            field=models.BooleanField(default=True, help_text='是否需要匹配所有所需权限（选中）或任意一个权限（未选中）才能访问此菜单项', verbose_name='权限匹配方式'),
        ),
    ]
