# Generated by Django 5.2.5 on 2025-09-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('navigation', '0007_menuitem_login_required_menuitem_perm_match_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_group_header',
            field=models.BooleanField(default=False, verbose_name='仅分组标题（无链接）'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='css_classes',
            field=models.CharField(blank=True, help_text='如 "text-primary font-bold"', max_length=200, verbose_name='CSS类'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='htmx_attrs',
            field=models.JSONField(blank=True, default=dict, help_text='如 {"hx-get": "/some/url/"}', verbose_name='HTMX属性'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='login_required',
            field=models.BooleanField(default=True, help_text='仅对已登录用户显示此菜单项', verbose_name='登录可见'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='perm_match_all',
            field=models.BooleanField(default=True, help_text='选中=需满足全部；未选中=满足任一即可', verbose_name='权限匹配方式'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='required_perms',
            field=models.JSONField(blank=True, default=list, help_text='标准权限列表，如 ["meeting.view_meeting"]；留空表示不限制', verbose_name='所需权限'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='target_blank',
            field=models.BooleanField(default=False, verbose_name='新标签页打开'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url_kwargs',
            field=models.JSONField(blank=True, default=dict, help_text='命名路由的参数，如 {"pk": 1}', verbose_name='路由参数'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='url_query',
            field=models.JSONField(blank=True, default=dict, help_text='例如 {"tab": "files"}', verbose_name='路由查询参数'),
        ),
        migrations.AddIndex(
            model_name='menuitem',
            index=models.Index(fields=['parent', 'order', 'id'], name='navigation__parent__ccf4ea_idx'),
        ),
    ]
