# Generated by Django 5.2.5 on 2025-09-03 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpages', '0001_initial'),
        ('navigation', '0010_remove_menuitem_required_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='flatpage',
            field=models.ForeignKey(blank=True, help_text='选择一个简单页面', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flatpages.flatpage', verbose_name='简单页面'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='icon',
            field=models.CharField(blank=True, help_text='菜单项的图标类名，如 icon-[tabler--home], 图标类名参考https://icon-sets.iconify.design/tabler/', max_length=100, verbose_name='图标'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='perm_match_all',
            field=models.BooleanField(default=True, help_text='选中=需满足全部；未选中=满足任一即可', verbose_name='权限需全部满足'),
        ),
    ]
