# Generated by Django 6.0.6 on 2026-08-18 02:49

import core.uploads
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import training.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('assigned', '已分配'),
                            ('in_progress', '进行中'),
                            ('completed', '已完成'),
                            ('partially_completed', '部分完成'),
                            ('blocked', '受阻'),
                            ('cancelled', '已取消'),
                        ],
                        default='assigned',
                        max_length=30,
                        verbose_name='状态',
                    ),
                ),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='分配时间')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                (
                    'actual_minutes',
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name='实际用时（分钟）',
                    ),
                ),
                ('completion_note', models.TextField(blank=True, verbose_name='完成情况')),
                ('problems', models.TextField(blank=True, verbose_name='遇到的问题')),
                ('problem_resolved', models.BooleanField(blank=True, null=True, verbose_name='问题已解决')),
                ('solution', models.TextField(blank=True, verbose_name='解决方法')),
                ('reflection', models.TextField(blank=True, verbose_name='个人总结')),
                ('coach_feedback', models.TextField(blank=True, verbose_name='教练反馈')),
                ('feedback_at', models.DateTimeField(blank=True, null=True, verbose_name='反馈时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'feedback_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='task_execution_feedbacks',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='反馈教练',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='task_executions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='选手',
                    ),
                ),
            ],
            options={
                'verbose_name': '训练任务执行',
                'verbose_name_plural': '训练任务执行',
                'ordering': ['training_task__planned_date', 'user'],
            },
        ),
        migrations.CreateModel(
            name='TaskExecutionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='标题')),
                (
                    'file',
                    models.FileField(
                        storage=core.uploads.PrivateMediaStorage('training'),
                        upload_to=training.models.training_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=(
                                    'pdf',
                                    'doc',
                                    'docx',
                                    'xls',
                                    'xlsx',
                                    'ppt',
                                    'pptx',
                                    'zip',
                                    'gz',
                                    'bz2',
                                    'rar',
                                    '7z',
                                    'json',
                                    'txt',
                                    'csv',
                                    'png',
                                    'jpg',
                                    'jpeg',
                                ),
                                message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, ppt, pptx, zip, gz, bz2, rar, 7z, json, txt, csv, png, jpg, jpeg',
                            ),
                            core.uploads.UploadSizeValidator(100),
                            core.uploads.UploadSignatureValidator(),
                        ],
                        verbose_name='文件',
                    ),
                ),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                (
                    'task_execution',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attachments',
                        to='training.taskexecution',
                        verbose_name='任务执行',
                    ),
                ),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='uploaded_execution_attachments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='上传者',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TrainingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='周期代码')),
                ('name', models.CharField(max_length=120, verbose_name='周期名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('planning', '筹备中'),
                            ('active', '进行中'),
                            ('completed', '已完成'),
                            ('archived', '已归档'),
                        ],
                        default='planning',
                        max_length=20,
                        verbose_name='状态',
                    ),
                ),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='stages',
                        to='training.trainingcycle',
                        verbose_name='父周期',
                    ),
                ),
                (
                    'skill_project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='training_cycles',
                        to='standards.skillproject',
                        verbose_name='技能项目',
                    ),
                ),
                (
                    'skill_tree_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='training_cycles',
                        to='standards.skilltreeversion',
                        verbose_name='技能树版本',
                    ),
                ),
            ],
            options={
                'verbose_name': '训练周期',
                'verbose_name_plural': '训练周期',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='训练日期')),
                ('topic', models.CharField(max_length=150, verbose_name='训练主题')),
                ('summary', models.TextField(blank=True, verbose_name='训练摘要')),
                (
                    'document',
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=core.uploads.PrivateMediaStorage('training'),
                        upload_to=training.models.training_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=('doc', 'docx', 'pdf', 'txt', 'md'),
                                message='仅支持以下格式的文件：doc, docx, pdf, txt, md',
                            ),
                            core.uploads.UploadSizeValidator(20),
                            core.uploads.UploadSignatureValidator(),
                        ],
                        verbose_name='正式训练日志',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'author',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='training_logs',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='作者',
                    ),
                ),
                (
                    'training_cycle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='training_logs',
                        to='training.trainingcycle',
                        verbose_name='训练周期',
                    ),
                ),
            ],
            options={
                'verbose_name': '训练日志',
                'verbose_name_plural': '训练日志',
                'ordering': ['-training_date', '-created_at'],
                'permissions': [
                    ('view_all_traininglog', '查看全部训练日志'),
                    ('change_all_traininglog', '修改全部训练日志'),
                    ('view_traininglog_statistics', '查看训练日志统计'),
                    ('export_traininglog_archive', '导出训练日志归档'),
                ],
            },
        ),
        migrations.CreateModel(
            name='TrainingLogExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                (
                    'task_execution',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='log_links',
                        to='training.taskexecution',
                        verbose_name='任务执行',
                    ),
                ),
                (
                    'training_log',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='execution_links',
                        to='training.traininglog',
                        verbose_name='训练日志',
                    ),
                ),
            ],
            options={
                'verbose_name': '训练日志执行关联',
                'verbose_name_plural': '训练日志执行关联',
                'ordering': ['training_log', 'order'],
            },
        ),
        migrations.AddField(
            model_name='traininglog',
            name='executions',
            field=models.ManyToManyField(
                related_name='training_logs', through='training.TrainingLogExecution', to='training.taskexecution'
            ),
        ),
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180, verbose_name='计划标题')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('objective', models.TextField(verbose_name='训练目标')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('draft', '草稿'),
                            ('published', '已发布'),
                            ('completed', '已完成'),
                            ('archived', '已归档'),
                        ],
                        default='draft',
                        max_length=20,
                        verbose_name='状态',
                    ),
                ),
                (
                    'source_file',
                    models.FileField(
                        blank=True,
                        null=True,
                        storage=core.uploads.PrivateMediaStorage('training'),
                        upload_to=training.models.training_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=(
                                    'pdf',
                                    'doc',
                                    'docx',
                                    'xls',
                                    'xlsx',
                                    'ppt',
                                    'pptx',
                                    'zip',
                                    'gz',
                                    'bz2',
                                    'rar',
                                    '7z',
                                    'json',
                                    'txt',
                                    'csv',
                                    'png',
                                    'jpg',
                                    'jpeg',
                                ),
                                message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, ppt, pptx, zip, gz, bz2, rar, 7z, json, txt, csv, png, jpg, jpeg',
                            ),
                            core.uploads.UploadSizeValidator(100),
                            core.uploads.UploadSignatureValidator(),
                        ],
                        verbose_name='原始计划文件',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='created_training_plans',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='创建人',
                    ),
                ),
                (
                    'training_cycle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='plans',
                        to='training.trainingcycle',
                        verbose_name='训练周期',
                    ),
                ),
            ],
            options={
                'verbose_name': '训练计划',
                'verbose_name_plural': '训练计划',
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TrainingTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField(verbose_name='计划日期')),
                ('title', models.CharField(max_length=180, verbose_name='任务标题')),
                ('description', models.TextField(blank=True, verbose_name='任务描述')),
                ('requirements', models.TextField(verbose_name='训练要求')),
                (
                    'estimated_minutes',
                    models.PositiveIntegerField(blank=True, null=True, verbose_name='预计用时（分钟）'),
                ),
                (
                    'priority',
                    models.CharField(
                        choices=[('low', '低'), ('normal', '普通'), ('high', '高'), ('urgent', '紧急')],
                        default='normal',
                        max_length=20,
                        verbose_name='优先级',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[('draft', '草稿'), ('published', '已发布'), ('cancelled', '已取消')],
                        default='draft',
                        max_length=20,
                        verbose_name='状态',
                    ),
                ),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'created_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='created_training_tasks',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='创建人',
                    ),
                ),
                (
                    'training_plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='tasks',
                        to='training.trainingplan',
                        verbose_name='训练计划',
                    ),
                ),
            ],
            options={
                'verbose_name': '训练任务',
                'verbose_name_plural': '训练任务',
                'ordering': ['planned_date', 'order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='taskexecution',
            name='training_task',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='executions',
                to='training.trainingtask',
                verbose_name='训练任务',
            ),
        ),
        migrations.CreateModel(
            name='TrainingTaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='标题')),
                (
                    'file',
                    models.FileField(
                        storage=core.uploads.PrivateMediaStorage('training'),
                        upload_to=training.models.training_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=(
                                    'pdf',
                                    'doc',
                                    'docx',
                                    'xls',
                                    'xlsx',
                                    'ppt',
                                    'pptx',
                                    'zip',
                                    'gz',
                                    'bz2',
                                    'rar',
                                    '7z',
                                    'json',
                                    'txt',
                                    'csv',
                                    'png',
                                    'jpg',
                                    'jpeg',
                                ),
                                message='仅支持以下格式的文件：pdf, doc, docx, xls, xlsx, ppt, pptx, zip, gz, bz2, rar, 7z, json, txt, csv, png, jpg, jpeg',
                            ),
                            core.uploads.UploadSizeValidator(100),
                            core.uploads.UploadSignatureValidator(),
                        ],
                        verbose_name='文件',
                    ),
                ),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                (
                    'training_task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='attachments',
                        to='training.trainingtask',
                        verbose_name='训练任务',
                    ),
                ),
                (
                    'uploaded_by',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='uploaded_training_task_attachments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='上传者',
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='TrainingTaskCoach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'role',
                    models.CharField(
                        choices=[('primary', '主教练'), ('collaborator', '协作教练')],
                        default='collaborator',
                        max_length=20,
                        verbose_name='角色',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                (
                    'training_task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='coach_links',
                        to='training.trainingtask',
                        verbose_name='训练任务',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='training_task_assignments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='教练',
                    ),
                ),
            ],
            options={
                'verbose_name': '训练任务教练',
                'verbose_name_plural': '训练任务教练',
            },
        ),
        migrations.CreateModel(
            name='TrainingTaskDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'role',
                    models.CharField(
                        choices=[('primary', '主要领域'), ('related', '关联领域')],
                        default='related',
                        max_length=20,
                        verbose_name='角色',
                    ),
                ),
                (
                    'technical_domain',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='training_task_links',
                        to='standards.technicaldomain',
                        verbose_name='技术领域',
                    ),
                ),
                (
                    'training_task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='domain_links',
                        to='training.trainingtask',
                        verbose_name='训练任务',
                    ),
                ),
            ],
            options={
                'verbose_name': '训练任务技术领域',
                'verbose_name_plural': '训练任务技术领域',
            },
        ),
        migrations.CreateModel(
            name='TrainingTaskSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'role',
                    models.CharField(
                        choices=[('primary', '主要技能'), ('related', '关联技能')],
                        default='related',
                        max_length=20,
                        verbose_name='角色',
                    ),
                ),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                (
                    'skill',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='training_task_links',
                        to='standards.skill',
                        verbose_name='技能',
                    ),
                ),
                (
                    'training_task',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='skill_links',
                        to='training.trainingtask',
                        verbose_name='训练任务',
                    ),
                ),
            ],
            options={
                'verbose_name': '训练任务技能',
                'verbose_name_plural': '训练任务技能',
                'ordering': ['training_task', 'role', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCycleMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'role',
                    models.CharField(
                        choices=[('competitor', '选手'), ('coach', '教练')], max_length=20, verbose_name='角色'
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                (
                    'training_cycle',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='members',
                        to='training.trainingcycle',
                        verbose_name='训练周期',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='training_cycle_memberships',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='用户',
                    ),
                ),
            ],
            options={
                'verbose_name': '训练周期成员',
                'verbose_name_plural': '训练周期成员',
                'constraints': [
                    models.UniqueConstraint(fields=('training_cycle', 'user'), name='uniq_trainingcycle_member')
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='traininglogexecution',
            constraint=models.UniqueConstraint(
                fields=('training_log', 'task_execution'), name='uniq_traininglog_execution'
            ),
        ),
        migrations.AddConstraint(
            model_name='traininglog',
            constraint=models.UniqueConstraint(
                fields=('training_cycle', 'author', 'training_date'), name='uniq_traininglog_cycle_author_date'
            ),
        ),
        migrations.AddConstraint(
            model_name='taskexecution',
            constraint=models.UniqueConstraint(
                fields=('training_task', 'user'), name='uniq_trainingtask_execution_user'
            ),
        ),
        migrations.AddConstraint(
            model_name='trainingtaskcoach',
            constraint=models.UniqueConstraint(fields=('training_task', 'user'), name='uniq_trainingtask_coach'),
        ),
        migrations.AddConstraint(
            model_name='trainingtaskcoach',
            constraint=models.UniqueConstraint(
                condition=models.Q(('role', 'primary')),
                fields=('training_task',),
                name='uniq_primary_coach_per_trainingtask',
            ),
        ),
        migrations.AddConstraint(
            model_name='trainingtaskdomain',
            constraint=models.UniqueConstraint(
                fields=('training_task', 'technical_domain'), name='uniq_trainingtask_domain'
            ),
        ),
        migrations.AddConstraint(
            model_name='trainingtaskdomain',
            constraint=models.UniqueConstraint(
                condition=models.Q(('role', 'primary')),
                fields=('training_task',),
                name='uniq_primary_domain_per_trainingtask',
            ),
        ),
        migrations.AddConstraint(
            model_name='trainingtaskskill',
            constraint=models.UniqueConstraint(fields=('training_task', 'skill'), name='uniq_trainingtask_skill'),
        ),
    ]
