# Generated by Django 6.0.6 on 2026-06-17 10:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='周期代码')),
                ('name', models.CharField(max_length=120, verbose_name='周期名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='结束日期')),
                ('status', models.CharField(choices=[('planning', '筹备中'), ('active', '进行中'), ('completed', '已结束'), ('archived', '已归档')], default='planning', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('skill_project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_cycles', to='standards.skillproject', verbose_name='技能项目')),
            ],
            options={
                'verbose_name': '训练周期',
                'verbose_name_plural': '训练周期',
                'ordering': ['-start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='训练日期')),
                ('topic', models.CharField(max_length=150, verbose_name='训练主题')),
                ('summary', models.TextField(blank=True, verbose_name='训练摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('capability_domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_logs', to='standards.capabilitydomain', verbose_name='能力领域')),
                ('training_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_logs', to='training.trainingcycle', verbose_name='训练周期')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='training_logs', to=settings.AUTH_USER_MODEL, verbose_name='上传者')),
            ],
            options={
                'verbose_name': '训练日志',
                'verbose_name_plural': '训练日志',
                'ordering': ['-training_date', '-created_at'],
                'permissions': [('view_all_traininglog', '查看全部训练日志'), ('view_coach_traininglog', '查看教练训练日志'), ('view_competitor_traininglog', '查看选手训练日志'), ('export_traininglog_archive', '导出训练日志归档')],
                'constraints': [models.UniqueConstraint(fields=('training_cycle', 'uploaded_by', 'training_date'), name='uniq_traininglog_cycle_user_date')],
            },
        ),
    ]
