# Generated by Django 6.0.6 on 2026-08-14 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traininglog',
            options={'ordering': ['-training_date', '-created_at'], 'permissions': [('view_all_traininglog', '查看全部训练日志'), ('change_all_traininglog', '修改全部训练日志'), ('view_traininglog_statistics', '查看训练日志统计'), ('export_traininglog_archive', '导出训练日志归档')], 'verbose_name': '训练日志', 'verbose_name_plural': '训练日志'},
        ),
    ]
