# Generated by Django 6.0.6 on 2026-06-17 10:52

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_retire_legacy_standard_stack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='技能项目代码')),
                ('name', models.CharField(max_length=150, verbose_name='技能项目名称')),
                ('short_name', models.CharField(blank=True, max_length=80, verbose_name='简称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '技能项目',
                'verbose_name_plural': '技能项目',
                'ordering': ['order', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CapabilityDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='领域代码')),
                ('name', models.CharField(max_length=120, verbose_name='领域名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('skill_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_domains', to='standards.skillproject', verbose_name='技能项目')),
            ],
            options={
                'verbose_name': '能力领域',
                'verbose_name_plural': '能力领域',
                'ordering': ['skill_project', 'order', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillTreeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='版本')),
                ('name', models.CharField(max_length=120, verbose_name='版本名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_skill_tree_versions', to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('skill_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_tree_versions', to='standards.skillproject', verbose_name='技能项目')),
            ],
            options={
                'verbose_name': '标准技能树版本',
                'verbose_name_plural': '标准技能树版本',
                'ordering': ['skill_project', '-is_current', '-created_at', 'version'],
            },
        ),
        migrations.CreateModel(
            name='SkillNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('CATEGORY', '技能分类'), ('TOPIC', '能力主题'), ('SKILL', '标准技能点')], max_length=20, verbose_name='节点类型')),
                ('code', models.CharField(max_length=100, verbose_name='节点代码')),
                ('name', models.CharField(max_length=200, verbose_name='节点名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('difficulty', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='难度')),
                ('is_core', models.BooleanField(default=False, verbose_name='核心技能')),
                ('is_assessable', models.BooleanField(default=True, verbose_name='可考核')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='别名')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                ('capability_domain', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skill_nodes', to='standards.capabilitydomain', verbose_name='能力领域')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='standards.skillnode', verbose_name='父节点')),
                ('tree_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='standards.skilltreeversion', verbose_name='技能树版本')),
            ],
            options={
                'verbose_name': '技能节点',
                'verbose_name_plural': '技能节点',
                'ordering': ['tree_version', 'capability_domain__order', 'parent_id', 'order', 'code', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='capabilitydomain',
            constraint=models.UniqueConstraint(fields=('skill_project', 'code'), name='uniq_capabilitydomain_project_code'),
        ),
        migrations.AddConstraint(
            model_name='skilltreeversion',
            constraint=models.UniqueConstraint(fields=('skill_project', 'version'), name='uniq_skilltreeversion_project_version'),
        ),
        migrations.AddConstraint(
            model_name='skilltreeversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('skill_project',), name='uniq_current_skilltreeversion_per_project'),
        ),
        migrations.AddConstraint(
            model_name='skillnode',
            constraint=models.UniqueConstraint(fields=('tree_version', 'code'), name='uniq_skillnode_treeversion_code'),
        ),
    ]
