# Generated by Django 6.0.6 on 2026-08-18 02:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('core', '0002_retire_legacy_standard_stack'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='技能项目代码')),
                ('name', models.CharField(max_length=150, verbose_name='技能项目名称')),
                ('short_name', models.CharField(blank=True, max_length=80, verbose_name='简称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '技能项目',
                'verbose_name_plural': '技能项目',
                'ordering': ['order', 'code', 'name'],
                'permissions': [('manage_all_technical_domains', '管理全部训练主线技术领域')],
            },
        ),
        migrations.CreateModel(
            name='WSOSSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='章节代码')),
                ('name', models.CharField(max_length=160, verbose_name='章节名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                (
                    'weight',
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name='权重（%）',
                    ),
                ),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
            ],
            options={
                'verbose_name': 'WSOS 章节',
                'verbose_name_plural': 'WSOS 章节',
                'ordering': ['wsos_version', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='技能代码')),
                ('name', models.CharField(max_length=200, verbose_name='技能名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                (
                    'difficulty',
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name='难度',
                    ),
                ),
                ('is_core', models.BooleanField(default=False, verbose_name='核心技能')),
                ('is_assessable', models.BooleanField(default=True, verbose_name='可考核')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='标签')),
                ('aliases', models.JSONField(blank=True, default=list, verbose_name='别名')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'skill_project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='skills',
                        to='standards.skillproject',
                        verbose_name='技能项目',
                    ),
                ),
            ],
            options={
                'verbose_name': '技能',
                'verbose_name_plural': '技能',
                'ordering': ['skill_project', 'primary_domain__order', 'order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SkillTreeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='版本')),
                ('name', models.CharField(max_length=120, verbose_name='版本名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_skill_tree_versions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='创建人',
                    ),
                ),
                (
                    'skill_project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='skill_tree_versions',
                        to='standards.skillproject',
                        verbose_name='技能项目',
                    ),
                ),
            ],
            options={
                'verbose_name': '标准技能树版本',
                'verbose_name_plural': '标准技能树版本',
                'ordering': ['skill_project', '-is_current', '-created_at', 'version'],
            },
        ),
        migrations.CreateModel(
            name='TechnicalDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='领域代码')),
                ('name', models.CharField(max_length=120, verbose_name='领域名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'skill_project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='technical_domains',
                        to='standards.skillproject',
                        verbose_name='技能项目',
                    ),
                ),
            ],
            options={
                'verbose_name': '技术领域',
                'verbose_name_plural': '技术领域',
                'ordering': ['skill_project', 'order', 'code', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SkillTreeNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'node_type',
                    models.CharField(
                        choices=[('CATEGORY', '技能分类'), ('TOPIC', '能力主题'), ('SKILL', '技能')],
                        max_length=20,
                        verbose_name='节点类型',
                    ),
                ),
                ('code', models.CharField(max_length=100, verbose_name='节点代码')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='节点名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'parent',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='children',
                        to='standards.skilltreenode',
                        verbose_name='父节点',
                    ),
                ),
                (
                    'skill',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='tree_nodes',
                        to='standards.skill',
                        verbose_name='技能',
                    ),
                ),
                (
                    'tree_version',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='nodes',
                        to='standards.skilltreeversion',
                        verbose_name='技能树版本',
                    ),
                ),
                (
                    'technical_domain',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='skill_tree_nodes',
                        to='standards.technicaldomain',
                        verbose_name='技术领域',
                    ),
                ),
            ],
            options={
                'verbose_name': '技能树节点',
                'verbose_name_plural': '技能树节点',
                'ordering': ['tree_version', 'technical_domain__order', 'parent_id', 'order', 'code'],
            },
        ),
        migrations.AddField(
            model_name='skill',
            name='primary_domain',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='primary_skills',
                to='standards.technicaldomain',
                verbose_name='主要技术领域',
            ),
        ),
        migrations.AddField(
            model_name='skill',
            name='related_domains',
            field=models.ManyToManyField(
                blank=True, related_name='related_skills', to='standards.technicaldomain', verbose_name='关联技术领域'
            ),
        ),
        migrations.CreateModel(
            name='TechnicalDomainMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                (
                    'role',
                    models.CharField(
                        choices=[('lead_coach', '主教练'), ('coach', '教练')],
                        default='coach',
                        max_length=20,
                        verbose_name='职责',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'technical_domain',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='memberships',
                        to='standards.technicaldomain',
                        verbose_name='技术领域',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='technical_domain_memberships',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='用户',
                    ),
                ),
            ],
            options={
                'verbose_name': '技术领域教练',
                'verbose_name_plural': '技术领域教练',
                'ordering': ['technical_domain', 'role', 'user'],
            },
        ),
        migrations.CreateModel(
            name='SkillWSOSMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                (
                    'skill',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='wsos_mappings',
                        to='standards.skill',
                        verbose_name='技能',
                    ),
                ),
                (
                    'wsos_section',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='skill_mappings',
                        to='standards.wsossection',
                        verbose_name='WSOS 章节',
                    ),
                ),
            ],
            options={
                'verbose_name': '技能与 WSOS 映射',
                'verbose_name_plural': '技能与 WSOS 映射',
                'ordering': ['skill', 'wsos_section__order'],
            },
        ),
        migrations.CreateModel(
            name='WSOSVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, verbose_name='版本代码')),
                ('name', models.CharField(max_length=120, verbose_name='版本名称')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('is_current', models.BooleanField(default=False, verbose_name='当前版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='created_wsos_versions',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='创建人',
                    ),
                ),
                (
                    'skill_project',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='wsos_versions',
                        to='standards.skillproject',
                        verbose_name='技能项目',
                    ),
                ),
            ],
            options={
                'verbose_name': 'WSOS 版本',
                'verbose_name_plural': 'WSOS 版本',
                'ordering': ['skill_project', '-is_current', 'code'],
            },
        ),
        migrations.AddField(
            model_name='wsossection',
            name='wsos_version',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='sections',
                to='standards.wsosversion',
                verbose_name='WSOS 版本',
            ),
        ),
        migrations.AddConstraint(
            model_name='skilltreeversion',
            constraint=models.UniqueConstraint(
                fields=('skill_project', 'version'), name='uniq_skilltreeversion_project_version'
            ),
        ),
        migrations.AddConstraint(
            model_name='skilltreeversion',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_current', True)),
                fields=('skill_project',),
                name='uniq_current_skilltreeversion_per_project',
            ),
        ),
        migrations.AddConstraint(
            model_name='technicaldomain',
            constraint=models.UniqueConstraint(
                fields=('skill_project', 'code'), name='uniq_technicaldomain_project_code'
            ),
        ),
        migrations.AddConstraint(
            model_name='skilltreenode',
            constraint=models.UniqueConstraint(fields=('tree_version', 'code'), name='uniq_skilltreenode_version_code'),
        ),
        migrations.AddConstraint(
            model_name='skilltreenode',
            constraint=models.UniqueConstraint(
                condition=models.Q(('skill__isnull', False)),
                fields=('tree_version', 'skill'),
                name='uniq_skilltreenode_version_skill',
            ),
        ),
        migrations.AddConstraint(
            model_name='skill',
            constraint=models.UniqueConstraint(fields=('skill_project', 'code'), name='uniq_skill_project_code'),
        ),
        migrations.AddConstraint(
            model_name='technicaldomainmembership',
            constraint=models.UniqueConstraint(
                fields=('technical_domain', 'user'), name='uniq_technicaldomain_membership_user'
            ),
        ),
        migrations.AddConstraint(
            model_name='skillwsosmap',
            constraint=models.UniqueConstraint(fields=('skill', 'wsos_section'), name='uniq_skill_wsos_section'),
        ),
        migrations.AddConstraint(
            model_name='wsosversion',
            constraint=models.UniqueConstraint(fields=('skill_project', 'code'), name='uniq_wsosversion_project_code'),
        ),
        migrations.AddConstraint(
            model_name='wsosversion',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_current', True)),
                fields=('skill_project',),
                name='uniq_current_wsosversion_per_project',
            ),
        ),
        migrations.AddConstraint(
            model_name='wsossection',
            constraint=models.UniqueConstraint(fields=('wsos_version', 'code'), name='uniq_wsossection_version_code'),
        ),
    ]
