# Generated by Django 6.0.6 on 2026-08-18 11:39

from django.db import migrations, models


def set_single_active_project_as_default(apps, schema_editor):
    SkillProject = apps.get_model("standards", "SkillProject")
    database = schema_editor.connection.alias
    active_project_ids = list(
        SkillProject.objects.using(database).filter(is_active=True).values_list("pk", flat=True)[:2]
    )
    if len(active_project_ids) == 1:
        SkillProject.objects.using(database).filter(pk=active_project_ids[0]).update(is_default=True)


def clear_default_project(apps, schema_editor):
    SkillProject = apps.get_model("standards", "SkillProject")
    SkillProject.objects.using(schema_editor.connection.alias).update(is_default=False)


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillproject',
            name='is_default',
            field=models.BooleanField(default=False, help_text='新建业务对象时优先选择此技能项目；全系统最多只能设置一个默认项目。', verbose_name='默认项目'),
        ),
        migrations.RunPython(set_single_active_project_as_default, clear_default_project),
        migrations.AddConstraint(
            model_name='skillproject',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='uniq_default_skill_project'),
        ),
        migrations.AddConstraint(
            model_name='skillproject',
            constraint=models.CheckConstraint(condition=models.Q(('is_default', False), ('is_active', True), _connector='OR'), name='default_skill_project_must_be_active'),
        ),
    ]
