# Generated by Django 6.0.6 on 2026-08-18 15:21

import django.db.models.deletion
from django.db import migrations, models
from unicodedata import normalize


def normalize_term(value):
    folded = normalize("NFKC", value or "").casefold()
    return "".join(character for character in folded if not character.isspace())


def migrate_skill_terms(apps, schema_editor):
    Skill = apps.get_model("standards", "Skill")
    SkillTerm = apps.get_model("standards", "SkillTerm")
    database = schema_editor.connection.alias
    claimed = {}

    for skill in Skill.objects.using(database).order_by("pk"):
        terms = [("name", skill.name), *(("alias", alias) for alias in (skill.aliases or []))]
        seen_for_skill = set()
        for kind, term in terms:
            term = (term or "").strip()
            normalized_term = normalize_term(term)
            if not normalized_term or normalized_term in seen_for_skill:
                continue
            owner = claimed.get((skill.skill_project_id, normalized_term))
            if owner is not None and owner != skill.pk:
                raise RuntimeError(
                    f"技能称谓“{term}”在同一项目内属于多个技能，请先清理重复数据后再迁移。"
                )
            claimed[(skill.skill_project_id, normalized_term)] = skill.pk
            seen_for_skill.add(normalized_term)
            SkillTerm.objects.using(database).create(
                skill_project_id=skill.skill_project_id,
                skill_id=skill.pk,
                term=term,
                normalized_term=normalized_term,
                kind=kind,
            )


def restore_skill_aliases(apps, schema_editor):
    Skill = apps.get_model("standards", "Skill")
    database = schema_editor.connection.alias
    for skill in Skill.objects.using(database).all():
        skill.aliases = list(skill.terms.filter(kind="alias").values_list("term", flat=True))
        skill.save(update_fields=["aliases"])


class Migration(migrations.Migration):

    dependencies = [
        ('standards', '0002_skillproject_is_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='称谓')),
                ('normalized_term', models.CharField(editable=False, max_length=400, verbose_name='规范化称谓')),
                ('kind', models.CharField(choices=[('name', '正式名称'), ('alias', '别名')], max_length=10, verbose_name='称谓类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '技能称谓',
                'verbose_name_plural': '技能称谓',
                'ordering': ['skill_project', 'skill', 'kind', 'term'],
            },
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['skill_project', 'primary_domain__order', 'order', 'name', 'pk'], 'verbose_name': '技能', 'verbose_name_plural': '技能'},
        ),
        migrations.RemoveConstraint(
            model_name='skill',
            name='uniq_skill_project_code',
        ),
        migrations.AddField(
            model_name='skillterm',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='standards.skill', verbose_name='技能'),
        ),
        migrations.AddField(
            model_name='skillterm',
            name='skill_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_terms', to='standards.skillproject', verbose_name='技能项目'),
        ),
        migrations.RunPython(migrate_skill_terms, restore_skill_aliases),
        migrations.RemoveField(
            model_name='skill',
            name='aliases',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='code',
        ),
        migrations.AddConstraint(
            model_name='skillterm',
            constraint=models.CheckConstraint(condition=models.Q(('normalized_term', ''), _negated=True), name='skillterm_normalized_not_empty'),
        ),
        migrations.AddConstraint(
            model_name='skillterm',
            constraint=models.UniqueConstraint(fields=('skill_project', 'normalized_term'), name='uniq_skillterm_project_normalized'),
        ),
        migrations.AddConstraint(
            model_name='skillterm',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'name')), fields=('skill',), name='uniq_primary_skillterm_per_skill'),
        ),
    ]
