# Generated by Django 6.0.6 on 2026-08-23 00:39

import django.db.models.deletion
from django.db import migrations, models


def remove_retired_permission_rows(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    database = schema_editor.connection.alias if schema_editor else "default"
    Permission.objects.using(database).filter(
        content_type__app_label="standards",
        content_type__model="skillproject",
        codename="manage_all_technical_domains",
    ).delete()
    ContentType.objects.using(database).filter(
        app_label="standards",
        model="technicaldomainmembership",
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('standards', '0007_finalize_domain_skill_tree_versions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalDomainGroupScope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '技术领域用户组范围',
                'verbose_name_plural': '技术领域用户组范围',
                'ordering': ['group', 'technical_domain'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='technicaldomainmembership',
            name='uniq_technicaldomain_membership_user',
        ),
        migrations.AlterModelOptions(
            name='skillproject',
            options={
                'ordering': ['order', 'code', 'name'],
                'verbose_name': '技能项目',
                'verbose_name_plural': '技能项目',
            },
        ),
        migrations.AddField(
            model_name='technicaldomaingroupscope',
            name='group',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='technical_domain_scopes',
                to='auth.group',
                verbose_name='用户组',
            ),
        ),
        migrations.AddField(
            model_name='technicaldomaingroupscope',
            name='technical_domain',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='group_scopes',
                to='standards.technicaldomain',
                verbose_name='技术领域',
            ),
        ),
        migrations.RemoveField(
            model_name='technicaldomainmembership',
            name='technical_domain',
        ),
        migrations.RemoveField(
            model_name='technicaldomainmembership',
            name='user',
        ),
        migrations.AddConstraint(
            model_name='technicaldomaingroupscope',
            constraint=models.UniqueConstraint(
                fields=('group', 'technical_domain'), name='uniq_technicaldomain_group_scope'
            ),
        ),
        migrations.DeleteModel(
            name='TechnicalDomainMembership',
        ),
        migrations.RunPython(remove_retired_permission_rows, migrations.RunPython.noop),
    ]
