# Generated by Django 6.0.6 on 2026-09-05 01:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('standards', '0008_technicaldomaingroupscope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillproject',
            name='code',
            field=models.CharField(
                help_text='1–12 位英文字母或数字。',
                max_length=50,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        '\\A[A-Za-z0-9]{1,12}\\Z', '技能项目代码须为 1–12 位英文字母或数字。'
                    )
                ],
                verbose_name='技能项目代码',
            ),
        ),
    ]
