"""
Django settings for tmsproject project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
# from django.forms.renderers import TemplatesSetting

from pathlib import Path

import environ

env = environ.Env(DEBUG=(bool, False))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(env_file=BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-ervt8@=%%#n1vmzhs)$5^x%#bfk+*lnre8e)n=c243)mihbi@^'
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = env.bool('DEBUG', default=False) # type: ignore

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1']) # type: ignore


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'django.forms',
    # Custom apps
    'django_htmx',
    'django_tables2',
    'common',
    'accounts',
    'samba',
    'articles',
    'competitions',
    'skills',
    'traininglogs',
    'meeting',
    'notices',
]

SITE_ID = 1

MIDDLEWARE = [
    'django_htmx.middleware.HtmxMiddleware',     # django-htmx 中间件
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    'django.contrib.auth.middleware.LoginRequiredMiddleware',   # 启用将所有未认证请求重定向到登录页面
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',   # 启用 flatpages 中间件
]

ROOT_URLCONF = 'tmsproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'common.context_processors.custom_context',     # 自定义上下文处理器
            ],
        },
    },
]


# class CustomFormRenderer(TemplatesSetting):
#     form_template_name = "components/form_snippet.html"
#     # field_template_name = "field_snippet.html"

# FORM_RENDERER = "tmsproject.settings.CustomFormRenderer"


WSGI_APPLICATION = 'tmsproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': env.db(default=f'sqlite:///{BASE_DIR}/db.sqlite3') # type: ignore
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Media files (user uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'



# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 认证相关设置
# LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/'  # 登录成功后跳转的页面
# LOGOUT_REDIRECT_URL = '/accounts/login/'


# class CustomFormRenderer(TemplatesSetting):
#     form_template_name = BASE_DIR /  'templates' / 'form_snippet.html'

# FORM_RENDERER = 'tmsproject.settings.CustomFormRenderer'

# 自定义变量

# SITE INFO
SITE_INFO = {
    "site_name": env('SITE_NAME', default="ITNSA"), # type: ignore
    "site_description": env('SITE_DESCRIPTION', default="A simple training management system."), # type: ignore
    "site_keywords": env('SITE_KEYWORDS', default="TMS, Training Management System, Training, Management"), # type: ignore
    "site_author": env('SITE_AUTHOR', default="hdaojin"), # type: ignore
}

CACHE_TIMEOUT = env('CACHE_TIMEOUT', default=300) # type: ignore
UPLOAD_MAX_SIZE_MB = env('UPLOAD_MAX_SIZE_MB', default=10) # type: ignore
UPLOAD_MAX_SIZE = UPLOAD_MAX_SIZE_MB * 1024 * 1024  # type: ignore


WSCSKILL_NAME = env('WSCSKILL_NAME', default='网络系统管理项目') # type: ignore
INVITATION_CODE_TIMEOUT = env('INVITATION_CODE_TIMEOUT', default=86400)  # type: ignore # 1天,单位为秒

LOGS_DIR = env('LOGS_DIR', default='logs') # type: ignore
MEETING_FILE_DIR = env('MEETING_FILE_DIR', default='meetings') # type: ignore
NOTICE_ATTACHMENT_DIR = env('NOTICE_ATTACHMENT_DIR', default='notices') # type: ignore



