"""
Django settings for tmsproject project.

Generated by 'django-admin startproject' using Django 6.0+.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
# from django.forms.renderers import TemplatesSetting

from pathlib import Path

import environ

from core.constants import (
    DEFAULT_CACHE_TIMEOUT,
    DEFAULT_UPLOAD_MAX_SIZE_MB,
)

env = environ.Env(DEBUG=(bool, False))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Take environment variables from .env file
environ.Env.read_env(env_file=BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-ervt8@=%%#n1vmzhs)$5^x%#bfk+*lnre8e)n=c243)mihbi@^'
SECRET_KEY = env('SECRET_KEY', default='django-insecure-ervt8@=%%#n1vmzhs)$5^x%#bfk+*lnre8e)n=c243)mihbi@^') # type: ignore

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = env.bool('DEBUG', default=True) # type: ignore

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1']) # type: ignore

CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=[]) # type: ignore

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.flatpages',
    'django.forms',
    # Third-party apps
    'django_htmx',
    'django_tables2',
    'django_filters',
    # Local apps
    'core',
    'accounts',
    'samba',
    'articles',
    'competitions',
    'assessments.apps.AssessmentsConfig',
    'notes',
    'skills',
    'traininglogs',
    'meetings.apps.MeetingsConfig',
    'notices',
    'behaviors.apps.BehaviorsConfig',
]

# 开发模式下添加 demo 应用
if DEBUG:
    INSTALLED_APPS.append('demo')

SITE_ID = 1

MIDDLEWARE = [
    'django_htmx.middleware.HtmxMiddleware',     # django-htmx 中间件
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    
    'django.contrib.auth.middleware.LoginRequiredMiddleware',   # 启用将所有未认证请求重定向到登录页面
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',   # 启用 flatpages 中间件
]

ROOT_URLCONF = 'tmsproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.utils.context_processors.custom_context',     # 自定义上下文处理器
            ],
        },
    },
]


WSGI_APPLICATION = 'tmsproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': env.db(default=f'sqlite:///{BASE_DIR}/db.sqlite3') # type: ignore
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/


STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (user uploaded files)
# 注意：公共文件上传目录是通过Web服务器静态文件功能直接提供服务的，无法控制用户权限。
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 认证相关设置
# LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/accounts/home/'  # 登录成功后跳转的页面
# LOGOUT_REDIRECT_URL = '/accounts/login/'


# 自定义变量（默认值定义在 core/constants.py，可通过环境变量覆盖）
CACHE_TIMEOUT = env.int('CACHE_TIMEOUT', default=DEFAULT_CACHE_TIMEOUT)  # type: ignore
UPLOAD_MAX_SIZE_MB = env.int('UPLOAD_MAX_SIZE_MB', default=DEFAULT_UPLOAD_MAX_SIZE_MB)  # type: ignore
